/* İngilizce — ek sorular (Theme 5–8: festivals, city, transport, countries, food, nature, environment, planets, future). */
(function () {
  "use strict";
  const { R, sec, karistir, od, ek, S, Q, G } = OGR;

  /* ===================== THEME 5: FESTIVALS ===================== */
  SORU_EKLE("enfes.vocab",
    Q("enfes.vocab", "transfer", 2, "Read the poster and answer the question.<br><i>🎪 KITE FESTIVAL — Saturday, 10 a.m.–5 p.m., Seaside Park. Bring your own kite or make one in our workshop! There is a kite competition at 3 p.m. The winner gets a prize. Entry is free.</i><br>What can visitors do at the workshop?", "They can make a kite.",
      [["They can buy a ticket.", "dikkat", "Afişte “Entry is free” yazıyor; giriş ücretsiz, bilet almaya gerek yok."], ["They can win a prize.", "dikkat", "Ödül (prize) atölyede değil, saat 3'teki yarışmayı kazanana veriliyor."], ["They can watch a concert.", "bilgi", "Afişte konserden hiç söz edilmiyor; uydurma bilgiye dikkat et."]],
      "Afişte “workshop” sözcüğünün geçtiği cümleyi bul.",
      ["🔎 Soruyu anlayalım: Bir uçurtma festivali afişi var. Soru, atölyede (workshop) ne yapılabileceğini soruyor.",
       "💡 Hatırlayalım: workshop = atölye, yani bir şeyi yaparak öğrendiğin etkinlik. competition = yarışma, prize = ödül.",
       "✏️ Afişte “workshop” sözcüğünü arayalım: “Bring your own kite or make one in our workshop!”",
       "✏️ “make one” burada “make a kite” (bir uçurtma yap) demek; “one” uçurtmanın yerine kullanılmış.",
       "✅ Sonuç: Ziyaretçiler atölyede uçurtma yapabilir → They can make a kite.",
       "🔁 Kontrol edelim: Ödül yarışmayla, ücretsiz giriş “Entry is free” ile ilgili. Okuma sorularında cevabı metindeki cümleye dayandır."],
      { kural: "Okuma sorusunda önce sorudaki anahtar sözcüğü (workshop) metinde bul, cevabı o cümleden çıkar.", dogruNeden: "Afişte “make one in our workshop” yazıyor; “one” bir uçurtma demek." }),
    Q("enfes.vocab", "uygulama", 1, "Complete the sentence.<br><b>The band played music on the ___ and the audience clapped.</b>", "stage",
      [["ticket", "kavrama", "Bilet (ticket) bir kâğıttır; grup biletin üstünde müzik çalamaz."], ["costume", "kavrama", "Kostüm (costume) giyilen bir şeydir, bir yer değildir."], ["queue", "bilgi", "Kuyruk (queue) insanların sırada beklediği yerdir; müzisyenler orada çalmaz."]],
      "Müzisyenler konserde nerede durur ve çalar?",
      ["🔎 Soruyu anlayalım: Grup (band) bir yerde müzik çalıyor, seyirci (audience) alkışlıyor. Boşluğa bir YER gelmeli.",
       "💡 Hatırlayalım: stage = sahne, ticket = bilet, costume = kostüm, queue = sıra/kuyruk.",
       "✏️ Seçeneklerden hangisi “on the …” kalıbıyla bir yer bildiriyor? Yalnızca “stage”.",
       "✏️ Cümleyi okuyalım: The band played music on the stage. → Grup sahnede müzik çaldı.",
       "✅ Sonuç: Cevap “stage”.",
       "🔁 Kontrol edelim: Türkçesi anlamlı mı? “Grup sahnede çaldı, seyirciler alkışladı.” Evet, tam oturuyor."],
      { kural: "Konser kelimeleri: stage (sahne), band (müzik grubu), audience (seyirci), ticket (bilet).", dogruNeden: "Müzik grubu sahnede (on the stage) çalar." }),
    Q("enfes.vocab", "baglanti", 2, "Look at the table. Which event was <b>the most popular</b>?", "the puppet show",
      [["the parade", "dikkat", "Geçit törenini 120 kişi izledi; kukla gösterisinin seyircisi daha fazla."], ["the poetry contest", "dikkat", "Şiir yarışmasının seyircisi en az olandır (60 kişi)."], ["the fireworks show", "islem", "180 ile 210'u karşılaştır: 210 daha büyük, yani havai fişek ikinci sırada."]],
      "“Audience” sütunundaki en büyük sayıyı bul.",
      ["🔎 Soruyu anlayalım: Tabloda dört etkinlik ve seyirci sayıları var. “The most popular” = en popüler, yani en çok seyircisi olan.",
       "💡 Hatırlayalım: popular = sevilen, çok kişinin ilgilendiği. Theme 3'teki “the most …” kalıbı “en …” demektir.",
       "✏️ Sayıları yazalım: parade 120, puppet show 210, poetry contest 60, fireworks show 180.",
       "✏️ Karşılaştıralım: 210 > 180 > 120 > 60.",
       "✅ Sonuç: En çok seyirci kukla gösterisinde → the puppet show.",
       "🔁 Kontrol edelim: En az seyirci şiir yarışmasında (60). “Most” en büyük sayıyı, “least” en küçük sayıyı ister."],
      { gorsel: G.tablo(["Event", "Day", "Audience"], [["🥁 Parade", "Monday", "120"], ["🧸 Puppet show", "Tuesday", "210"], ["📜 Poetry contest", "Wednesday", "60"], ["🎆 Fireworks show", "Thursday", "180"]]),
        kural: "the most popular = en popüler → en büyük sayıyı ara.", dogruNeden: "210 kişiyle kukla gösterisi en çok seyirciye sahip." }),
  );

  SORU_EKLE("enfes.adj",
    Q("enfes.adj", "transfer", 2, "Complete the dialogue.<br>— Did you like the magic show?<br>— Yes! I was really ___. The magician made a rabbit disappear!", "amazed",
      [["amazing", "kavrama", "Öznesi “I” (ben); kişinin duygusu -ed ile anlatılır. “I was amazing” “Ben harikaydım” demek olur."], ["boring", "kavrama", "Konuşmacı gösteriyi beğenmiş; “boring” hem anlamca hem biçimce uymuyor."], ["amaze", "bilgi", "“amaze” fiilin yalın hâli; was'tan sonra sıfat gerekir."]],
      "Öznenin kim olduğuna bak: bir kişi mi, bir şey mi?",
      ["🔎 Soruyu anlayalım: Konuşmacı “I was really ___” diyor. Boşluk konuşmacının DUYGUSUNU anlatıyor.",
       "💡 Hatırlayalım: -ed sıfatlar kişinin hissini (I was amazed = Çok şaşırdım/hayran kaldım), -ing sıfatlar şeyin özelliğini (The show was amazing) anlatır.",
       "✏️ Özne “I” → bir kişi. O hâlde -ed biten sıfat gerekir.",
       "✏️ Konuşmacı gösteriyi beğenmiş (Yes!), yani olumlu bir duygu: amazed.",
       "✅ Sonuç: I was really amazed.",
       "🔁 Kontrol edelim: Gösteriyi anlatmak isteseydik “The show was amazing” derdik. Kişi → -ed, şey → -ing."],
      { kural: "I / we / she + was/were + -ed (amazed, excited). The show + was + -ing (amazing, exciting).", dogruNeden: "Kişinin hissettiği duygu -ed sıfatla anlatılır: I was amazed." }),
    Q("enfes.adj", "uygulama", 2, "Find the <b>mistake</b> in the sentence.<br><b>We waited for two hours and the queue was very tired.</b>", "tired → tiring",
      [["waited → waiting", "kavrama", "“waited” geçmiş zaman ve doğru kullanılmış; hata sıfatta."], ["was → were", "kavrama", "“the queue” tekil; “was” doğru."], ["two hours → two hour", "bilgi", "İki ve fazlası için çoğul gerekir: two hours doğru."]],
      "Sıra (queue) bir şey hissedebilir mi?",
      ["🔎 Soruyu anlayalım: Cümlede bir hata var; onu bulup düzeltmeliyiz.",
       "💡 Hatırlayalım: tired = yorgun (kişinin hissi), tiring = yorucu (şeyin özelliği).",
       "✏️ Cümlenin öznesi “the queue” (sıra/kuyruk). Kuyruk bir şeydir, yorgunluk hissetmez.",
       "✏️ Kuyruğun özelliği anlatılmalı → -ing: The queue was very tiring. (Sıra çok yorucuydu.)",
       "✅ Sonuç: Hata “tired”; doğrusu “tiring”.",
       "🔁 Kontrol edelim: Diğer parçalar doğru: waited (geçmiş), was (tekil), two hours (çoğul). Kişiyi anlatmak isteseydik “We were very tired” derdik."],
      { kural: "Şey/olay → -ing (tiring queue). Kişi → -ed (tired people).", dogruNeden: "Kuyruk bir şeydir; özelliği -ing sıfatla anlatılır: tiring." }),
    Q("enfes.adj", "baglanti", 2, "Read the text and answer the question.<br><i>Last Sunday, Ada went to a science festival with her brother Efe. Ada loved the robot show. She was very excited. Efe didn't like the long talk about rocks. It was boring for him and he fell asleep!</i><br>Which sentence is <b>true</b>?", "Efe was bored during the talk.",
      [["Efe was boring during the talk.", "kavrama", "“Efe was boring” “Efe sıkıcıydı” demektir; metinde Efe'nin sıkıldığı anlatılıyor."], ["Ada was bored at the robot show.", "dikkat", "Metne göre Ada robot gösterisini çok sevdi ve heyecanlandı."], ["The robot show was excited.", "kavrama", "Gösteri bir şeydir; özelliği “exciting” ile anlatılır, “excited” ile değil."]],
      "Hem metne hem -ing/-ed kuralına uyan cümleyi seç.",
      ["🔎 Soruyu anlayalım: Ada ve Efe bir bilim festivaline gitmiş. Hem metne uygun hem dil bilgisi doğru cümleyi bulacağız.",
       "💡 Hatırlayalım: Kişinin hissi -ed (bored, excited), şeyin özelliği -ing (boring, exciting).",
       "✏️ Metin: Efe kayalarla ilgili uzun konuşmayı sevmedi, uyuyakaldı → Efe sıkıldı → Efe was bored.",
       "✏️ Diğerlerini eleyelim: Ada sıkılmadı, heyecanlandı. “The robot show was excited” yanlış; doğrusu “exciting”.",
       "✅ Sonuç: Efe was bored during the talk.",
       "🔁 Kontrol edelim: Konuşmayı anlatmak isteseydik “The talk was boring” derdik; o da doğru olurdu ama seçeneklerde yok."],
      { kural: "bored = sıkılmış (kişi) · boring = sıkıcı (şey).", dogruNeden: "Efe konuşmada uyuyakaldı, yani sıkıldı; kişi olduğu için “bored” doğru." }),
  );

  SORU_EKLE("enfes.past",
    z => {
      const kisi = sec([["Ali", "he"], ["Zeynep", "she"], ["your parents", "they"], ["Mert and Ece", "they"], ["your cousin", "he"], ["the students", "they"]]);
      const yer = sec(["at the film festival", "at the street parade", "at the folk dance show", "at the book fair", "at the food festival"]);
      const zaman = sec(["last Saturday", "yesterday", "last night", "two days ago"]);
      const tekil = kisi[1] !== "they", dogru = (tekil ? "Was " : "Were ") + `${kisi[0]} ${yer} ${zaman}?`;
      const yanlisFiil = (tekil ? "Were " : "Was ") + `${kisi[0]} ${yer} ${zaman}?`;
      const kisa = tekil ? `Yes, ${kisi[1]} was.` : "Yes, they were.";
      return S({ kaz: "enfes.past", duzey: "uygulama", zorluk: 2,
        soru: `Complete the dialogue with the correct question.<br>— ___<br>— <b>${kisa}</b> ${tekil ? (kisi[1] === "he" ? "He" : "She") + " was" : "They were"} very happy there.`,
        dogru,
        yanlis: [[yanlisFiil, "kavrama", `“${kisi[0]}” ${tekil ? "tekil, “was” ister" : "çoğul, “were” ister"}.`],
          [`Did ${kisi[0]} ${yer} ${zaman}?`, "bilgi", "Bu cümlede asıl fiil yok; “be” ile kurulan soruda did kullanılmaz, was/were başa gelir."],
          [`${kisi[0][0].toUpperCase() + kisi[0].slice(1)} ${tekil ? "was" : "were"} ${yer} ${zaman}?`, "kavrama", "Bu bir soru değil; soruda was/were öznenin önüne geçer."]],
        ipucu: "Cevaptaki “was/were” sözcüğü sana sorunun nasıl başlayacağını söylüyor.",
        cozum: ["🔎 Soruyu anlayalım: Cevap verilmiş, ona uyan evet-hayır sorusunu seçeceğiz.",
          "💡 Hatırlayalım: Geçmişte “be” ile soru: Was/Were + özne + …? (Was he at home? Were they happy?)",
          `✏️ Kısa cevapta “${kisa}” var; demek ki soru “${tekil ? "Was" : "Were"}” ile başlamalı.`,
          `✏️ Özne “${kisi[0]}” → ${tekil ? "tekil (he/she) → was" : "çoğul (they) → were"}. Uyum tamam.`,
          `✅ Sonuç: ${dogru}`,
          "🔁 Kontrol edelim: “did” yalnızca asıl fiil (go, watch…) olan cümlelerde kullanılır; burada fiil “be” olduğu için did gerekmez."],
        kural: "Was/Were + özne + …? → Yes, he was. / No, they weren't.", dogruNeden: `Özne ${tekil ? "tekil olduğu için Was" : "çoğul olduğu için Were"} ile başlayan soru cevaba uyuyor.` });
    },
    Q("enfes.past", "transfer", 2, "Read the diary and answer the question.<br><i>Friday, 3 May. Today was our school festival. The weather was sunny and warm. My friends were in a folk dance show. They were great! I was at the cake stand with my mum. The cakes were delicious and they weren't expensive.</i><br>Where was the writer?", "at the cake stand",
      [["in the folk dance show", "dikkat", "Halk dansı gösterisinde yazarın arkadaşları vardı, yazarın kendisi değil."], ["at home with her mum", "dikkat", "Yazar annesiyle evde değil, pasta standındaydı."], ["at a concert", "bilgi", "Günlükte konserden söz edilmiyor."]],
      "“I was …” diye başlayan cümleyi bul.",
      ["🔎 Soruyu anlayalım: Bir günlük sayfası var. Soru “Yazar neredeydi?” diye soruyor.",
       "💡 Hatırlayalım: “I was at …” = “… -daydım.” Yazar kendinden “I” diye söz eder.",
       "✏️ Metinde “I” geçen cümleyi bulalım: “I was at the cake stand with my mum.”",
       "✏️ “My friends were in a folk dance show” cümlesi arkadaşlarla ilgili; soru yazarı soruyor.",
       "✅ Sonuç: Yazar pasta standındaydı → at the cake stand.",
       "🔁 Kontrol edelim: Okuma sorularında “kim” sorulduğuna dikkat et: I = yazar, my friends = arkadaşları."],
      { kural: "I was / he was / she was · we were / they were / you were.", dogruNeden: "Metinde “I was at the cake stand with my mum” yazıyor." }),
    Q("enfes.past", "uygulama", 2, "Find the <b>mistake</b>.<br><b>The fireworks was very colourful last night.</b>", "was → were",
      [["very → much", "bilgi", "Sıfattan önce “very” kullanılır; “very colourful” doğru."], ["last night → tonight", "kavrama", "“last night” geçmişi gösterir ve cümleyle uyumludur."], ["colourful → colour", "bilgi", "“colour” isimdir; was/were'den sonra burada sıfat gerekir."]],
      "Özne tekil mi, çoğul mu?",
      ["🔎 Soruyu anlayalım: Cümlede bir dil bilgisi hatası var.",
       "💡 Hatırlayalım: Tekil isim → was, çoğul isim → were.",
       "✏️ Özne “the fireworks” (havai fişekler). Sonundaki -s çoğul olduğunu gösteriyor.",
       "✏️ Çoğul özne “were” ister: The fireworks were very colourful.",
       "✅ Sonuç: Hata “was”; doğrusu “were”.",
       "🔁 Kontrol edelim: “fireworks” yerine “they” koy: They were … Doğru! Bir dahaki sefere özneyi zamirle değiştirerek dene."],
      { kural: "Çoğul özne (fireworks = they) → were.", dogruNeden: "“The fireworks” çoğul olduğu için “were” kullanılmalı." }),
  );

  SORU_EKLE("enfes.like",
    z => {
      const [fiil, ing] = sec([["dance", "dancing"], ["swim", "swimming"], ["ride", "riding"], ["make", "making"], ["run", "running"], ["sing", "singing"], ["take", "taking"], ["shop", "shopping"]]);
      const yanlisIng = fiil.endsWith("e") ? fiil + "ing" : (["swim", "run", "shop"].includes(fiil) ? fiil + "ing" : fiil + "ingg");
      const kisi = sec(["My brother", "Elif", "Our teacher", "My best friend"]);
      const duygu = sec(["loves", "likes", "hates", "enjoys"]);
      const ek_ = { dance: "at festivals", swim: "in the sea", ride: "a bike", make: "costumes", run: "in the park", sing: "songs", take: "photos", shop: "at the market" }[fiil];
      return S({ kaz: "enfes.like", duzey: "uygulama", zorluk: 2,
        soru: `Choose the correct form.<br><b>${kisi} ${duygu} ___ ${ek_}.</b> (${fiil})`, dogru: ing,
        yanlis: [[yanlisIng, "islem", fiil.endsWith("e") ? "Sonu -e ile biten fiillerde -e düşer: make → making." : "Tek heceli, ünsüz-ünlü-ünsüz ile biten fiilde son harf çiftlenir: swim → swimming."],
          [fiil, "bilgi", `“${duygu}” fiilinden sonra fiil -ing alır; yalın hâl olmaz.`],
          [fiil + "s", "kavrama", "Özneye -s eki zaten ana fiile (" + duygu + ") gelmiş; ikinci fiil -ing alır."]],
        ipucu: "like / love / hate / enjoy'dan sonra fiil hangi eki alır? Yazımına da dikkat et.",
        cozum: ["🔎 Soruyu anlayalım: Parantezdeki fiilin doğru hâlini seçeceğiz.",
          `💡 Hatırlayalım: like, love, hate, enjoy + fiil-ing (I love dancing). want + to + fiil (I want to dance).`,
          `✏️ Cümlede “${duygu}” var → ikinci fiil -ing alacak.`,
          fiil.endsWith("e") && fiil !== "see" ? `✏️ “${fiil}” -e ile bitiyor; -e düşer, -ing eklenir: ${fiil} → ${ing}.` : (["swim", "run", "shop"].includes(fiil) ? `✏️ “${fiil}” tek heceli ve ünsüz-ünlü-ünsüz ile bitiyor; son harf çiftlenir: ${fiil} → ${ing}.` : `✏️ “${fiil}” fiiline doğrudan -ing eklenir: ${fiil} → ${ing}.`),
          `✅ Sonuç: ${kisi} ${duygu} ${ing} ${ek_}.`,
          "🔁 Kontrol edelim: -ing yazım kuralları: make → making, swim → swimming, sing → singing."],
        kural: "love / like / hate / enjoy + V-ing · want + to + V.", dogruNeden: `“${duygu}” sonrasında fiil -ing alır ve doğru yazımı “${ing}”.` });
    },
    Q("enfes.like", "transfer", 2, "Complete the dialogue.<br>— There is a pottery workshop at the festival. Do you want to join?<br>— ___ I love making things with my hands.", "Yes, I want to try it!",
      [["No, I hate it.", "dikkat", "Konuşmacı “I love making things with my hands” diyor; “I hate it” bu cümleyle çelişiyor."], ["Yes, I want trying it!", "bilgi", "“want”tan sonra “to + fiil” gelir: want to try."], ["Yes, I want try it!", "bilgi", "“want” ile fiil arasında “to” eksik."]],
      "İkinci cümle olumlu mu, olumsuz mu? want'tan sonra ne gelir?",
      ["🔎 Soruyu anlayalım: Arkadaşı çömlek atölyesine katılmak isteyip istemediğini soruyor. Cevap ikinci cümleyle uyumlu olmalı.",
       "💡 Hatırlayalım: want + to + fiil (I want to go). love + fiil-ing (I love making).",
       "✏️ Cevabın devamı: “I love making things with my hands.” → Konuşmacı el işini seviyor, yani cevap olumlu.",
       "✏️ Olumlu seçeneklerden dil bilgisi doğru olanı seçelim: “want to try” ✔, “want trying” ✘, “want try” ✘.",
       "✅ Sonuç: Yes, I want to try it!",
       "🔁 Kontrol edelim: Diyalog sorularında hem anlam (olumlu/olumsuz) hem kalıp doğru olmalı."],
      { kural: "want TO + fiil; love / like / hate + fiil-ING.", dogruNeden: "Konuşmacı el işini seviyor ve “want to try” doğru kalıp." }),
    Q("enfes.like", "baglanti", 2, "Look at the chart. It shows how many students in 6/A <b>love</b> each activity. Which sentence is <b>true</b>?", "More students love dancing than singing.",
      [["Most students love watching films.", "islem", "Film izlemeyi 6 öğrenci seviyor; bu en küçük sayı."], ["Ten students love singing.", "dikkat", "Şarkı söylemenin sütunu 8'i gösteriyor, 10'u değil."], ["Nobody loves playing games.", "dikkat", "Oyun oynamayı 12 öğrenci seviyor."]],
      "Grafikten sayıları tek tek oku, sonra cümleleri karşılaştır.",
      ["🔎 Soruyu anlayalım: Sütun grafiği 6/A sınıfında her etkinliği seven öğrenci sayısını gösteriyor. Doğru cümleyi bulacağız.",
       "💡 Hatırlayalım: more … than = -den daha çok. most = en çok. nobody = hiç kimse.",
       "✏️ Sayıları okuyalım: dancing 10, singing 8, games 12, films 6.",
       "✏️ “More students love dancing than singing” → 10 > 8. Doğru!",
       "✅ Sonuç: More students love dancing than singing.",
       "🔁 Kontrol edelim: En çok sevilen “games” (12), en az “films” (6). Diğer seçenekler grafikle uyuşmuyor."],
      { gorsel: G.sutun([["dancing", 10], ["singing", 8], ["games", 12], ["films", 6]], { baslik: "Students in 6/A", birim: "students" }),
        kural: "Grafik sorularında önce sayıları yaz, sonra cümledeki karşılaştırmayı kontrol et.", dogruNeden: "Dans etmeyi 10, şarkı söylemeyi 8 öğrenci seviyor; 10 > 8." }),
  );

  /* ===================== THEME 5: CITY ===================== */
  SORU_EKLE("encty.places",
    Q("encty.places", "aciklama", 1, "You can borrow books and study quietly here. Where is it?", "library",
      [["stadium", "bilgi", "Stadyumda maç izlenir; kitap ödünç alınmaz."], ["bakery", "bilgi", "Fırında ekmek ve pasta satılır."], ["pharmacy", "bilgi", "Eczanede ilaç alınır."]],
      "borrow books = kitap ödünç almak.",
      ["🔎 Soruyu anlayalım: Tanımı verilen yeri bulacağız: kitap ödünç alınan ve sessizce çalışılan yer.",
       "💡 Hatırlayalım: library = kütüphane, bookshop = kitapçı (kitap satın alınır), stadium = stadyum, bakery = fırın, pharmacy = eczane.",
       "✏️ “borrow” ödünç almak demek; kitapları ödünç verip geri alan yer kütüphanedir.",
       "✏️ “study quietly” (sessizce çalışmak) da kütüphaneye uyuyor.",
       "✅ Sonuç: library.",
       "🔁 Kontrol edelim: Dikkat! “library” kitapçı değil, kütüphanedir. Kitap satın almak için “bookshop”a gidersin."],
      { kural: "library = kütüphane (ödünç) · bookshop = kitapçı (satın alma).", dogruNeden: "Kitap ödünç alınan ve sessiz çalışılan yer kütüphanedir (library)." }),
    Q("encty.places", "transfer", 2, "Read the two texts and answer the question.<br><i><b>Kerem:</b> My town is small and quiet. There are old stone houses and a historic castle. The streets are clean.<br><b>Nehir:</b> My city is very big and modern. There are lots of skyscrapers and shopping centres. The traffic is terrible in the mornings.</i><br>Which sentence is <b>true</b>?", "Nehir's city is crowded and noisy in the mornings.",
      [["Kerem's town is modern and noisy.", "dikkat", "Kerem kasabasının küçük ve sakin (quiet) olduğunu, eski taş evleri olduğunu söylüyor."], ["There is a castle in Nehir's city.", "dikkat", "Tarihî kale (castle) Kerem'in kasabasında var."], ["Nehir's city doesn't have any tall buildings.", "dikkat", "Nehir'in şehrinde çok sayıda gökdelen (skyscraper) var."]],
      "Her bilgiyi doğru kişiyle eşleştir.",
      ["🔎 Soruyu anlayalım: İki kişi yaşadığı yeri anlatıyor. Metinlere göre doğru cümleyi bulacağız.",
       "💡 Hatırlayalım: quiet = sakin, historic = tarihî, modern = modern, crowded = kalabalık, noisy = gürültülü, terrible traffic = korkunç trafik.",
       "✏️ Kerem: küçük, sakin, tarihî kale, eski evler, temiz sokaklar.",
       "✏️ Nehir: büyük, modern, gökdelenler, alışveriş merkezleri, sabahları korkunç trafik → kalabalık ve gürültülü.",
       "✅ Sonuç: Nehir's city is crowded and noisy in the mornings.",
       "🔁 Kontrol edelim: Metinde “crowded” ve “noisy” sözcükleri yok ama “terrible traffic” bunu anlatıyor. Bu, metinden çıkarım yapmaktır."],
      { kural: "Karşılaştırmalı okuma: bilgileri iki ayrı listeye yaz, sonra seçenekleri kontrol et.", dogruNeden: "Korkunç trafik, şehrin sabahları kalabalık ve gürültülü olduğunu gösterir." }),
    Q("encty.places", "uygulama", 2, "Find the <b>odd one out</b> (the word that is different).", "noisy",
      [["museum", "kavrama", "Museum bir yerdir; diğer yerlerle (cinema, hospital) aynı gruptadır."], ["cinema", "kavrama", "Cinema bir yerdir; grubun bir üyesidir."], ["hospital", "kavrama", "Hospital bir yerdir; grubun bir üyesidir."]],
      "Hangisi bir yer değil, bir özellik bildiriyor?",
      ["🔎 Soruyu anlayalım: Dört sözcükten farklı olanı bulacağız: museum, cinema, hospital, noisy.",
       "💡 Hatırlayalım: Yer adları isimdir (noun); noisy, crowded, historic gibi sözcükler sıfattır (adjective).",
       "✏️ museum (müze), cinema (sinema), hospital (hastane) → üçü de şehirde bir YER.",
       "✏️ noisy (gürültülü) → bir yerin nasıl olduğunu anlatan SIFAT.",
       "✅ Sonuç: Farklı olan “noisy”.",
       "🔁 Kontrol edelim: “a noisy museum” diyebiliriz ama “a museum cinema” diyemeyiz; noisy diğerlerini niteliyor."],
      { kural: "Şehir yerleri isimdir; noisy, crowded, modern, historic gibi kelimeler sıfattır.", dogruNeden: "noisy bir yer adı değil, bir sıfattır." }),
  );

  SORU_EKLE("encty.prep",
    z => {
      const yerler = ["bank", "café", "bakery", "post office", "museum"];
      const d = karistir(yerler);
      // Sıra: d[0] d[1] d[2] (aynı sokakta, soldan sağa)
      const tip = R(0, 1);
      let soru, dogru, yanlis, adim;
      if (tip === 0) {
        soru = `Look at the street: <b>${d[0]} – ${d[1]} – ${d[2]}</b>.<br>Where is the ${d[1]}?`;
        dogru = `It's between the ${d[0]} and the ${d[2]}.`;
        yanlis = [[`It's next to the ${d[3]}.`, "dikkat", `${d[3]} bu sokakta yok.`], [`It's opposite the ${d[0]}.`, "kavrama", "opposite = karşısında; bu binalar yan yana, karşı karşıya değil."], [`It's between the ${d[0]} and the ${d[3]}.`, "dikkat", `${d[3]} sokakta yok; ${d[1]} iki komşusunun arasında.`]];
        adim = [`✏️ ${d[1]} ortada duruyor; solunda ${d[0]}, sağında ${d[2]} var.`, "✏️ İki yerin arasında olmak = between … and …"];
      } else {
        soru = `Look at the street: <b>${d[0]} – ${d[1]} – ${d[2]}</b>.<br>Where is the ${d[2]}?`;
        dogru = `It's next to the ${d[1]}.`;
        yanlis = [[`It's next to the ${d[0]}.`, "dikkat", `${d[2]} ile ${d[0]} arasında ${d[1]} var; yan yana değiller.`], [`It's between the ${d[0]} and the ${d[1]}.`, "dikkat", `Bu iki yerin arasında ${d[2]} değil, hiçbir yer yok; ${d[2]} en sonda.`], [`It's behind the ${d[1]}.`, "kavrama", "behind = arkasında; binalar yan yana duruyor."]];
        adim = [`✏️ ${d[2]} sokağın en sonunda; tek komşusu ${d[1]}.`, "✏️ Hemen yanında olmak = next to."];
      }
      return S({ kaz: "encty.prep", duzey: "uygulama", zorluk: 2, soru, dogru, yanlis,
        ipucu: "Binaların sırasını parmağınla takip et.",
        cozum: ["🔎 Soruyu anlayalım: Bir sokaktaki binalar soldan sağa sıralanmış. Sorulan yerin konumunu bulacağız.",
          "💡 Hatırlayalım: next to = yanında, between … and … = … ile … arasında, opposite = karşısında, behind = arkasında.",
          ...adim, `✅ Sonuç: ${dogru}`,
          "🔁 Kontrol edelim: Cevaptaki yerleri sokakta göster; ikisi de orada ve konum doğru mu? Evet."],
        kural: "between A and B: A ile B arasında · next to: hemen yanında.", dogruNeden: "Sokaktaki sıraya göre konum bu şekilde." });
    },
    Q("encty.prep", "transfer", 2, "Read and find the place.<br><i>My favourite shop is in Park Street. It is opposite the school and next to the cinema. It sells toys and games.</i><br>Look at the map. Which shop is it?", "Shop B",
      [["Shop A", "dikkat", "A dükkânı okulun karşısında ama sinemanın yanında değil, eczanenin yanında."], ["Shop C", "dikkat", "C dükkânı sinemanın yanında ama okulun karşısında değil, parkın karşısında."], ["Shop D", "dikkat", "D dükkânı ne okulun karşısında ne de sinemanın yanında."]],
      "İki ipucunu birlikte kullan: opposite the school + next to the cinema.",
      ["🔎 Soruyu anlayalım: Metindeki iki ipucuyla haritadaki dükkânı bulacağız.",
       "💡 Hatırlayalım: opposite = (caddenin) karşısında, next to = yanında.",
       "✏️ 1. ipucu: Okulun karşısında olan dükkânlar: A ve B (okul caddenin öbür tarafında, A ile B'nin karşısında).",
       "✏️ 2. ipucu: Sinemanın yanında olanlar: B ve C. İki ipucunu da sağlayan tek dükkân: B.",
       "✅ Sonuç: Shop B.",
       "🔁 Kontrol edelim: B'nin karşısında okul, yanında sinema var. İki koşul da tamam."],
      { gorsel: G.tablo(["North side", "", "", "", ""], [["💊 Pharmacy", "Shop A", "Shop B", "🎬 Cinema", "Shop C"], ["⬅️ — — —", "— PARK STREET —", "— — —", "— — —", "— — ➡️"], ["🏡 House", "🏫 School", "🏫 School", "☕ Café", "🌳 Park"]]).replace("Shop D", "Shop D") + "<p><i>Shop D is in Lale Street, behind the park.</i></p>",
        kural: "İki koşullu konum sorularında her koşulu sağlayanları ayrı ayrı yaz, ortak olanı seç.", dogruNeden: "Okulun karşısında ve sinemanın yanında olan tek dükkân B." }),
    Q("encty.prep", "uygulama", 1, "Look at the picture: 🌳🐱🌳<br>The cat is ___ the two trees.", "between",
      [["behind", "kavrama", "behind = arkasında; kedi ağaçların arkasında değil, ortasında."], ["next to", "kavrama", "next to tek bir şeyin yanını anlatır; iki şeyin ortası için between kullanılır."], ["opposite", "kavrama", "opposite = karşısında; kedi ağaçların karşısında değil."]],
      "Kedi iki ağacın neresinde?",
      ["🔎 Soruyu anlayalım: Resimde kedi iki ağacın ortasında duruyor.",
       "💡 Hatırlayalım: between = iki şeyin arasında, next to = yanında, behind = arkasında, opposite = karşısında.",
       "✏️ Kedinin solunda bir ağaç, sağında bir ağaç var.",
       "✏️ İki şeyin ortasında olmak → between.",
       "✅ Sonuç: The cat is between the two trees.",
       "🔁 Kontrol edelim: “between” her zaman iki şey ister: between the bank and the café, between the two trees."],
      { kural: "between = iki şeyin arasında.", dogruNeden: "Kedi iki ağacın ortasında olduğu için between kullanılır." }),
  );

  SORU_EKLE("encty.dir",
    Q("encty.dir", "transfer", 2, "Complete the dialogue.<br>— Excuse me, is there a pharmacy near here?<br>— ___<br>— Thank you very much!<br>— You're welcome.", "Yes, there is. Go straight and turn left. It's next to the bank.",
      [["No, it isn't. It's on the right.", "kavrama", "“Is there…?” sorusuna “Yes, there is / No, there isn't” ile cevap verilir; ayrıca yeri yoksa sağda olamaz."], ["Yes, I do. Turn left.", "bilgi", "“Is there…?” sorusu “do” ile cevaplanmaz."], ["Go to bed early.", "kavrama", "Bu bir öğüt; yol tarifi değil."]],
      "“Is there…?” sorusunun kısa cevabı nasıl olur? Ardından yol tarifi gelmeli.",
      ["🔎 Soruyu anlayalım: Bir kişi yakında eczane olup olmadığını soruyor; ardından teşekkür ediyor. Demek ki ona yol tarif edilmiş.",
       "💡 Hatırlayalım: Is there a …? → Yes, there is. / No, there isn't. Yol tarifi: go straight, turn left/right, it's next to/opposite …",
       "✏️ Teşekkür edildiğine göre cevap olumlu ve yol tarifi içeriyor.",
       "✏️ “Yes, there is.” + “Go straight and turn left. It's next to the bank.” → hem kısa cevap hem tarif doğru.",
       "✅ Sonuç: Yes, there is. Go straight and turn left. It's next to the bank.",
       "🔁 Kontrol edelim: “You're welcome” = Rica ederim; tarif eden kişi teşekküre böyle cevap verir."],
      { kural: "Is there…? → Yes, there is / No, there isn't. Sonra tarif: Go straight… Turn left…", dogruNeden: "Doğru kısa cevap ve uygun yol tarifi içeren tek seçenek bu." }),
    Q("encty.dir", "uygulama", 2, "You are at the ⭐. Follow the directions:<br><b>Go straight. Take the first turning on the right. The cinema is on your left.</b><br>Look at the map. Which building is the cinema?", "B",
      [["A", "dikkat", "A, ilk sağdan girince sağ tarafta kalıyor; tarifte “on your left” diyor."], ["C", "dikkat", "C, sola dönünce karşına çıkar; tarif sağa dönmeyi söylüyor."], ["D", "dikkat", "D, ikinci sapakta; tarif birinci sapağı (first turning) söylüyor."]],
      "Adım adım ilerle: önce düz, sonra ilk sağ, sonra sol tarafına bak.",
      ["🔎 Soruyu anlayalım: Yıldızdan başlayıp tarifi uygulayarak sinemayı bulacağız.",
       "💡 Hatırlayalım: go straight = düz git, the first turning on the right = sağdaki ilk sapak, on your left = solunda.",
       "✏️ Düz gidiyoruz, sağdaki ilk sokağa (1st Street) giriyoruz.",
       "✏️ Bu sokakta solumuzda B, sağımızda A var. Tarif “on your left” diyor.",
       "✅ Sonuç: Sinema B binasıdır.",
       "🔁 Kontrol edelim: Sağa döndükten sonra yönler de döner; kendini sokağın içinde yürüyormuş gibi düşün."],
      { gorsel: G.tablo(["", "1st Street ➡️", "2nd Street ➡️"], [["Left side of the street", "B", "D"], ["Right side of the street", "A", "E"], ["Main Street ⬆️ (⭐ start)", "turn right here", "turn right here"], ["Left of Main Street", "C", "F"]]),
        kural: "Dönüşten sonra sağ/sol, yürüdüğün yöne göre belirlenir.", dogruNeden: "İlk sağ sapaktan girince solda kalan bina B'dir." }),
    Q("encty.dir", "aciklama", 1, "What does <b>“Go past the park”</b> mean?", "Parkın önünden geçip yürümeye devam et.",
      [["Parkın içine gir.", "kavrama", "İçine girmek “go into the park” demektir."], ["Parktan geri dön.", "kavrama", "Geri dönmek “go back” demektir."], ["Parkta dur ve bekle.", "kavrama", "Durmak “stop” demektir; “go past” geçip gitmektir."]],
      "“past” burada geçip gitmeyi anlatır.",
      ["🔎 Soruyu anlayalım: “Go past the park” tarif ifadesinin anlamını bulacağız.",
       "💡 Hatırlayalım: go straight = düz git, go past = önünden geçip devam et, go into = içine gir, go back = geri dön.",
       "✏️ “past” bir yerin yanından geçip onu arkada bırakmayı anlatır.",
       "✏️ Örnek: Go past the park and the school is on your right. → Parkı geç, okul sağında.",
       "✅ Sonuç: Parkın önünden geçip yürümeye devam et.",
       "🔁 Kontrol edelim: Parkta durmuyoruz, içine de girmiyoruz; parkı geride bırakıyoruz."],
      { kural: "go past = önünden geçip devam et.", dogruNeden: "“Go past” bir yerin önünden geçip yürümeye devam etmek demektir." }),
  );
})();
