/* 6. sınıf Türkçe — 1. tema: Dilimizin Zenginliği.
 * Konular: Bir Kelime Seyyahı · Türkçenin Beyliği · Türküz, Türkçe Konuşuruz · Türk Dil Kurumu Sunar (Kaşık) ·
 * Azerbaycan-Türkiye (Okumak Gibisi Yok!) · Üretmek Gibisi Yok!
 * Ders kitabı metinleri kullanılmaz; anlatımlar ve sorulardaki kısa metinler özgündür.
 */
(function () {
  "use strict";
  const { R, sec, karistir, S, Q, G } = OGR;
  const K = kural => ({ kural });

  /* =========================== 1. Bir Kelime Seyyahı =========================== */
  KONU_EKLE("tr", {
    id: "tr_seyyah", tema: "tr1", ad: "Bir Kelime Seyyahı", sayfa: "s. 12", gorev: "Kelime keşfetme ve anlam bulma",
    kazanimlar: [
      { id: "trsey.anlam", ad: "Sözcüğün gerçek, mecaz ve terim anlamını ayırt etme" },
      { id: "trsey.sozluk", ad: "Sözlük kullanarak ve bağlamdan yararlanarak sözcüğün anlamını bulma" },
      { id: "trsey.eszit", ad: "Eş anlamlı ve zıt anlamlı sözcükleri belirleme" },
    ],
    anlatim: [
      { baslik: "Sözcüklerin anlam yolculuğu",
        metin: "Bir sözcük, cümleden cümleye farklı anlamlar kazanabilir.<br><b>Gerçek anlam:</b> Sözcüğün akla gelen ilk anlamıdır. “Taş duvar” derken gerçek taşı anlatırız.<br><b>Mecaz anlam:</b> Sözcüğün gerçek anlamından uzaklaşıp yeni bir anlam kazanmasıdır. “Taş kalpli” denince duygusuz bir insan anlatılır.<br><b>Terim anlam:</b> Bir bilim, sanat ya da meslek dalına özgü anlamdır. Matematikteki “açı”, müzikteki “nota” terimdir.",
        ornek: "“Soğuk su içtim.” (gerçek) · “Bana soğuk davrandı.” (mecaz) · “Dik açının ölçüsü 90 derecedir.” (terim)",
        durak: { soru: "“Çocuğun tatlı sözleri hepimizi güldürdü.” cümlesinde “tatlı” sözcüğü hangi anlamda kullanılmıştır?", secenekler: [["Mecaz anlam", true, "Sözlerin tadı olmaz; “tatlı söz” hoşa giden, sevimli söz demektir."], ["Gerçek anlam", false, "Gerçek anlamda tatlı, şekerli bir tadı anlatır; sözlerin tadı yoktur."], ["Terim anlam", false, "“Tatlı” burada bir bilim ya da meslek dalına özgü değildir."], ["Zıt anlam", false, "Zıt anlam iki sözcük arasındaki ilişkidir; tek sözcüğün anlam türü değildir."]] } },
      { baslik: "Sözlük: kelime seyyahının haritası",
        metin: "<b>Seyyah</b>, gezgin demektir. Kelime seyyahı da yeni sözcükler keşfeden okurdur. Onun haritası <b>sözlüktür</b>.<br>Sözlükte sözcükler <b>alfabetik sırayla</b> dizilir. İlk harfler aynıysa ikinci, üçüncü harflere bakılır.<br>Sözlük yanımızda olmadığında <b>bağlamdan</b>, yani sözcüğün geçtiği cümleden ve metnin bütününden anlamı tahmin ederiz. Sonra tahminimizi sözlükten kontrol ederiz.",
        ornek: "“defter, demir, deniz, dere” sözcüklerinin ilk iki harfi aynıdır (d, e). Üçüncü harflere (f, m, n, r) bakılarak sıralanır.",
        durak: { soru: "Sözlükte “kalem, kale, kalp, kalın” sözcüklerinden hangisi en önce gelir?", secenekler: [["kale", true, "“kale”, “kalem”in başıdır; kısa olan önce gelir. k-a-l-e, k-a-l-ı, k-a-l-p sırasında e önce gelir."], ["kalem", false, "“kale” sözcüğü “kalem”in ilk dört harfidir; kısa olan önce yazılır."], ["kalın", false, "Dördüncü harflere bak: e, ı, p. Alfabede e, ı'dan önce gelir."], ["kalp", false, "Dördüncü harf p'dir; e ve ı'dan sonra gelir."]] } },
      { baslik: "Eş anlam ve zıt anlam",
        metin: "<b>Eş anlamlı sözcükler:</b> Yazılışları farklı, anlamları aynı ya da çok yakın olan sözcüklerdir: kara–siyah, okul–mektep, yanıt–cevap, gezgin–seyyah.<br><b>Zıt anlamlı sözcükler:</b> Anlamca birbirinin karşıtı olan sözcüklerdir: uzun–kısa, cesur–korkak, erken–geç.<br>Yazarken aynı sözcüğü tekrar etmemek için eş anlamlılarından yararlanırız. Bu, dilimizin zenginliğini gösterir.",
        ornek: "“Sorunun yanıtını buldum. Bu cevap çok doğru.” (yanıt–cevap eş anlamlı) · “Gece gündüz çalıştı.” (gece–gündüz zıt anlamlı)",
        durak: { soru: "Hangi sözcük çiftinde zıt anlam vardır?", secenekler: [["geniş – dar", true, "Geniş ve dar birbirinin karşıtıdır."], ["yanıt – cevap", false, "Bu iki sözcük aynı anlama gelir; eş anlamlıdır."], ["okul – mektep", false, "Mektep, okulun eski adıdır; eş anlamlıdırlar."], ["gezgin – seyyah", false, "Seyyah, gezgin demektir; eş anlamlıdırlar."]] } },
    ],
    uret: {
      "trsey.anlam": [
        Q("trsey.anlam", "aciklama", 1, "“Kalbi taş gibiydi.” cümlesinde “taş” sözcüğü hangi anlamda kullanılmıştır?", "Mecaz anlam",
          [["Gerçek anlam", "kavrama", "Gerçek anlamda taş, sert bir maddedir; burada kalbin duygusuzluğu anlatılıyor."], ["Terim anlam", "bilgi", "Terim anlam bir bilim ya da sanat dalına özgüdür."], ["Zıt anlam", "kavrama", "Zıt anlam iki sözcük arasındaki ilişkidir."]],
          "Taş gerçekten kalbin içinde mi, yoksa bir özelliği mi anlatılıyor?",
          ["Cümlede taşın kendisinden söz edilmiyor.", "“Taş gibi kalp”, duygusuz ve katı bir kişiyi anlatır.", "Sözcük gerçek anlamından uzaklaştığı için mecaz anlamlıdır."],
          K("Gerçek anlam: ilk akla gelen anlam. Mecaz anlam: gerçek anlamından uzaklaşmış anlam. Terim anlam: bir bilim ya da sanat dalına özgü anlam.")),
        Q("trsey.anlam", "hatirlama", 1, "Bir bilim, sanat ya da meslek dalına özgü anlam taşıyan sözcüklere ne ad verilir?", "Terim anlamlı sözcük",
          [["Mecaz anlamlı sözcük", "bilgi", "Mecaz anlam, sözcüğün gerçek anlamından uzaklaşmasıdır; bir bilim dalına özgü olması değildir."], ["Eş anlamlı sözcük", "bilgi", "Eş anlam, iki sözcüğün aynı anlama gelmesidir."], ["Zıt anlamlı sözcük", "bilgi", "Zıt anlam, iki sözcüğün karşıt anlamlı olmasıdır."]],
          "Matematikteki “açı”, müzikteki “nota” sözcüklerini düşün.",
          ["Soru, bir alana özgü anlamın adını istiyor.", "“Açı” matematiğe, “nota” müziğe özgüdür.", "Bu tür anlama terim anlam denir."],
          K("Terim anlam: bir bilim, sanat ya da meslek dalına özgü anlam (açı, hücre, nota, cümle).")),
        Q("trsey.anlam", "uygulama", 2, "Aşağıdaki cümlelerin hangisinde “ağır” sözcüğü gerçek anlamıyla kullanılmıştır?", "Bu valiz çok ağır, tek başıma kaldıramıyorum.",
          [["Arkadaşının ağır sözleri onu çok üzdü.", "kavrama", "Sözlerin ağırlığı ölçülmez; burada “kırıcı” anlamında, mecazdır."], ["Babam ağır başlı, sakin bir insandır.", "kavrama", "“Ağır başlı” ciddi ve olgun demektir; mecaz anlamdır."], ["Bu kitabın konusu bana biraz ağır geldi.", "kavrama", "Burada “anlaşılması zor” anlamındadır; mecazdır."]],
          "Hangi cümlede gerçekten tartıya konabilecek bir ağırlıktan söz ediliyor?",
          ["Gerçek anlamda “ağır”, kaldırması zor, kütlesi büyük demektir.", "Valizin ağırlığı ölçülebilir; diğerlerinde söz, kişilik ya da konu anlatılıyor.", "Gerçek anlam valiz cümlesindedir."],
          K("Bir sözcüğün gerçek anlamını bulmak için onu ilk akla gelen anlamıyla, somut olarak düşün.")),
        Q("trsey.anlam", "uygulama", 2, "“Matematik dersinde açıları ölçmeyi öğrendik.” cümlesinde “açı” sözcüğü hangi anlamdadır?", "Terim anlam",
          [["Mecaz anlam", "kavrama", "“Açı” burada gerçek anlamından uzaklaşmamış; matematiğe özgü bir kavramdır."], ["Zıt anlam", "kavrama", "Zıt anlam iki sözcük arasındaki ilişkidir; tek sözcüğün anlam türü değildir."], ["Eş anlam", "kavrama", "Eş anlam iki sözcük arasındaki ilişkidir."]],
          "Sözcük hangi derste, hangi alanda kullanılıyor?",
          ["Cümlede matematik dersinden söz ediliyor.", "“Açı”, matematikte iki ışının oluşturduğu şekildir; bu alana özgüdür.", "Bir bilim dalına özgü olduğu için terim anlamlıdır."],
          K("Bir derse ya da mesleğe özgü kavramlar terim anlamlıdır: kesir, hücre, özne, nota.")),
        Q("trsey.anlam", "transfer", 2, "Teneffüste arkadaşın sana “Bugün Elif bana çok soğuk davrandı.” dedi. Buradaki “soğuk” sözcüğü ne anlatıyor?", "Elif'in ilgisiz ve mesafeli davrandığını (mecaz anlam)",
          [["Elif'in elinin buz gibi olduğunu (gerçek anlam)", "kavrama", "Davranışın sıcaklığı termometreyle ölçülmez; burada mecaz anlam var."], ["Havanın çok soğuk olduğunu (gerçek anlam)", "dikkat", "Cümlede havadan değil, Elif'in davranışından söz ediliyor."], ["Fen dersindeki ısı kavramını (terim anlam)", "kavrama", "Cümlede bir derse özgü kavram anlatılmıyor."]],
          "“Soğuk davranmak” sözünde gerçekten bir sıcaklık ölçülebilir mi?",
          ["Sözcük bir davranışı nitelendiriyor.", "Davranışlar soğuk ya da sıcak olamaz; burada ilgisizlik anlatılıyor.", "Gerçek anlamından uzaklaştığı için mecaz anlamdır."],
          K("Bir özellik, gerçekte o özelliği taşıyamayacak bir şeye yüklenirse sözcük mecaz anlam kazanır.")),
      ],
      "trsey.sozluk": [
        Q("trsey.sozluk", "hatirlama", 1, "Sözlükte sözcükler hangi sıraya göre dizilir?", "Alfabetik sıraya göre",
          [["Uzunluklarına göre", "bilgi", "Sözlükte kısa ya da uzun olmasına göre değil, harf sırasına göre dizilir."], ["Kullanım sıklığına göre", "bilgi", "Sözlükte çok kullanılan sözcükler öne alınmaz."], ["Anlamlarına göre gruplanarak", "bilgi", "Sözcükler anlam gruplarına göre değil, harf sırasına göre dizilir."]],
          "Sözlükte bir sözcüğü hızlıca bulabilmemizi sağlayan düzeni düşün.",
          ["Soru, sözlüğün düzenini soruyor.", "Sözlükte önce a ile başlayanlar, sonra b ile başlayanlar gelir.", "Bu düzen alfabetik sıradır."],
          K("Sözlükte sözcükler alfabetik sıradadır; ilk harfler aynıysa sonraki harflere bakılır.")),
        Q("trsey.sozluk", "uygulama", 2, "Aşağıdaki sözcüklerden hangisi sözlükte en önce yer alır?", "defter",
          [["demir", "islem", "Üçüncü harflere bak: f, m'den önce gelir; “defter” daha öndedir."], ["deniz", "islem", "Üçüncü harf n'dir; f, n'den önce gelir."], ["dere", "islem", "Üçüncü harf r'dir; f, r'den önce gelir."]],
          "İlk iki harf hepsinde aynı (d, e). Üçüncü harflere bak.",
          ["Bütün sözcükler “de” ile başlıyor.", "Üçüncü harfler: f (defter), m (demir), n (deniz), r (dere).", "Alfabede f en önde olduğu için “defter” ilk sırada yer alır."],
          K("İlk harfler aynıysa sıralamada ilk farklı harfe bakılır.")),
        Q("trsey.sozluk", "aciklama", 2, "<i>Seyyah, yıllarca uzak diyarları dolaştı. Gittiği her şehirde yeni insanlar tanıdı, gördüklerini defterine not etti.</i><br><br>Bu metne göre “seyyah” sözcüğünün anlamı nedir?", "Gezgin",
          [["Yazar", "dikkat", "Defterine not alması onu yazar yapmaz; metnin asıl vurgusu gezmesidir."], ["Tüccar", "kavrama", "Metinde alışveriş ya da ticaretten söz edilmiyor."], ["Öğretmen", "kavrama", "Metinde ders anlatmaktan söz edilmiyor."]],
          "Seyyahın metinde en çok yaptığı iş nedir?",
          ["Bağlamdan anlam bulmak isteniyor.", "Seyyah “uzak diyarları dolaştı”, “her şehirde” yeni insanlar tanıdı.", "Sürekli gezen kişiye gezgin denir; seyyah gezgin demektir."],
          K("Bağlamdan anlam bulma: Bilmediğin sözcüğün çevresindeki ipuçlarını (eylemleri, örnekleri) kullan.")),
        Q("trsey.sozluk", "aciklama", 2, "<i>Dedem çok cömert biridir. Elindekini komşularıyla paylaşmayı sever, kapısını çalan kimseyi eli boş göndermez.</i><br><br>Bu metne göre “cömert” ne demektir?", "Eli açık, paylaşmayı seven",
          [["Eli sıkı, paylaşmayı sevmeyen", "kavrama", "Bu, cimrinin anlamıdır; metindeki dede her şeyini paylaşıyor."], ["Çok çalışkan", "dikkat", "Metinde dedenin çalışmasından söz edilmiyor."], ["Çabuk sinirlenen", "dikkat", "Metinde dedenin öfkesinden söz edilmiyor."]],
          "Dede ne yapıyor? “paylaşmayı sever”, “eli boş göndermez”.",
          ["Sözcüğün anlamını metindeki ipuçlarından bulmalıyız.", "Dede elindekini paylaşıyor ve kimseyi eli boş göndermiyor.", "Bu özellik “eli açık, cömert” olmaktır."],
          K("Metindeki örnek davranışlar, bilinmeyen sözcüğün anlamına en güçlü ipucudur.")),
        Q("trsey.sozluk", "transfer", 1, "Kitap okurken anlamını bilmediğin bir sözcükle karşılaştın ve yanında sözlük yok. Önce ne yapmalısın?", "Cümlenin ve metnin gelişinden anlamını tahmin etmeye çalışmalıyım.",
          [["Sözcüğü hiç düşünmeden atlamalıyım.", "strateji", "Atlarsan metni tam anlayamayabilirsin; önce tahmin etmeyi denemelisin."], ["Kitabı okumayı hemen bırakmalıyım.", "strateji", "Bir sözcük yüzünden okumayı bırakmak gerekmez; bağlam sana yardım eder."], ["Sözcüğü anlamını bilmeden ezberlemeliyim.", "strateji", "Anlamını bilmediğin sözcüğü ezberlemek işe yaramaz."]],
          "Kelime seyyahının sözlük yokken kullandığı ipucunu hatırla.",
          ["Elimizde sözlük yok, ama metin var.", "Sözcüğün geçtiği cümle ve çevresi anlamına ipucu verir.", "Önce tahmin ederim, sonra fırsat bulunca sözlükten doğrularım."],
          K("Bilinmeyen sözcük: 1) Bağlamdan tahmin et. 2) Sözlükten doğrula. 3) Kendi cümlende kullan.")),
        Q("trsey.sozluk", "baglanti", 2, "Sözlükte “taş” maddesinde bir anlamın başında “mec.” kısaltması yazıyor. Bu kısaltma neyi gösterir?", "O anlamın mecaz anlam olduğunu",
          [["O anlamın terim anlam olduğunu", "bilgi", "Terim anlamlar genellikle hangi bilim dalına ait olduğu yazılarak gösterilir (mat., fiz. gibi)."], ["Sözcüğün yabancı kökenli olduğunu", "bilgi", "Kısaltma köken değil, anlam türünü gösteriyor."], ["Sözcüğün zıt anlamlısını", "bilgi", "Zıt anlamlılar bu kısaltmayla gösterilmez."]],
          "“mec.” hangi anlam türünün kısaltması olabilir? Mecaz…",
          ["Sözlüklerde bazı anlamların önüne kısaltmalar konur.", "“mec.”, “mecaz” sözcüğünün kısaltmasıdır.", "Demek ki o anlam, sözcüğün mecaz anlamıdır."],
          K("Sözlük kısaltmaları anlamın türünü gösterir: “mec.” mecaz anlamı belirtir.")),
      ],
      "trsey.eszit": [
        Q("trsey.eszit", "hatirlama", 1, "Yazılışları farklı, anlamları aynı ya da çok yakın olan sözcüklere ne denir?", "Eş anlamlı sözcükler",
          [["Zıt anlamlı sözcükler", "bilgi", "Zıt anlamlılar, anlamca birbirinin karşıtı olan sözcüklerdir."], ["Sesteş sözcükler", "bilgi", "Sesteşlerde yazılış aynı, anlam farklıdır; burada tam tersi soruluyor."], ["Terim anlamlı sözcükler", "bilgi", "Terim anlam, bir alana özgü anlamdır."]],
          "“okul – mektep” gibi çiftleri düşün.",
          ["Soru, yazılışı farklı ama anlamı aynı olan sözcükleri soruyor.", "“Okul” ile “mektep” aynı yeri anlatır.", "Bunlara eş anlamlı sözcükler denir."],
          K("Eş anlamlı: kara–siyah, yanıt–cevap. Zıt anlamlı: uzun–kısa, erken–geç.")),
        Q("trsey.eszit", "uygulama", 1, "“Siyah” sözcüğünün eş anlamlısı hangisidir?", "kara",
          [["ak", "kavrama", "“Ak”, beyaz demektir; siyahın zıt anlamlısıdır."], ["gri", "kavrama", "Gri farklı bir renktir; siyahla aynı anlamda değildir."], ["kırmızı", "kavrama", "Kırmızı başka bir renktir."]],
          "Siyah bir kalem için başka hangi rengi söyleyebiliriz?",
          ["Siyahla aynı anlama gelen sözcük isteniyor.", "“Kara tahta”, “kara kedi” derken siyahı anlatırız.", "Siyahın eş anlamlısı “kara”dır."],
          K("Eş anlamlıyı bulmak için sözcüğü cümlede değiştir; anlam bozulmuyorsa eş anlamlıdır.")),
        Q("trsey.eszit", "uygulama", 1, "“Cesur” sözcüğünün zıt anlamlısı hangisidir?", "korkak",
          [["yiğit", "kavrama", "“Yiğit”, cesurun eş anlamlısıdır; zıttı değildir."], ["güçlü", "kavrama", "Güçlü olmak cesaretle ilgili değildir; zıt anlam da değildir."], ["akıllı", "kavrama", "Akıllı, cesurla ilgisiz bir özelliktir."]],
          "Cesur olmayan, her şeyden çekinen kişiye ne denir?",
          ["Cesurun karşıt anlamlısı isteniyor.", "Cesur kişi korkmadan davranır; karşıtı korkan kişidir.", "Zıt anlamlısı “korkak”tır."],
          K("Zıt anlam: birbirinin karşıtı olan sözcükler (cesur–korkak, cömert–cimri).")),
        Q("trsey.eszit", "uygulama", 2, "Aşağıdaki cümlelerin hangisinde zıt anlamlı sözcükler birlikte kullanılmıştır?", "Gece gündüz demeden sınava çalıştı.",
          [["Okula mektebe giden çocuklar sevinçliydi.", "kavrama", "“Okul” ve “mektep” eş anlamlıdır, zıt değildir."], ["Kırmızı elmayı kardeşime verdim.", "dikkat", "Bu cümlede zıt anlamlı bir sözcük çifti yok."], ["Hızlı hızlı yürüyerek eve vardık.", "kavrama", "Burada aynı sözcük tekrar edilmiş; zıt anlam yok."]],
          "Birbirinin karşıtı olan iki sözcük arıyorsun.",
          ["Cümlelerde karşıt anlamlı sözcük çifti aranıyor.", "“Gece” ile “gündüz” birbirinin karşıtıdır.", "Zıt anlamlı sözcükler ilk cümlede birlikte kullanılmıştır."],
          K("Zıt anlamlı sözcükler bir arada kullanılınca anlatıma güç katar: gece gündüz, aşağı yukarı, az çok.")),
        Q("trsey.eszit", "transfer", 2, "Ödevinde “Tatilde güzel bir kasabaya gittik. Kasabanın güzel sokaklarında dolaştık.” yazdın. İkinci cümlede “güzel” sözcüğünün yerine anlam bozulmadan hangisi kullanılabilir?", "hoş",
          [["çirkin", "kavrama", "“Çirkin”, güzelin zıt anlamlısıdır; anlam tamamen değişir."], ["büyük", "kavrama", "Büyük, boyutu anlatır; güzelin eş anlamlısı değildir."], ["hızlı", "kavrama", "Hızlı, sokakları anlatmak için anlamsız olur."]],
          "Tekrarı önlemek için anlamca en yakın sözcüğü seç.",
          ["Aynı sözcüğün tekrarını önlemek isteniyor.", "“Güzel” ile anlamca en yakın sözcük “hoş”tur.", "“Kasabanın hoş sokaklarında dolaştık.” cümlesinde anlam bozulmaz."],
          K("Yazılarında aynı sözcüğü tekrar etmemek için eş anlamlılarından yararlan.")),
        Q("trsey.eszit", "baglanti", 1, "Sözlükte “seyyah” sözcüğünün karşısında “gezgin” yazıyor. Bu iki sözcük arasında nasıl bir anlam ilişkisi vardır?", "Eş anlamlıdırlar.",
          [["Zıt anlamlıdırlar.", "kavrama", "Gezgin ve seyyah aynı kişiyi anlatır; karşıt değildir."], ["Biri gerçek, biri mecaz anlamlıdır.", "kavrama", "İkisi de gerçek anlamıyla gezen kişiyi anlatır."], ["Aralarında hiçbir anlam ilişkisi yoktur.", "dikkat", "Sözlük, birini ötekiyle açıklıyor; aynı anlama geliyorlar."]],
          "Sözlük bir sözcüğü açıklarken bazen eş anlamlısını yazar.",
          ["Sözlük “seyyah”ı “gezgin” ile açıklamış.", "İki sözcük aynı anlamı taşıyor.", "Bu nedenle eş anlamlıdırlar."],
          K("Sözlükler bir sözcüğü açıklarken sık sık eş anlamlısını verir.")),
      ],
    },
    oyun: [
      { tur: "eslestir", kaz: "trsey.eszit", soru: "Sözcükleri eş anlamlılarıyla eşleştir.", ciftler: [["siyah", "kara"], ["mektep", "okul"], ["cevap", "yanıt"], ["seyyah", "gezgin"]], aciklama: "Siyah–kara, mektep–okul, cevap–yanıt ve seyyah–gezgin eş anlamlıdır; yazılışları farklı, anlamları aynıdır." },
      { tur: "eslestir", kaz: "trsey.eszit", soru: "Sözcükleri zıt anlamlılarıyla eşleştir.", ciftler: [["cesur", "korkak"], ["uzun", "kısa"], ["erken", "geç"], ["cömert", "cimri"]], aciklama: "Bu çiftlerdeki sözcükler anlamca birbirinin karşıtıdır." },
      { tur: "sirala", kaz: "trsey.sozluk", soru: "Sözcükleri sözlükteki sırasına göre diz.", ogeler: ["defter", "demir", "deniz", "dere"], aciklama: "İlk iki harf aynı (de). Üçüncü harflere bakılır: f, m, n, r." },
      { tur: "eslestir", kaz: "trsey.anlam", soru: "Cümleleri “soğuk” sözcüğünün anlam türüyle eşleştir.", ciftler: [["Soğuk su içtim.", "gerçek anlam"], ["Bana soğuk davrandı.", "mecaz anlam"], ["Soğuk cephe yağış getirdi.", "terim anlam"]], aciklama: "Suyun soğukluğu gerçek, davranışın soğukluğu mecaz anlamdır. “Soğuk cephe” coğrafya ve meteorolojiye özgü bir terimdir." },
      { tur: "uret", kaz: "trsey.anlam", soru: "KELİME harfleriyle en az 3 anlamlı kelime üret.", harfler: "KELİME", kelimeler: ["kelime", "melek", "emek", "emel", "leke", "ilke", "ekim", "kel", "kil", "kim", "mil", "ilk", "kem", "lime", "el", "ek", "il"], hedef: 3, aciklama: "Örnekler: kelime, melek, emek, leke, ilke, ekim, kil, mil. Her harfi en fazla bir kez kullanabilirsin; E harfi iki tane." },
    ],
  });

  /* =========================== 2. Türkçenin Beyliği =========================== */
  KONU_EKLE("tr", {
    id: "tr_beylik", tema: "tr1", ad: "Türkçenin Beyliği", sayfa: "s. 24", gorev: "Kelimelerle cümle kurma ve dil bilgisi",
    kazanimlar: [
      { id: "trbey.kokek", ad: "Sözcüğün kökünü ve eklerini ayırt etme" },
      { id: "trbey.yapimcekim", ad: "Yapım eki ile çekim ekini ayırt etme" },
      { id: "trbey.cumle", ad: "Sözcüklerden anlamlı ve kurallı cümle kurma" },
    ],
    anlatim: [
      { baslik: "Kök ve ek",
        metin: "Türkçe <b>eklemeli</b> bir dildir: Sözcüklerin sonuna ekler getirerek yeni sözcükler ve anlamlar oluştururuz.<br><b>Kök:</b> Sözcüğün anlamlı, daha küçük parçalara ayrılamayan ilk bölümüdür.<br><b>Ek:</b> Köke eklenen, tek başına anlamı olmayan parçadır.<br>Kökü bulmak için sözcüğün sonundan ekleri tek tek atarız; anlamlı en küçük parça kalınca durur.",
        ornek: "göz-lük-çü-ler → kök: göz · ekler: -lük, -çü, -ler",
        durak: { soru: "“denizciler” sözcüğünün kökü hangisidir?", secenekler: [["deniz", true, "Ekler atıldığında (-ci, -ler) anlamlı en küçük parça “deniz” kalır."], ["denizci", false, "“denizci”de -ci eki vardır; kök ekten arındırılmış hâldir."], ["den", false, "“den” tek başına bu sözcüğün anlamını taşımaz."], ["-ler", false, "“-ler” bir ektir, kök değildir."]] } },
      { baslik: "Yapım eki ve çekim eki",
        metin: "<b>Yapım ekleri</b> sözcükten yeni bir sözcük türetir; anlamı değiştirir: göz → gözlük, tuz → tuzlu, balık → balıkçı.<br><b>Çekim ekleri</b> yeni sözcük türetmez; sözcüğü cümleye bağlar ya da çoğul, hâl, iyelik gibi görevler kazandırır: kitap → kitaplar, ev → evde, okul → okulum.<br>Bir sözcükte önce yapım ekleri, sonra çekim ekleri gelir.",
        ornek: "balık-çı-lar-dan: “-çı” yapım eki (yeni sözcük: balıkçı), “-lar” ve “-dan” çekim ekleri.",
        durak: { soru: "Hangi sözcükte yalnızca çekim eki vardır?", secenekler: [["kalemler", true, "“-ler” çoğul ekidir; yeni bir sözcük türetmez, çekim ekidir."], ["kalemlik", false, "“-lik” eki yeni bir sözcük (kalem konan yer) türetmiştir; yapım ekidir."], ["gözcü", false, "“-cü” eki yeni bir sözcük türetmiştir; yapım ekidir."], ["tuzlu", false, "“-lu” eki yeni bir sözcük türetmiştir; yapım ekidir."]] } },
      { baslik: "Sözcüklerden cümleye",
        metin: "Sözcükler bir araya gelip bir duyguyu, düşünceyi ya da olayı tam olarak anlatınca <b>cümle</b> oluşur.<br>Türkçede kurallı cümlelerde iş, oluş ya da durum bildiren <b>yüklem</b> genellikle <b>sondadır</b>.<br>Anlamlı bir cümle kurmak için: 1) Ne anlatmak istediğine karar ver. 2) Yüklemi sona koy. 3) Kim, ne, nerede, ne zaman gibi bilgileri yüklemden önce sırala. 4) Cümleyi büyük harfle başlat, uygun noktalama işaretiyle bitir.",
        ornek: "dün / kitap / okudum / ilginç / bir → “Dün ilginç bir kitap okudum.”",
        durak: { soru: "Hangisi anlamca tamamlanmış bir cümledir?", secenekler: [["Annem bahçeye çiçek dikti.", true, "Kimin, ne yaptığı tam olarak anlatılmış; yüklem (dikti) sondadır."], ["Bahçeye çiçek ve", false, "Söz yarım kalmış; ne olduğu anlatılmıyor."], ["Sabah erkenden okula giderken", false, "“Giderken ne oldu?” sorusu cevapsız kalıyor."], ["Kırmızı güzel büyük", false, "Yalnızca özellikler sıralanmış; bir yargı yok."]] } },
    ],
    uret: {
      "trbey.kokek": [
        Q("trbey.kokek", "hatirlama", 1, "Bir sözcüğün anlamlı, daha küçük parçalara ayrılamayan ilk bölümüne ne denir?", "Kök",
          [["Ek", "bilgi", "Ek, köke eklenen ve tek başına anlamı olmayan parçadır."], ["Hece", "bilgi", "Hece, bir solukta çıkarılan ses birimidir; anlamla ilgili değildir."], ["Cümle", "bilgi", "Cümle, sözcüklerin bir araya gelmesiyle oluşur."]],
          "“gözlük” sözcüğünde anlamlı en küçük parça hangisi?",
          ["Sözcüğün temel, anlamlı parçası soruluyor.", "“gözlük”te “göz” anlamlıdır ve daha küçük anlamlı parçaya bölünemez.", "Bu bölüme kök denir."],
          K("Kök: anlamlı en küçük parça. Ek: köke eklenen, tek başına anlamı olmayan parça.")),
        Q("trbey.kokek", "uygulama", 1, "“kitaplık” sözcüğünün kökü hangisidir?", "kitap",
          [["kitaplık", "kavrama", "Bu, sözcüğün tamamıdır; içinde -lık eki vardır."], ["-lık", "kavrama", "“-lık” bir ektir, kök değildir."], ["kit", "islem", "“kit” bu sözcükte anlamlı bir parça değildir; kökü bulurken fazla kestin."]],
          "Sözcüğün sonundaki eki at; geriye anlamlı ne kalıyor?",
          ["“kitaplık” sözcüğünün sonunda “-lık” eki var.", "Ek atılınca “kitap” kalır; anlamlıdır ve daha fazla bölünemez.", "Kök “kitap”tır."],
          K("Kökü bulmak için ekleri sondan başa doğru tek tek at.")),
        Q("trbey.kokek", "uygulama", 2, "“gözlükçüler” sözcüğünde kaç ek vardır?", "3",
          [["2", "islem", "Ekleri yeniden say: -lük, -çü, -ler."], ["4", "islem", "Kökü (göz) ek gibi saymış olabilirsin."], ["1", "islem", "Yalnızca çoğul ekini saymışsın; -lük ve -çü de ektir."]],
          "Sözcüğü parçalarına ayır: göz-…",
          ["Sözcük parçalarına ayrılır: göz-lük-çü-ler.", "Kök “göz”, ekler “-lük”, “-çü”, “-ler”.", "Toplam 3 ek vardır."],
          K("Ek sayarken kökü sayma; kökten sonra gelen parçaları say.")),
        Q("trbey.kokek", "aciklama", 2, "Aşağıdaki sözcüklerden hangisi ek almamış, kök hâlindedir?", "deniz",
          [["denizci", "kavrama", "“-ci” eki almıştır."], ["evler", "kavrama", "“-ler” çoğul ekini almıştır."], ["yolcu", "kavrama", "“-cu” eki almıştır."]],
          "Hangi sözcükten hiçbir parça atılamaz?",
          ["Ek almamış sözcük isteniyor.", "denizci (-ci), evler (-ler), yolcu (-cu) ek almıştır.", "“deniz” hiç ek almamıştır; kök hâlindedir."],
          K("Hiç ek almamış sözcük yalın (kök) hâldedir.")),
        Q("trbey.kokek", "baglanti", 2, "“sözlük” sözcüğünün kök ve eki doğru ayrılmış olan hangisidir?", "söz + -lük",
          [["sö + -zlük", "islem", "“sö” anlamlı bir parça değildir."], ["sözl + -ük", "islem", "“sözl” anlamlı bir parça değildir."], ["sözlü + -k", "islem", "“-k” burada bir ek değildir; “sözlük”, “söz” köküne “-lük” eklenerek oluşmuştur."]],
          "Kelime seyyahının haritası olan sözlük, aslında “söz” sözcüğünden türemiştir.",
          ["Kök anlamlı olmalı: “söz” anlamlıdır.", "Kalan parça “-lük” ektir.", "Doğru ayırma: söz + -lük."],
          K("Kök her zaman anlamlıdır; anlamsız bir parça kök olamaz.")),
      ],
      "trbey.yapimcekim": [
        Q("trbey.yapimcekim", "hatirlama", 1, "Sözcüğe eklendiğinde yeni bir sözcük türeten eklere ne denir?", "Yapım eki",
          [["Çekim eki", "bilgi", "Çekim ekleri yeni sözcük türetmez; sözcüğe çoğul, hâl gibi görevler kazandırır."], ["Kök", "bilgi", "Kök ek değildir; sözcüğün anlamlı ilk parçasıdır."], ["Hece", "bilgi", "Hece, bir ek türü değildir."]],
          "göz → gözlük dönüşümünü düşün.",
          ["Yeni sözcük türeten ekin adı soruluyor.", "“-lük” eki “göz”den yeni bir sözcük türetmiştir.", "Bu tür eklere yapım eki denir."],
          K("Yapım eki: yeni sözcük türetir. Çekim eki: yeni sözcük türetmez, görev kazandırır.")),
        Q("trbey.yapimcekim", "uygulama", 2, "“balıkçı” sözcüğündeki “-çı” eki için hangisi doğrudur?", "Yapım ekidir, yeni bir sözcük türetmiştir.",
          [["Çekim ekidir, sözcüğün anlamını değiştirmez.", "kavrama", "“balık” bir hayvan, “balıkçı” bir meslek adıdır; anlam değişmiştir."], ["Çoğul ekidir.", "bilgi", "Çoğul ekleri -lar ve -ler'dir."], ["Sözcükte hiç ek yoktur.", "dikkat", "“balık” köküne “-çı” eki getirilmiştir."]],
          "“balık” ile “balıkçı” aynı şeyi mi anlatıyor?",
          ["Balık bir canlıdır; balıkçı balık tutan kişidir.", "Ek, yeni bir sözcük türetmiştir.", "Bu nedenle “-çı” yapım ekidir."],
          K("-cı/-ci/-cu/-cü (-çı/-çi/-çu/-çü) eki genellikle meslek bildiren yeni sözcükler türetir.")),
        Q("trbey.yapimcekim", "uygulama", 2, "“evlerimizden” sözcüğündeki ekler için hangisi doğrudur?", "Eklerin hepsi çekim ekidir.",
          [["Eklerin hepsi yapım ekidir.", "kavrama", "Bu ekler yeni sözcük türetmiyor; sözcük hâlâ “ev”i anlatıyor."], ["İlk ek yapım, diğerleri çekim ekidir.", "kavrama", "“-ler” çoğul ekidir; yeni sözcük türetmez."], ["Sözcükte hiç ek yoktur.", "dikkat", "ev-ler-imiz-den: kökten sonra üç ek vardır."]],
          "Ekler eklendikten sonra sözcük hâlâ “ev” mi, yoksa yeni bir sözcük mü?",
          ["Sözcük parçalanır: ev-ler-imiz-den.", "-ler (çoğul), -imiz (iyelik), -den (hâl) yeni sözcük türetmez.", "Bu nedenle hepsi çekim ekidir."],
          K("Çoğul (-lar/-ler), iyelik (-ım, -ın…) ve hâl ekleri (-e, -de, -den, -i) çekim ekidir.")),
        Q("trbey.yapimcekim", "transfer", 2, "Gazete satan ya da gazetede çalışan kişiyi anlatmak için “gazete” sözcüğüne hangi eki eklersin?", "-ci (gazeteci)",
          [["-ler (gazeteler)", "kavrama", "“-ler” çoğul ekidir; birden çok gazeteyi anlatır, kişiyi değil."], ["-de (gazetede)", "kavrama", "“-de” bulunma hâli ekidir; yer bildirir."], ["-yi (gazeteyi)", "kavrama", "“-yi” belirtme hâli ekidir; yeni sözcük türetmez."]],
          "Meslek bildiren yapım ekini hatırla: balıkçı, fırıncı…",
          ["Kişiyi, mesleği anlatan yeni bir sözcük isteniyor.", "Meslek bildiren yapım eki -ci'dir.", "gazete + -ci = gazeteci."],
          K("Yeni bir sözcük gerekiyorsa yapım eki kullanılır.")),
        Q("trbey.yapimcekim", "aciklama", 2, "Hangi sözcükte hem yapım eki hem çekim eki vardır?", "tuzluklar",
          [["tuzlar", "kavrama", "Yalnızca “-lar” çoğul eki vardır; o da çekim ekidir."], ["tuzlu", "kavrama", "Yalnızca “-lu” yapım eki vardır."], ["tuz", "dikkat", "Bu sözcük hiç ek almamıştır."]],
          "Önce yeni sözcük türeten eki, sonra görev ekini ara.",
          ["tuz-luk-lar: “-luk” yeni sözcük türetir (tuz kabı).", "“-lar” çoğul ekidir; çekim ekidir.", "Hem yapım hem çekim eki olan sözcük “tuzluklar”dır."],
          K("Sözcükte önce yapım ekleri, ardından çekim ekleri gelir: tuz-luk-lar.")),
      ],
      "trbey.cumle": [
        Q("trbey.cumle", "uygulama", 1, "“okudum / dün / kitap / ilginç / bir” sözcükleriyle kurulan kurallı cümle hangisidir?", "Dün ilginç bir kitap okudum.",
          [["Kitap dün okudum bir ilginç.", "dikkat", "Sözcüklerin sırası bozuk; “bir ilginç” Türkçede böyle sıralanmaz."], ["İlginç dün bir okudum kitap.", "dikkat", "Yüklem (okudum) sonda değil; cümle anlaşılmıyor."], ["Okudum kitap ilginç bir dün.", "dikkat", "Yüklem başa alınmış ve sıralama bozulmuş."]],
          "Yüklemi bul ve sona koy; zaman bildiren sözcükle başla.",
          ["Yüklem “okudum”dur; sona gelir.", "Ne zaman? Dün. Ne okudum? İlginç bir kitap.", "Cümle: “Dün ilginç bir kitap okudum.”"],
          K("Kurallı cümlede yüklem sondadır; diğer öğeler yüklemden önce gelir.")),
        Q("trbey.cumle", "hatirlama", 1, "Türkçede kurallı cümlelerde yüklem genellikle nerede bulunur?", "Cümlenin sonunda",
          [["Cümlenin başında", "bilgi", "Yüklemin başta olduğu cümleler devrik cümledir; kurallı cümlede yüklem sondadır."], ["Cümlenin ortasında", "bilgi", "Kurallı cümlede yüklem ortada değil, sondadır."], ["Cümlede yüklem bulunmaz", "bilgi", "Her cümlenin bir yüklemi vardır; cümlenin temelidir."]],
          "“Ali okula gitti.” cümlesinde iş bildiren sözcük nerede?",
          ["Soru yüklemin yerini soruyor.", "“gitti” iş bildirir ve cümlenin sonundadır.", "Kurallı cümlede yüklem sondadır."],
          K("Kurallı cümle: yüklem sonda. Devrik cümle: yüklem sonda değil.")),
        Q("trbey.cumle", "transfer", 2, "“dil” ve “zenginlik” sözcüklerini kullanarak anlamlı bir cümle kurman isteniyor. Hangisi en uygundur?", "Dilimiz, atalarımızdan kalan en büyük zenginliktir.",
          [["Dil zenginlik çok güzel yapmak.", "dikkat", "Sözcükler yan yana dizilmiş ama anlamlı bir yargı oluşmamış."], ["Zenginlik dilin ve.", "dikkat", "Cümle yarım kalmış."], ["Dilimiz zenginliği koşuyor.", "kavrama", "Dilin koşması anlamsızdır; sözcükler uyumsuz."]],
          "Anlamlı ve tamamlanmış bir yargı arıyorsun.",
          ["İki sözcük de kullanılmalı ve cümle anlamlı olmalı.", "Seçeneklerden yalnızca biri tam bir düşünce bildiriyor.", "“Dilimiz, atalarımızdan kalan en büyük zenginliktir.” doğru ve anlamlıdır."],
          K("Cümle kurarken: anlam tam olmalı, yüklem sonda olmalı, sözcükler birbiriyle uyumlu olmalı.")),
        Q("trbey.cumle", "baglanti", 2, "“Seyyah, gezdiği şehirleri defterine yazdı.” cümlesinde yapılan işi bildiren sözcük (yüklem) hangisidir?", "yazdı",
          [["Seyyah", "kavrama", "Seyyah işi yapan kişidir; işi bildiren sözcük değildir."], ["defterine", "kavrama", "“defterine” işin nereye yapıldığını bildirir."], ["şehirleri", "kavrama", "“şehirleri” neyin yazıldığını bildirir."]],
          "Cümlede ne yapılmış? Kurallı cümlede bu sözcük sondadır.",
          ["Yapılan iş soruluyor.", "Seyyahın yaptığı iş “yazmak”tır.", "Cümlenin sonundaki “yazdı” yüklemdir."],
          K("Yüklem, cümlede iş, oluş ya da durum bildiren temel öğedir.")),
        Q("trbey.cumle", "aciklama", 2, "Aşağıdakilerden hangisi devrik cümledir?", "Gel bizimle parka.",
          [["Bizimle parka gel.", "kavrama", "Yüklem (gel) sondadır; kurallı cümledir."], ["Annem bize kek yaptı.", "kavrama", "Yüklem (yaptı) sondadır; kurallı cümledir."], ["Kardeşim okula erken gitti.", "kavrama", "Yüklem (gitti) sondadır; kurallı cümledir."]],
          "Yüklemi bul: sonda değilse cümle devriktir.",
          ["Her cümlede yüklemin yerine bakılır.", "“Gel bizimle parka.” cümlesinde yüklem (gel) başta.", "Yüklemi sonda olmayan cümle devrik cümledir."],
          K("Devrik cümleler şiirde ve konuşmada sık kullanılır; yüklem sonda değildir.")),
      ],
    },
    oyun: [
      { tur: "sirala", kaz: "trbey.cumle", soru: "Sözcükleri sıraya dizerek kurallı bir cümle kur.", ogeler: ["Türkçe", "zengin", "ve", "güzel", "bir dildir"], aciklama: "“Türkçe zengin ve güzel bir dildir.” Yüklem (bir dildir) sondadır." },
      { tur: "sirala", kaz: "trbey.kokek", soru: "Kökten başlayarak sözcüğün ek ala ala büyümesini sırala.", ogeler: ["göz", "gözlük", "gözlükçü", "gözlükçüler"], aciklama: "Kök “göz”e önce “-lük”, sonra “-çü” yapım ekleri, en sonda “-ler” çekim eki gelir." },
      { tur: "eslestir", kaz: "trbey.yapimcekim", soru: "Sözcükleri aldıkları ekin göreviyle eşleştir.", ciftler: [["balıkçı", "meslek bildiren yapım eki"], ["kitaplar", "çoğul bildiren çekim eki"], ["evde", "yer bildiren çekim eki"], ["tuzlu", "içinde bulunma bildiren yapım eki"]], aciklama: "-çı ve -lu yeni sözcük türettiği için yapım eki; -lar ve -de yeni sözcük türetmediği için çekim ekidir." },
      { tur: "uret", kaz: "trbey.kokek", soru: "KİTAPLAR harfleriyle en az 3 anlamlı kelime üret.", harfler: "KİTAPLAR", kelimeler: ["kitaplar", "kitap", "kartal", "parlak", "pratik", "kaplar", "katlar", "atlar", "tarla", "tarak", "parti", "katil", "kira", "lira", "para", "pala", "tapa", "kart", "park", "kalp", "plak", "kara", "kar", "kat", "kap", "kil", "kir", "ilk", "tak", "pak", "ara", "ata", "ak", "al", "at", "ar", "kal", "tip", "pil", "ip", "it"], hedef: 3, aciklama: "Örnekler: kitap, kartal, parlak, tarla, tarak, park, kalp, para. “kitap” köküne “-lar” eki getirince “kitaplar” olur." },
    ],
  });

  /* =========================== 3. Türküz, Türkçe Konuşuruz =========================== */
  KONU_EKLE("tr", {
    id: "tr_turkce", tema: "tr1", ad: "Türküz, Türkçe Konuşuruz", sayfa: "s. 42", gorev: "Türkçeyi doğru ve güzel kullanma",
    kazanimlar: [
      { id: "trtur.karsilik", ad: "Yabancı sözcüklere Türkçe karşılıklar bulma ve kullanma" },
      { id: "trtur.yazim", ad: "Yazım ve noktalama kurallarını doğru uygulama" },
      { id: "trtur.koruma", ad: "Metnin ana fikrini belirleme ve dilimizi koruma bilinci geliştirme" },
    ],
    anlatim: [
      { baslik: "Yabancı sözcük yerine Türkçesi",
        metin: "Günlük hayatta, tabelalarda ve internette pek çok yabancı sözcükle karşılaşırız. Türkçede karşılığı bulunan bir sözcüğü yabancı dilde söylemek dilimizi yoksullaştırır.<br>Türk Dil Kurumu, yeni ortaya çıkan kavramlar için <b>Türkçe karşılıklar</b> önerir. Bunları kullandıkça dilimiz canlı ve zengin kalır.",
        ornek: "e-mail → e-posta · online → çevrim içi · selfie → özçekim · printer → yazıcı · mouse → fare · feedback → geri bildirim",
        gorsel: G.tablo(["Yabancı sözcük", "Türkçe karşılığı"], [["e-mail", "e-posta"], ["online", "çevrim içi"], ["offline", "çevrim dışı"], ["selfie", "özçekim"], ["printer", "yazıcı"]]),
        durak: { soru: "“Bu akşam arkadaşlarımla online oyun oynayacağım.” cümlesinde “online” yerine hangisi kullanılmalıdır?", secenekler: [["çevrim içi", true, "“Online”ın Türkçe karşılığı “çevrim içi”dir."], ["çevrim dışı", false, "Bu, “offline”ın karşılığıdır; anlamı tam tersidir."], ["özçekim", false, "Bu, “selfie”nin karşılığıdır."], ["e-posta", false, "Bu, “e-mail”in karşılığıdır."]] } },
      { baslik: "Doğru yazmak: kesme, de/da, ki, mi",
        metin: "<b>Kesme işareti (')</b> özel adlara gelen ekleri ayırır: Ankara'ya, Atatürk'ün. Dil adlarına (Türkçe, İngilizce) gelen ekler ayrılmaz: Türkçeyi, İngilizcede.<br><b>Bağlaç olan de/da</b> ayrı yazılır: Ben de geleceğim. Bulunma eki olan -de/-da bitişik yazılır: Kitap masada.<br><b>Bağlaç olan ki</b> ayrı yazılır: Duydum ki… Sıfat yapan -ki bitişik yazılır: evdeki, masadaki.<br><b>Soru eki mi</b> her zaman ayrı yazılır: Geliyor musun?",
        ornek: "İpucu: “de” yi cümleden çıkar. Anlam bozulmuyorsa bağlaçtır ve ayrı yazılır. “Ben de geleceğim.” → “Ben geleceğim.” (anlam bozulmadı)",
        durak: { soru: "Hangi cümlede yazım yanlışı yoktur?", secenekler: [["Sen de bizimle sinemaya gelir misin?", true, "Bağlaç “de” ve soru eki “mi” ayrı yazılmış; doğrudur."], ["Sende bizimle sinemaya gelirmisin?", false, "Bağlaç olan “de” ve soru eki “mi” ayrı yazılmalıydı."], ["Türkçe'yi çok seviyorum.", false, "Dil adlarına gelen ekler kesmeyle ayrılmaz: Türkçeyi."], ["Masada ki kitabı uzatır mısın?", false, "Sıfat yapan “-ki” bitişik yazılır: masadaki."]] } },
      { baslik: "Dilimizi korumak",
        metin: "Dil, bir milletin ortak hafızasıdır. Atalarımızın duyguları, düşünceleri ve deneyimleri sözcüklerle bize ulaşır.<br>Atatürk, Türkçenin gelişmesine büyük önem vermiştir: <b>1928</b>'de Harf Devrimi ile Latin harflerine dayanan yeni Türk alfabesi kabul edilmiş, <b>1932</b>'de Türk Dil Kurumu kurulmuştur.<br>Biz de dilimizi korumak için Türkçe karşılıkları kullanır, yazım kurallarına uyar, bol bol okuruz.",
        ornek: "Mesaj yazarken “slm, nbr” yerine “Selam, ne haber?” yazmak dilimize gösterdiğimiz özenin bir örneğidir.",
        durak: { soru: "Türk Dil Kurumu hangi yıl kurulmuştur?", secenekler: [["1932", true, "Türk Dil Kurumu, Atatürk'ün önderliğinde 1932'de kurulmuştur."], ["1923", false, "1923, Cumhuriyetin ilan edildiği yıldır."], ["1928", false, "1928, Harf Devrimi'nin yapıldığı yıldır."], ["1920", false, "1920, Türkiye Büyük Millet Meclisinin açıldığı yıldır."]] } },
    ],
    uret: {
      "trtur.karsilik": [
        Q("trtur.karsilik", "uygulama", 1, "“selfie” sözcüğünün Türkçe karşılığı hangisidir?", "özçekim",
          [["fotoğrafçı", "kavrama", "Fotoğrafçı, fotoğraf çeken kişidir; kişinin kendi fotoğrafını çekmesi değildir."], ["öz geçmiş", "dikkat", "Öz geçmiş, bir kişinin hayat hikâyesini anlatan yazıdır."], ["çevrim içi", "bilgi", "Çevrim içi, “online” sözcüğünün karşılığıdır."]],
          "Kişinin kendi kendini çekmesi: öz + çekim…",
          ["“Selfie”, kişinin kendi fotoğrafını çekmesidir.", "“Öz” kendi, “çekim” fotoğraf çekme anlamındadır.", "Türkçe karşılığı “özçekim”dir."],
          K("Yabancı sözcüklerin Türkçe karşılıklarını kullanmak dilimizi zenginleştirir.")),
        Q("trtur.karsilik", "uygulama", 1, "“e-mail” sözcüğünün Türkçe karşılığı hangisidir?", "e-posta",
          [["e-devlet", "dikkat", "E-devlet, devlet hizmetlerinin internetten verilmesidir."], ["telefon", "bilgi", "Telefon bir iletişim aracıdır; elektronik mektup değildir."], ["yazıcı", "bilgi", "Yazıcı, “printer”ın karşılığıdır."]],
          "Elektronik ortamda gönderilen mektuba ne deriz?",
          ["“Mail” mektup, posta anlamına gelir.", "Elektronik postaya kısaca e-posta deriz.", "Doğru karşılık “e-posta”dır."],
          K("e-mail → e-posta, online → çevrim içi, printer → yazıcı.")),
        Q("trtur.karsilik", "aciklama", 2, "Aşağıdaki cümlelerin hangisinde Türkçe karşılığı varken gereksiz yere yabancı sözcük kullanılmıştır?", "Dün akşamki party çok eğlenceliydi.",
          [["Kardeşime e-posta gönderdim.", "dikkat", "“E-posta” Türkçe karşılıktır; yanlış yok."], ["Yazıcıdan ödevimin çıktısını aldım.", "dikkat", "“Yazıcı” Türkçe karşılıktır; yanlış yok."], ["Yarın okulda bir gösteri var.", "dikkat", "“Gösteri” Türkçe bir sözcüktür; yanlış yok."]],
          "Hangi sözcüğün yerine “eğlence” ya da “şenlik” denebilir?",
          ["Seçeneklerde yabancı sözcük aranıyor.", "“party” İngilizce bir sözcüktür; Türkçesi “eğlence, şenlik”tir.", "Gereksiz yabancı sözcük ilk cümlededir."],
          K("Türkçesi varken yabancı sözcük kullanmak gereksizdir.")),
        Q("trtur.karsilik", "transfer", 2, "Mahallendeki bir dükkânın camında “Super Sale” yazıyor. Dükkân sahibine hangi Türkçe ifadeyi önerirsin?", "Büyük İndirim",
          [["Süper Sale", "dikkat", "“Sale” hâlâ yabancı bir sözcük; tam bir Türkçe karşılık değil."], ["Big Sale", "dikkat", "Bu da İngilizcedir; Türkçe karşılık değildir."], ["Mega Fırsat", "dikkat", "“Mega” yabancı bir sözcüktür; Türkçesi kullanılmalı."]],
          "“Sale” indirim, “super” büyük, harika anlamındadır.",
          ["Tabeladaki yazı İngilizcedir.", "“Super” büyük, “sale” indirim demektir.", "Türkçe karşılık “Büyük İndirim” olur."],
          K("Tabelalarda, menülerde ve reklamlarda da Türkçe sözcükler kullanılmalıdır.")),
        Q("trtur.karsilik", "uygulama", 1, "Bilgisayar ekranında imleci hareket ettirdiğimiz “mouse”un Türkçe karşılığı hangisidir?", "fare",
          [["klavye", "bilgi", "Klavye, harfleri yazdığımız tuşlu araçtır."], ["ekran", "bilgi", "Ekran, görüntünün çıktığı bölümdür."], ["hoparlör", "bilgi", "Hoparlör, ses çıkaran araçtır."]],
          "Şekli küçük bir hayvana benzediği için bu adı almıştır.",
          ["“Mouse” İngilizcede küçük bir hayvanın adıdır.", "Türkçede bu hayvana “fare” deriz.", "Bilgisayar aracının Türkçe adı da “fare”dir."],
          K("Bilişim sözcüklerinin de Türkçe karşılıkları vardır: fare, yazıcı, e-posta, çevrim içi.")),
      ],
      "trtur.yazim": [
        Q("trtur.yazim", "hatirlama", 1, "Özel adlara getirilen çekim ekleri nasıl yazılır?", "Kesme işaretiyle ayrılır.",
          [["Virgülle ayrılır.", "bilgi", "Virgül, sözcük ile ekini ayırmak için kullanılmaz."], ["Kesme işareti olmadan bitişik yazılır.", "bilgi", "Özel adlara gelen ekler kesmeyle ayrılır: Ankara'ya."], ["Ek, sözcükten bir boşlukla ayrı yazılır.", "bilgi", "Ekler sözcükten boşlukla ayrılmaz."]],
          "“Ankara…ya” sözcüğünü nasıl yazarız?",
          ["Özel adlara gelen ekler soruluyor.", "Ankara'ya, Atatürk'ün, Türkiye'nin örneklerinde ek kesmeyle ayrılmıştır.", "Doğru cevap: kesme işaretiyle ayrılır."],
          K("Özel ad + çekim eki: Ankara'ya, İzmir'de, Mehmet Âkif'in.")),
        Q("trtur.yazim", "uygulama", 2, "Hangi cümlede kesme işareti doğru kullanılmıştır?", "Yaz tatilinde Ankara'ya gideceğiz.",
          [["Türkçe'yi çok seviyorum.", "bilgi", "Dil adlarına gelen ekler kesmeyle ayrılmaz: Türkçeyi."], ["Okul'a erken gittim.", "kavrama", "“okul” özel ad değildir; ek kesmeyle ayrılmaz: okula."], ["İzmirde ilk kez denizi gördüm.", "dikkat", "“İzmir” özel addır; ek kesmeyle ayrılmalıydı: İzmir'de."]],
          "Önce sözcüğün özel ad olup olmadığına bak.",
          ["Kesme işareti yalnızca özel adlara gelen ekleri ayırır.", "“Ankara” bir şehir adıdır; ek kesmeyle ayrılmıştır.", "Doğru kullanım ilk cümlededir."],
          K("Cins adlara (okul, ev) ve dil adlarına (Türkçe) gelen ekler kesmeyle ayrılmaz.")),
        Q("trtur.yazim", "uygulama", 2, "Hangi cümlede “de” bağlacı doğru yazılmıştır?", "Ben de sizinle geleceğim.",
          [["Bende sizinle geleceğim.", "kavrama", "Bağlaç olan “de” ayrı yazılmalıydı: Ben de."], ["Kitap masa da duruyor.", "kavrama", "Burada “-da” yer bildiren ektir; bitişik yazılır: masada."], ["Sende mi bu filmi izledin?", "kavrama", "“de” burada bağlaçtır; ayrı yazılmalıydı: Sen de."]],
          "“de”yi çıkardığında anlam bozulmuyorsa bağlaçtır ve ayrı yazılır.",
          ["Bağlaç olan “de”yi bulmak için onu cümleden çıkarırız.", "“Ben geleceğim.” anlamlıdır; demek ki “de” bağlaçtır ve ayrı yazılır.", "Doğru yazım: “Ben de sizinle geleceğim.”"],
          K("Bağlaç “de/da” ayrı, bulunma eki “-de/-da” bitişik yazılır.")),
        Q("trtur.yazim", "uygulama", 2, "Hangi cümlede soru eki doğru yazılmıştır?", "Yarın okula gelecek misin?",
          [["Yarın okula gelecekmisin?", "kavrama", "Soru eki “mi” her zaman ayrı yazılır."], ["Ödevini yaptınmı?", "kavrama", "Soru eki ayrı yazılmalıydı: yaptın mı?"], ["Bu kitabı okudumu?", "kavrama", "Soru eki ayrı yazılmalıydı: okudu mu?"]],
          "Soru eki “mi” bitişik mi, ayrı mı yazılır?",
          ["Soru eki “mi, mı, mu, mü” her zaman ayrı yazılır.", "Kendisinden sonra gelen ekler ise ona bitişir: misin, musun.", "Doğru yazım: “gelecek misin?”"],
          K("Soru eki ayrı yazılır: Geliyor musun? Güzel mi? Okudun mu?")),
        Q("trtur.yazim", "uygulama", 2, "Hangi cümlede “ki” doğru yazılmıştır?", "Duydum ki yarın kar yağacakmış.",
          [["Duydumki yarın kar yağacakmış.", "kavrama", "Bağlaç olan “ki” ayrı yazılmalıydı."], ["Evde ki kedi uyuyor.", "kavrama", "Burada “-ki” sıfat yapar; bitişik yazılır: evdeki."], ["Masada ki kitabı ver.", "kavrama", "Burada “-ki” sıfat yapar; bitişik yazılır: masadaki."]],
          "“ki” iki cümleyi bağlıyorsa ayrı, “evdeki” gibi bir ad niteliyorsa bitişik yazılır.",
          ["“Duydum ki” sözünde “ki” iki cümleyi bağlıyor; bağlaçtır.", "Bağlaç olan “ki” ayrı yazılır.", "“evdeki, masadaki” ise bitişik yazılmalıdır."],
          K("Bağlaç “ki” ayrı yazılır (Duydum ki…). Sıfat yapan “-ki” bitişik yazılır (evdeki, yarınki).")),
        Q("trtur.yazim", "uygulama", 1, "Hangi cümlenin sonuna soru işareti (?) konmalıdır?", "Hafta sonu nereye gideceksiniz",
          [["Hafta sonu sinemaya gideceğiz", "kavrama", "Bu cümle bir bilgi veriyor; sonuna nokta konur."], ["Ne güzel bir gün", "kavrama", "Bu cümle sevinç bildiriyor; sonuna ünlem konur."], ["Lütfen kapıyı kapat", "kavrama", "Bu cümle bir rica bildiriyor; sonuna nokta konur."]],
          "Hangi cümle bir cevap bekliyor?",
          ["Soru işareti, soru bildiren cümlelerin sonuna konur.", "“nereye” sözcüğü bir soru sorar ve cevap bekler.", "Soru işareti “Hafta sonu nereye gideceksiniz?” cümlesine konur."],
          K("Nokta: bilgi bildiren cümle. Soru işareti: soru cümlesi. Ünlem: sevinç, şaşkınlık, korku.")),
      ],
      "trtur.koruma": [
        Q("trtur.koruma", "aciklama", 2, "<i>Dil, bir milletin ortak hafızasıdır. Atalarımızın duyguları, düşünceleri ve deneyimleri sözcüklerle bize ulaşır. Dilimizi özenle kullandığımızda bu mirası geleceğe taşırız. Gereksiz yabancı sözcükler ise dilimizi yoksullaştırır.</i><br><br>Bu metnin ana fikri nedir?", "Dilimizi özenle kullanarak korumalıyız.",
          [["Yabancı dil öğrenmek gereksizdir.", "kavrama", "Metin yabancı dil öğrenmeye karşı çıkmıyor; gereksiz yabancı sözcük kullanımını eleştiriyor."], ["Atalarımız çok sözcük bilirdi.", "dikkat", "Metinde böyle bir bilgi yok; atalarımızın deneyimlerinin dille bize ulaştığı söyleniyor."], ["Sözcükler yalnızca hafızamızda saklanır.", "kavrama", "“Ortak hafıza” bir benzetmedir; metnin asıl mesajı dilin korunmasıdır."]],
          "Yazar okura sonunda ne yapmasını öneriyor?",
          ["Ana fikir, yazarın okura vermek istediği asıl mesajdır.", "Metin dilin değerini anlatıp onu özenle kullanmamız gerektiğini vurguluyor.", "Ana fikir: Dilimizi özenle kullanarak korumalıyız."],
          K("Ana fikri bulmak için sor: Yazar bu metinle bize asıl ne söylemek istiyor?")),
        Q("trtur.koruma", "transfer", 1, "Aşağıdaki davranışlardan hangisi dilimizi koruma bilincine uygundur?", "Mesajlarımda Türkçe karşılığı olan sözcükleri kullanırım.",
          [["Konuşurken araya yabancı sözcük katmak daha havalı olur.", "kavrama", "Gereksiz yabancı sözcükler dilimizi yoksullaştırır."], ["Nasılsa anlaşılıyor diye yazım kurallarına dikkat etmem.", "kavrama", "Yazım kurallarına uymak dile gösterilen özenin parçasıdır."], ["Her zaman “slm, nbr” gibi kısaltmalarla yazarım.", "kavrama", "Gelişigüzel kısaltmalar dilin doğru kullanımını bozar."]],
          "Hangi davranış Türkçeye özen göstermektir?",
          ["Dilimizi korumak, onu doğru ve özenle kullanmaktır.", "Türkçe karşılıkları kullanmak bu özenin bir göstergesidir.", "Doğru davranış ilk seçenektir."],
          K("Dilimizi korumak için: Türkçe karşılık kullan, yazım kurallarına uy, bol oku.")),
        Q("trtur.koruma", "hatirlama", 1, "Türk Dil Kurumu hangi yıl kurulmuştur?", "1932",
          [["1923", "bilgi", "1923, Cumhuriyetin ilan edildiği yıldır."], ["1928", "bilgi", "1928, Harf Devrimi'nin yapıldığı yıldır."], ["1920", "bilgi", "1920, Türkiye Büyük Millet Meclisinin açıldığı yıldır."]],
          "Harf Devrimi'nden dört yıl sonra kurulmuştur.",
          ["Harf Devrimi 1928'de yapılmıştır.", "Türk Dil Kurumu bundan dört yıl sonra, Atatürk'ün önderliğinde kurulmuştur.", "Kuruluş yılı 1932'dir."],
          K("1928 Harf Devrimi · 1932 Türk Dil Kurumunun kuruluşu.")),
        Q("trtur.koruma", "baglanti", 2, "Atatürk'ün 1928'de gerçekleştirdiği ve Türkçenin okunup yazılmasını kolaylaştıran yenilik hangisidir?", "Harf Devrimi (yeni Türk alfabesinin kabulü)",
          [["Türk Dil Kurumunun kurulması", "bilgi", "Türk Dil Kurumu 1932'de kurulmuştur."], ["Soyadı Kanunu", "bilgi", "Soyadı Kanunu 1934'te kabul edilmiştir."], ["Cumhuriyetin ilanı", "bilgi", "Cumhuriyet 1923'te ilan edilmiştir."]],
          "Bu yenilikle Latin harflerine dayanan yeni bir alfabe kabul edildi.",
          ["Soru 1928'deki dil ile ilgili yeniliği soruyor.", "1928'de Latin harflerine dayanan yeni Türk alfabesi kabul edildi.", "Bu yeniliğe Harf Devrimi denir."],
          K("Harf Devrimi (1928) ile Türkçe, sesleri iyi karşılayan yeni bir alfabeye kavuştu.")),
        Q("trtur.koruma", "aciklama", 2, "“Dil, bir milletin kimliğidir.” sözüyle anlatılmak istenen nedir?", "Dil, bir milleti birleştiren ve onu diğerlerinden ayıran en önemli özelliklerdendir.",
          [["Her insanın bir kimlik kartı olmalıdır.", "kavrama", "Söz, kimlik kartından değil, dilin bir milleti tanıtmasından söz ediyor."], ["Bir millet yalnızca tek bir sözcük kullanır.", "kavrama", "Sözün böyle bir anlamı yoktur."], ["Dil öğrenmek çok zordur.", "dikkat", "Söz, dil öğrenmenin zorluğuyla ilgili değildir."]],
          "Kimlik, bir kişiyi başkalarından ayıran bilgilerdir. Dil bir millet için ne işe yarar?",
          ["Kimlik, kişiyi tanıtan ve diğerlerinden ayıran özelliklerdir.", "Dil de bir milletin insanlarını birbirine bağlar ve onu tanıtır.", "Söz, dilin millet için ne kadar önemli olduğunu anlatır."],
          K("Benzetmeli sözlerde “neye benzetilmiş, hangi yönüyle?” diye sorarak anlamı bul.")),
      ],
    },
    oyun: [
      { tur: "eslestir", kaz: "trtur.karsilik", soru: "Yabancı sözcükleri Türkçe karşılıklarıyla eşleştir.", ciftler: [["selfie", "özçekim"], ["online", "çevrim içi"], ["e-mail", "e-posta"], ["printer", "yazıcı"]], aciklama: "Türk Dil Kurumunun önerdiği karşılıklar: özçekim, çevrim içi, e-posta, yazıcı." },
      { tur: "eslestir", kaz: "trtur.yazim", soru: "Yanlış yazılanları doğru yazılışlarıyla eşleştir.", ciftler: [["Türkçe'yi", "Türkçeyi"], ["gelecekmisin", "gelecek misin"], ["evde ki", "evdeki"], ["Bende geleceğim", "Ben de geleceğim"]], aciklama: "Dil adlarına gelen ek kesmeyle ayrılmaz; soru eki ayrı, sıfat yapan -ki bitişik, bağlaç de ayrı yazılır." },
      { tur: "sirala", kaz: "trtur.koruma", soru: "Olayları tarih sırasına göre diz.", ogeler: ["Cumhuriyetin ilanı (1923)", "Harf Devrimi (1928)", "Türk Dil Kurumunun kuruluşu (1932)", "Soyadı Kanunu (1934)"], aciklama: "1923 Cumhuriyet, 1928 Harf Devrimi, 1932 Türk Dil Kurumu, 1934 Soyadı Kanunu." },
      { tur: "uret", kaz: "trtur.koruma", soru: "DİLİMİZ harfleriyle en az 3 anlamlı kelime üret.", harfler: "DİLİMİZ", kelimeler: ["dilimiz", "dilim", "dizi", "ilim", "dil", "diz", "zil", "mil", "iz", "il", "dizim", "dizili"], hedef: 3, aciklama: "Örnekler: dil, dilim, diz, dizi, zil, mil, ilim. Hepsinde dilimizin güzel sesleri var!" },
    ],
  });

  /* =========================== 4. Türk Dil Kurumu Sunar (Kaşık) =========================== */
  KONU_EKLE("tr", {
    id: "tr_kasik", tema: "tr1", ad: "Türk Dil Kurumu Sunar (Kaşık)", sayfa: "s. 50", gorev: "Dinleme/izleme sonrası anlama",
    kazanimlar: [
      { id: "trkas.dinleme", ad: "Dinleme/izleme stratejilerini uygulama (tahmin etme, not alma, ana fikri bulma)" },
      { id: "trkas.deyim", ad: "Deyim ve atasözlerinin anlamını kavrama ve yerinde kullanma" },
      { id: "trkas.sozvarligi", ad: "Mutfak ve kaşıkla ilgili söz varlığını tanıma, sözcükleri doğru kullanma" },
    ],
    anlatim: [
      { baslik: "İyi bir dinleyici nasıl dinler?",
        metin: "Bir video izlerken ya da bir konuşmayı dinlerken şu adımları uygula:<br><b>Dinlemeden önce:</b> Başlığa ve görsellere bakarak konuyu <b>tahmin et</b>.<br><b>Dinlerken:</b> Dikkatini ver, konuşmacının sözünü kesme, önemli bilgileri <b>kısa notlar</b> hâlinde yaz (her sözcüğü değil, anahtar sözcükleri).<br><b>Dinledikten sonra:</b> Notlarından yararlanarak <b>ana fikri</b> bul ve dinlediklerini kendi cümlelerinle özetle.",
        ornek: "“Kaşık” başlıklı bir video izleyeceksin. Önce kendine sor: “Kaşığın tarihi mi, yapımı mı, kaşıklı deyimler mi anlatılacak?”",
        durak: { soru: "Dinlerken not almanın en doğru yolu hangisidir?", secenekler: [["Anahtar sözcükleri ve önemli bilgileri kısaca yazmak", true, "Kısa notlar hem dinlemeyi sürdürmeni hem de önemli bilgileri hatırlamanı sağlar."], ["Konuşmacının her sözcüğünü eksiksiz yazmak", false, "Her sözcüğü yazmaya çalışırken dinlemeyi kaçırırsın."], ["Hiç not almadan yalnızca görüntülere bakmak", false, "Not almazsan önemli bilgileri unutabilirsin."], ["Dinleme bittikten sonra ne hatırlarsan yazmak", false, "Önemli bilgileri dinlerken not almak daha güvenlidir."]] } },
      { baslik: "Deyim ve atasözü",
        metin: "<b>Deyim:</b> Bir durumu, kavramı çekici biçimde anlatan, genellikle mecaz anlamlı kalıplaşmış sözlerdir. Çoğu bir eylemle biter: kulak vermek, ağzı kulaklarına varmak.<br><b>Atasözü:</b> Atalarımızın uzun deneyimlerine dayanan, öğüt veren ya da genel bir yargı bildiren kalıplaşmış sözlerdir: Damlaya damlaya göl olur.<br>Kaşık da deyimlerimize girmiştir: <b>bir kaşık suda boğmak</b>, birine çok kızıp ona kötülük etmeye hazır olmak demektir.",
        ornek: "“Öğretmenimizin anlattıklarına kulak verdik.” (deyim: dikkatle dinlemek) · “Damlaya damlaya göl olur.” (atasözü: küçük birikimler zamanla büyür)",
        durak: { soru: "Aşağıdakilerden hangisi atasözüdür?", secenekler: [["Damlaya damlaya göl olur.", true, "Genel bir yargı bildirir ve öğüt verir; atasözüdür."], ["Kulak vermek", false, "Bir durumu anlatan kalıp sözdür; deyimdir."], ["Ağzı kulaklarına varmak", false, "Çok sevinmeyi anlatan bir deyimdir."], ["Bir kaşık suda boğmak", false, "Çok kızmayı anlatan bir deyimdir."]] } },
      { baslik: "Mutfaktan sözcükler: kaşık ailesi",
        metin: "Kaşık, sofraların vazgeçilmez aracıdır. Anadolu'da tahtadan oyulan kaşıklar ustaların emeğini ve sanatını taşır; bazı yörelerde kaşıklar halk oyunlarında ritim tutmak için de kullanılır.<br>“Kaşık” sözcüğünden yeni sözcükler türetilir: <b>kaşıkçı</b> (kaşık yapan ya da satan kişi), <b>kaşıklık</b> (kaşıkların konduğu yer).<br>Mutfağın diğer araçları: <b>kepçe</b> (çorba gibi sıvıları aktarmaya yarayan büyük kaşık), <b>kevgir</b> (delikli kepçe), <b>tencere</b>, <b>tava</b>.",
        ornek: "Annem çorbayı kepçeyle kâselere koydu; ben de kaşıkları kaşıklıktan alıp sofraya dizdim.",
        durak: { soru: "Kaşık yapan ya da satan kişiye ne denir?", secenekler: [["kaşıkçı", true, "“-çı” eki meslek bildirir: kaşıkçı."], ["kaşıklık", false, "Kaşıklık, kaşıkların konduğu yerdir."], ["kaşıklı", false, "Kaşıklı, içinde kaşık olan demektir."], ["kaşıksız", false, "Kaşıksız, kaşığı olmayan demektir."]] } },
    ],
    uret: {
      "trkas.dinleme": [
        Q("trkas.dinleme", "hatirlama", 1, "Dinlemeye başlamadan önce başlığa ve görsellere bakarak konuyu kestirmeye ne denir?", "Tahmin etme",
          [["Not alma", "bilgi", "Not alma dinlerken yapılır; konuyu önceden kestirmek değildir."], ["Özetleme", "bilgi", "Özetleme dinledikten sonra yapılır."], ["Sesli okuma", "bilgi", "Sesli okuma bir okuma yöntemidir; dinlemeye hazırlık değildir."]],
          "Dinlemeden önce yapılan zihinsel hazırlığı düşün.",
          ["Soru, dinlemeden önceki adımı soruyor.", "Başlık ve görseller konu hakkında ipucu verir.", "Bu ipuçlarıyla konuyu kestirmeye tahmin etme denir."],
          K("Dinleme adımları: Önce tahmin et → Dinlerken not al → Sonra ana fikri bul ve özetle.")),
        Q("trkas.dinleme", "transfer", 1, "Bir belgesel izlerken önemli bilgileri unutmamak için ne yapmalısın?", "Anahtar sözcükleri kısa notlar hâlinde yazmalıyım.",
          [["Konuşmacının her sözcüğünü eksiksiz yazmalıyım.", "strateji", "Her şeyi yazmaya çalışırken dinlemeyi kaçırırsın."], ["Yalnızca görüntülere bakmalıyım.", "strateji", "Görüntüler yardımcıdır ama önemli bilgiler genellikle anlatımdadır."], ["Videoyu en hızlı şekilde izlemeliyim.", "strateji", "Hızlı izlemek anlamayı zorlaştırır."]],
          "Hem dinlemeyi sürdürüp hem bilgileri saklamanın yolu nedir?",
          ["Dinlerken bilgileri kaybetmemek gerekiyor.", "Her şeyi yazmak dinlemeyi engeller; hiç yazmamak unutmaya yol açar.", "En doğrusu anahtar sözcükleri kısaca not etmektir."],
          K("İyi not: kısa, anahtar sözcüklerle, maddeler hâlinde.")),
        Q("trkas.dinleme", "aciklama", 2, "Dinlediğin bir metnin ana fikrini bulmak için kendine hangi soruyu sormalısın?", "Konuşmacı bize asıl ne söylemek istiyor?",
          [["Konuşmacı kaç yaşında?", "strateji", "Konuşmacının yaşı ana fikirle ilgili değildir."], ["Video kaç dakika sürdü?", "strateji", "Sürenin ana fikirle ilgisi yoktur."], ["Metinde kaç kişinin adı geçti?", "strateji", "Kişi sayısı bir ayrıntıdır; ana fikri vermez."]],
          "Ana fikir, metnin vermek istediği asıl mesajdır.",
          ["Ana fikir, metnin okura ya da dinleyiciye vermek istediği temel mesajdır.", "Ayrıntılar (yaş, süre, sayı) ana fikri vermez.", "Doğru soru: “Konuşmacı bize asıl ne söylemek istiyor?”"],
          K("Konu: Metin neyden söz ediyor? Ana fikir: Metin bize ne mesaj veriyor?")),
        Q("trkas.dinleme", "uygulama", 2, "<i>Kaşık, yalnızca yemek yemeye yarayan bir araç değildir. Anadolu'da tahtadan oyulan kaşıklar, ustaların emeğini ve sanatını taşır. Bazı yörelerde kaşıklar halk oyunlarında ritim tutmak için de kullanılır.</i><br><br>Bu dinleme metninin konusu nedir?", "Kaşığın farklı kullanım alanları",
          [["Çorba nasıl pişirilir?", "dikkat", "Metinde yemek tarifinden söz edilmiyor."], ["Anadolu'daki halk oyunlarının tarihi", "dikkat", "Halk oyunları yalnızca bir ayrıntı olarak geçiyor; konu kaşıktır."], ["Ağaç türleri", "dikkat", "Tahtadan söz ediliyor ama konu ağaçlar değil."]],
          "Metindeki bütün cümleler neyi anlatıyor?",
          ["Konu, metnin neyden söz ettiğidir.", "Her cümle kaşığın bir kullanımını anlatıyor: yemek, sanat, halk oyunu.", "Konu: Kaşığın farklı kullanım alanları."],
          K("Konuyu bulmak için bütün cümlelerin ortak noktasını ara.")),
        Q("trkas.dinleme", "transfer", 1, "Sınıfta bir arkadaşın sunum yapıyor. İyi bir dinleyici olarak hangisini yapmalısın?", "Sözünü kesmeden dinler, sorularımı sunum bitince sorarım.",
          [["Merak ettiğim her şeyi hemen araya girerek sorarım.", "strateji", "Sözü kesmek hem konuşmacıyı hem dinleyenleri rahatsız eder."], ["Sunum sırasında yanımdakiyle konuşurum.", "strateji", "Bu, hem senin hem başkalarının dinlemesini engeller."], ["Konu ilgimi çekmezse başka işle uğraşırım.", "strateji", "İyi dinleyici konuşmacıya saygı gösterir ve dikkatini verir."]],
          "Konuşmacıya saygı nasıl gösterilir?",
          ["İyi dinleyici dikkatini konuşmacıya verir.", "Sözü kesmez, sorularını uygun zamanda sorar.", "Doğru davranış ilk seçenektir."],
          K("İyi dinleyici: göz teması kurar, sözü kesmez, not alır, soruyu sona saklar.")),
      ],
      "trkas.deyim": [
        Q("trkas.deyim", "hatirlama", 1, "Atalarımızın uzun deneyimlerine dayanan, öğüt veren kalıplaşmış sözlere ne denir?", "Atasözü",
          [["Deyim", "bilgi", "Deyimler bir durumu anlatır; genellikle öğüt vermez."], ["Terim", "bilgi", "Terim, bir bilim ya da meslek dalına özgü sözcüktür."], ["İkileme", "bilgi", "İkileme, “yavaş yavaş” gibi sözcük tekrarlarıdır."]],
          "“Damlaya damlaya göl olur.” sözü ne tür bir sözdür?",
          ["Öğüt veren, genel yargı bildiren kalıp sözler soruluyor.", "“Damlaya damlaya göl olur.” bu tür bir sözdür.", "Bunlara atasözü denir."],
          K("Atasözü: öğüt verir, genel yargı bildirir. Deyim: bir durumu çekici biçimde anlatır.")),
        Q("trkas.deyim", "aciklama", 2, "“Bir kaşık suda boğmak” deyiminin anlamı nedir?", "Birine çok kızıp ona kötülük etmeye hazır olmak",
          [["Az suyla yemek pişirmek", "kavrama", "Deyimler çoğunlukla mecaz anlamlıdır; burada gerçek bir kaşık sudan söz edilmiyor."], ["Birini çok sevmek", "kavrama", "Deyim sevgiyi değil, büyük öfkeyi anlatır."], ["Az şeyle yetinmek", "kavrama", "Yetinmekle ilgisi yoktur; deyim öfkeyi anlatır."]],
          "Bir kaşık suda kimse boğulmaz; o hâlde bu söz neyi abartıyor?",
          ["Deyim mecaz anlamlıdır.", "Bir kaşık suda bile boğmak istemek, büyük bir öfkeyi abartarak anlatır.", "Anlamı: birine çok kızıp ona kötülük etmeye hazır olmak."],
          K("Deyimlerin anlamını sözcüklerin gerçek anlamından değil, bütün kalıbın anlattığı durumdan çıkar.")),
        Q("trkas.deyim", "uygulama", 2, "Aşağıdakilerden hangisi bir atasözüdür?", "Damlaya damlaya göl olur.",
          [["Göz atmak", "kavrama", "Bir durumu anlatan kalıp sözdür; deyimdir."], ["Kulak vermek", "kavrama", "“Dikkatle dinlemek” anlamında bir deyimdir."], ["Etekleri zil çalmak", "kavrama", "“Çok sevinmek” anlamında bir deyimdir."]],
          "Hangisi genel bir yargı bildirip öğüt veriyor?",
          ["Atasözleri genel bir yargı bildirir.", "“Damlaya damlaya göl olur.” küçük birikimlerin zamanla büyüyeceğini öğütler.", "Diğerleri bir durumu anlatan deyimlerdir."],
          K("Atasözleri çoğunlukla bir yargı bildiren tam cümledir; deyimler çoğunlukla mastarla (-mak/-mek) biter.")),
        Q("trkas.deyim", "transfer", 2, "Arkadaşın her gün 20 sayfa kitap okuyarak bir yılda pek çok kitap bitirdi. Bu duruma en uygun söz hangisidir?", "Damlaya damlaya göl olur.",
          [["Bir kaşık suda boğmak", "kavrama", "Bu deyim büyük öfkeyi anlatır; durumla ilgisi yoktur."], ["Etekleri zil çalmak", "kavrama", "Bu deyim çok sevinmeyi anlatır; birikimi anlatmaz."], ["Kulak asmamak", "kavrama", "Bu deyim önemsememek demektir."]],
          "Az az ama düzenli yapılan bir işin sonucu anlatılıyor.",
          ["Durum: küçük ama düzenli çabalar.", "Sonuç: büyük bir birikim (pek çok kitap).", "Bunu en iyi “Damlaya damlaya göl olur.” atasözü anlatır."],
          K("Atasözünü bir duruma uygularken anlamını o durumla karşılaştır.")),
        Q("trkas.deyim", "baglanti", 2, "“Öğretmenin anlattıklarına kulak ver.” cümlesindeki deyimin anlamı hangisidir? (Dinleme becerisiyle bağlantıyı düşün.)", "Dikkatle dinlemek",
          [["Duymazdan gelmek", "kavrama", "Bu, “kulak asmamak” deyiminin anlamıdır; tam tersidir."], ["Kulağını göstermek", "kavrama", "Deyim gerçek anlamda kullanılmaz; mecazdır."], ["Fısıldayarak konuşmak", "kavrama", "Deyim konuşmayı değil, dinlemeyi anlatır."]],
          "İyi bir dinleyicinin yaptığı şeyi düşün.",
          ["Deyim mecaz anlamlıdır.", "“Kulak vermek”, bir söylenene dikkatini vermektir.", "Anlamı: dikkatle dinlemek."],
          K("Kulak vermek: dikkatle dinlemek. Kulak asmamak: önemsememek, dinlememek.")),
      ],
      "trkas.sozvarligi": [
        Q("trkas.sozvarligi", "hatirlama", 1, "Kaşıkların konduğu kutu ya da askıya ne denir?", "kaşıklık",
          [["kaşıkçı", "kavrama", "Kaşıkçı, kaşık yapan ya da satan kişidir."], ["kaşıklı", "kavrama", "Kaşıklı, içinde kaşık bulunan demektir."], ["kaşıksız", "kavrama", "Kaşıksız, kaşığı olmayan demektir."]],
          "“-lık” eki bir şeyin konduğu yeri bildirebilir: kitaplık, tuzluk…",
          ["Kaşıkların konduğu yer soruluyor.", "“-lık” eki kitaplık, tuzluk gibi yer bildiren sözcükler türetir.", "Kaşıkların konduğu yere kaşıklık denir."],
          K("-lık/-lik/-luk/-lük eki bir şeyin konduğu yeri bildirebilir: kaşıklık, kitaplık, tuzluk.")),
        Q("trkas.sozvarligi", "uygulama", 1, "Aşağıdakilerden hangisi bir mutfak aracı değildir?", "cetvel",
          [["kepçe", "dikkat", "Kepçe, çorba gibi sıvıları aktarmaya yarayan mutfak aracıdır."], ["tencere", "dikkat", "Tencere, yemek pişirilen mutfak aracıdır."], ["kevgir", "dikkat", "Kevgir, delikli bir kepçedir; mutfakta kullanılır."]],
          "Hangisi okul çantasında bulunur?",
          ["Mutfak araçları: kepçe, tencere, kevgir.", "Cetvel, çizgi çizmeye ve ölçmeye yarayan bir okul aracıdır.", "Mutfak aracı olmayan “cetvel”dir."],
          K("Söz varlığını zenginleştirmek için sözcükleri gruplayarak öğren: mutfak, okul, doğa…")),
        Q("trkas.sozvarligi", "transfer", 1, "Çorbayı tencereden kâselere aktarmak için kullanılan büyük kaşığa ne denir?", "kepçe",
          [["çatal", "bilgi", "Çatalla sıvı aktarılamaz."], ["bıçak", "bilgi", "Bıçak kesmeye yarar."], ["rende", "bilgi", "Rende, sebze ve peynir gibi yiyecekleri ufalamaya yarar."]],
          "Derin ve uzun saplı bir mutfak aracıdır.",
          ["Sıvıyı bir kaptan diğerine aktaran araç soruluyor.", "Bu araç büyük, derin ve uzun saplı bir kaşıktır.", "Adı “kepçe”dir."],
          K("Kepçe: sıvıları aktarmaya yarayan büyük kaşık. Kevgir: delikli kepçe.")),
        Q("trkas.sozvarligi", "baglanti", 2, "“kaşıkçı” sözcüğündeki “-çı” eki için hangisi doğrudur?", "Yapım ekidir; meslek bildiren yeni bir sözcük türetmiştir.",
          [["Çekim ekidir; sözcüğü çoğul yapmıştır.", "bilgi", "Çoğul ekleri -lar/-ler'dir; “-çı” çoğul eki değildir."], ["Yapım ekidir; kaşığın konduğu yeri bildirir.", "kavrama", "Konulan yer “-lık” ekiyle yapılır: kaşıklık."], ["Sözcükte hiç ek yoktur.", "dikkat", "“kaşık” köküne “-çı” eki gelmiştir."]],
          "Türkçenin Beyliği konusunda öğrendiğin ek türlerini hatırla.",
          ["“kaşık” bir araç, “kaşıkçı” bir meslek adıdır.", "Ek yeni bir sözcük türetmiştir; yapım ekidir.", "“-çı” eki meslek bildirir."],
          K("-cı/-çı eki meslek, -lık eki yer, -lı eki sahiplik bildiren sözcükler türetebilir.")),
        Q("trkas.sozvarligi", "aciklama", 2, "“Kaşık” sözcüğü hangi cümlede mecaz anlamlı bir söz içinde kullanılmıştır?", "Kardeşine öyle kızdı ki onu bir kaşık suda boğacaktı.",
          [["Çorbamı tahta kaşıkla içtim.", "kavrama", "Burada gerçek bir kaşıktan söz ediliyor."], ["Sofraya altı kaşık koyduk.", "kavrama", "Burada kaşık gerçek anlamıyla kullanılmış."], ["Kaşıkları kaşıklığa yerleştirdim.", "kavrama", "Burada kaşık gerçek anlamıyla kullanılmış."]],
          "Hangi cümlede gerçek bir kaşık yok?",
          ["Üç cümlede gerçek bir kaşıktan söz ediliyor.", "“Bir kaşık suda boğmak” bir deyimdir ve büyük öfkeyi anlatır.", "Mecaz anlamlı kullanım bu deyimin geçtiği cümlededir."],
          K("Deyimlerin içindeki sözcükler genellikle mecaz anlam kazanır.")),
      ],
    },
    oyun: [
      { tur: "eslestir", kaz: "trkas.deyim", soru: "Deyimleri anlamlarıyla eşleştir.", ciftler: [["kulak vermek", "dikkatle dinlemek"], ["kulak asmamak", "önemsememek"], ["bir kaşık suda boğmak", "çok kızmak"], ["ağzı kulaklarına varmak", "çok sevinmek"]], aciklama: "Deyimler mecaz anlamlıdır: “kulak vermek” dikkatle dinlemek, “ağzı kulaklarına varmak” çok sevinmek demektir." },
      { tur: "sirala", kaz: "trkas.dinleme", soru: "Etkili dinlemenin adımlarını sırala.", ogeler: ["Başlığa bakıp konuyu tahmin et", "Dikkatle dinle ve kısa notlar al", "Notlarından ana fikri bul", "Dinlediklerini kendi cümlelerinle özetle"], aciklama: "Önce tahmin, dinlerken not, sonra ana fikir ve özet." },
      { tur: "eslestir", kaz: "trkas.sozvarligi", soru: "Mutfak araçlarını görevleriyle eşleştir.", ciftler: [["kepçe", "çorbayı kâseye aktarır"], ["kevgir", "haşlanmış makarnanın suyunu süzer"], ["kaşıklık", "kaşıkları saklar"], ["rende", "peyniri ufalar"]], aciklama: "Kepçe sıvı aktarır, kevgir deliklidir ve süzer, kaşıklık kaşıkları saklar, rende ufalar." },
      { tur: "uret", kaz: "trkas.sozvarligi", soru: "KAŞIKÇI harfleriyle en az 3 anlamlı kelime üret.", harfler: "KAŞIKÇI", kelimeler: ["kaşıkçı", "kaşık", "kaçık", "ışık", "akış", "çakı", "kaş", "kış", "kaç", "aşk", "aş", "aç", "ak", "çık"], hedef: 3, aciklama: "Örnekler: kaşık, ışık, akış, çakı, kaş, kış, kaç. K ve I harflerinden ikişer tane var." },
    ],
  });

  /* SON */
})();
