/* 6. sınıf Türkçe — 2. tema: Bağımsızlık Yolu.
 * Kitap metinleri kullanılmaz; sorulardaki kısa metinler ve şiirler bu dosya için özgün olarak yazılmıştır.
 */
(function () {
  "use strict";
  const { R, sec, karistir, S, Q, G } = OGR;

  /* ------------------------- Ortak kısa metinler ------------------------- */
  const KAGNI = "<i>1921 yılının soğuk bir kış sabahıydı. İnebolu'dan yola çıkan kafile, karlı dağ yolunda ağır ağır ilerliyordu. Kağnıları çeken öküzlerin yanında Ayşe Nine de yürüyordu. Kağnının üstünde cepheye götürülecek top mermileri vardı. Kar yağmaya başlayınca Ayşe Nine, mermiler ıslanmasın diye onları kendi battaniyesiyle örttü.</i>";
  const KARAYEL = "<i>Köyün en hızlı atı Karayel'di. Bir gün muhtar, ordunun ata ihtiyacı olduğunu duyurdu. Küçük Mehmet, Karayel'in boynuna sarılıp ağladı. Sonra babasıyla birlikte atı askerlere teslim etti. Aylar sonra cepheden bir mektup geldi. Mektupta, Karayel'in yaralı bir askeri sırtında taşıyarak kurtardığı yazıyordu. Mehmet o gün hem hüzünlü hem gururluydu.</i>";

  /* =============================== 1. Cepheye Koşan At =============================== */
  KONU_EKLE("tr", {
    id: "tr_at", tema: "tr2", ad: "Cepheye Koşan At", sayfa: "s. 68", gorev: "Metni okuyup ayrıntıları bulma",
    kazanimlar: [
      { id: "trat.5n1k", ad: "Metinle ilgili 5N1K sorularını cevaplama" },
      { id: "trat.unsur", ad: "Hikâyenin unsurlarını (olay, kişi, yer, zaman) belirleme" },
      { id: "trat.ayrinti", ad: "Metindeki ayrıntıları ve duyguları fark etme" },
    ],
    anlatim: [
      {
        baslik: "5N1K: Metnin anahtarları",
        metin: "Bir metni iyi anlamak için altı soru sorarız: <b>Ne?</b> (ne oldu), <b>Nerede?</b> (hangi yerde), <b>Ne zaman?</b> (hangi zamanda), <b>Nasıl?</b> (hangi şekilde), <b>Niçin?</b> (hangi sebeple) ve <b>Kim?</b> (kimler). Bu sorulara <b>5N1K</b> denir. Cevapları bulduğunda metnin haritası elinde olur.",
        ornek: "“Ali, sabah okulda arkadaşına kitabını sevinçle verdi.” Kim? Ali. Ne zaman? Sabah. Nerede? Okulda. Nasıl? Sevinçle.",
        durak: { soru: "“Kurtuluş Savaşı yıllarında köylüler, cephaneyi kağnılarla taşıdı.” cümlesinde “Nasıl?” sorusunun cevabı hangisidir?", secenekler: [["Kağnılarla", true, "Cephanenin hangi yolla taşındığını söyler."], ["Köylüler", false, "Bu, “Kim?” sorusunun cevabıdır."], ["Kurtuluş Savaşı yıllarında", false, "Bu, “Ne zaman?” sorusunun cevabıdır."], ["Cephaneyi", false, "Bu, “Neyi?” sorusunun cevabıdır."]] },
      },
      {
        baslik: "Hikâyenin dört unsuru",
        metin: "Her hikâyede dört temel unsur vardır: <b>olay</b> (yaşanan durum), <b>kişiler</b> (olayı yaşayanlar; insan ya da hayvan olabilir), <b>yer</b> (olayın geçtiği mekân) ve <b>zaman</b>. Kurtuluş Savaşı hikâyelerinde kişiler çoğu zaman sıradan köylüler, kadınlar, çocuklar ve onlara yardım eden hayvanlardır.",
        ornek: "Bir atın cepheye gidişini anlatan hikâyede kişi: at ve sahibi; yer: köy ve cephe; zaman: savaş yılları; olay: atın orduya verilmesi.",
        durak: { soru: "Aşağıdakilerden hangisi hikâyenin unsurlarından biri değildir?", secenekler: [["Uyak", true, "Uyak, şiirde dize sonlarındaki ses benzerliğidir."], ["Olay", false, "Olay, hikâyenin temel unsurudur."], ["Yer", false, "Yer, olayın geçtiği mekândır; hikâye unsurudur."], ["Zaman", false, "Zaman, olayın ne zaman geçtiğini gösterir; hikâye unsurudur."]] },
      },
      {
        baslik: "Ayrıntı ve duygu avı",
        metin: "Metinlerde küçük <b>ayrıntılar</b> büyük anlamlar taşır. “Battaniyesiyle örttü” gibi bir ayrıntı, kişinin fedakârlığını gösterir. Kişilerin davranışlarından <b>duygularını</b> da çıkarabiliriz: ağlamak hüznü, göğsünü kabartmak gururu anlatır. Okurken “Bu ayrıntı bana ne anlatıyor?” diye sor.",
        ornek: "“Mehmet atının boynuna sarılıp ağladı.” → Duygu: hüzün, ayrılık acısı.",
        durak: { soru: "“Ayşe Nine, mermiler ıslanmasın diye onları kendi battaniyesiyle örttü.” Bu ayrıntı Ayşe Nine'nin hangi özelliğini gösterir?", secenekler: [["Fedakârlığını", true, "Üşüme pahasına battaniyesini mermilere veriyor."], ["Korkaklığını", false, "Korkuyu gösteren bir davranış yok."], ["Tembelliğini", false, "Karlı yolda yürüyüp yük taşımak tembellik değildir."], ["Bencilliğini", false, "Kendi rahatını değil, cepheyi düşünüyor."]] },
      },
    ],
    uret: {
      "trat.5n1k": [
        Q("trat.5n1k", "hatirlama", 1, KAGNI + "<br><br>Kafile <b>nereden</b> yola çıkmıştır?", "İnebolu'dan",
          [["Ankara'dan", "dikkat", "Metinde Ankara geçmiyor; çıkış yeri metnin ikinci cümlesinde yazıyor."], ["Samsun'dan", "dikkat", "Samsun bu metinde geçmiyor; metne geri dön."], ["Cepheden", "kavrama", "Cephe, yükün götürüleceği yerdir; çıkış yeri değildir."]],
          "“Yola çıkan” sözünün geçtiği cümleye bak.",
          ["Soru “Nereden?” diye yeri soruyor.", "İkinci cümlede “İnebolu'dan yola çıkan kafile” deniyor.", "Cevap: İnebolu'dan."],
          { kural: "Nerede / Nereden? soruları olayın geçtiği ya da başladığı yeri bulur." }),
        Q("trat.5n1k", "hatirlama", 1, KAGNI + "<br><br>Olay <b>ne zaman</b> geçmektedir?", "1921 yılında bir kış sabahı",
          [["1919 yılında bir yaz akşamı", "dikkat", "Metindeki yıl ve mevsim farklı; ilk cümleyi yeniden oku."], ["1922 yılında bir bahar günü", "dikkat", "Metinde bahar değil kar ve kış var."], ["Savaş bittikten sonra", "kavrama", "Mermiler cepheye götürülüyor; savaş sürüyor."]],
          "Metnin ilk cümlesi zamanı veriyor.",
          ["Soru zamanı soruyor.", "İlk cümle: “1921 yılının soğuk bir kış sabahıydı.”", "Cevap: 1921 yılında bir kış sabahı."],
          { kural: "Ne zaman? sorusunun cevabı yıl, mevsim, gün, saat gibi zaman ifadeleridir." }),
        Q("trat.5n1k", "aciklama", 2, KAGNI + "<br><br>Ayşe Nine mermileri <b>niçin</b> battaniyesiyle örtmüştür?", "Islanmasınlar diye",
          [["Üşümesinler diye", "kavrama", "Mermiler canlı değildir, üşümez; metinde sebep açıkça yazıyor."], ["Saklamak için", "dikkat", "Metinde bir şeyi gizlemekten söz edilmiyor."], ["Hafiflesinler diye", "kavrama", "Örtmek yükü hafifletmez; sebep başka."]],
          "Cümlede “diye” sözcüğünden önceki kısım sebebi verir.",
          ["Soru sebebi (Niçin?) soruyor.", "“mermiler ıslanmasın diye” ifadesi sebebi açıklıyor.", "Cevap: Islanmasınlar diye."],
          { kural: "Niçin? / Neden? soruları sebebi bulur. “için, diye, -dığı için” sözleri sebep bildirir." }),
        Q("trat.5n1k", "uygulama", 2, "“Şerife Hanım, kağnısını donmuş yollarda sabırla sürdü.” cümlesinde <b>Nasıl?</b> sorusunun cevabı hangisidir?", "Sabırla",
          [["Şerife Hanım", "kavrama", "Bu, “Kim?” sorusunun cevabıdır."], ["Donmuş yollarda", "kavrama", "Bu, “Nerede?” sorusunun cevabıdır."], ["Kağnısını", "kavrama", "Bu, “Neyi?” sorusunun cevabıdır."]],
          "Nasıl? sorusu işin hangi şekilde yapıldığını sorar.",
          ["Soruyu yükleme sor: “Nasıl sürdü?”", "Cevap “sabırla” olur.", "Diğer seçenekler kim, nerede ve neyi sorularına cevap verir."],
          { kural: "Nasıl? sorusu eylemin yapılış biçimini gösterir: sabırla, hızla, sevinçle…" }),
        Q("trat.5n1k", "transfer", 2, "Okul gazetesi için Kurtuluş Savaşı'nda yardım eden bir köylü kadınla ilgili haber yazacaksın. Haberin ilk cümlesinde en çok hangi bilgiler bulunmalıdır?", "Kim, ne yaptı, nerede ve ne zaman",
          [["Yalnızca senin duyguların", "strateji", "Haberin girişinde önce olayın temel bilgileri verilir."], ["Sadece bir atasözü", "strateji", "Atasözü süs olabilir ama haberin temel bilgisi değildir."], ["Haberin başlığının renk ve boyutu", "kavrama", "Bu, biçimle ilgilidir; içerikle ilgili değildir."]],
          "Haberin girişi okura 5N1K'nın en önemli cevaplarını verir.",
          ["Haber metni bir olayı anlatır.", "Okur önce kimin, neyi, nerede ve ne zaman yaptığını öğrenmek ister.", "Bu yüzden ilk cümlede 5N1K bilgileri bulunur."],
          { kural: "Haber yazarken 5N1K sorularının cevaplarını vermeyi unutma." }),
      ],
      "trat.unsur": [
        Q("trat.unsur", "hatirlama", 1, KARAYEL + "<br><br>Bu hikâyenin <b>kişileri</b> arasında aşağıdakilerden hangisi yer almaz?", "Öğretmen",
          [["Mehmet", "dikkat", "Mehmet hikâyenin ana kişisidir."], ["Karayel", "kavrama", "Hayvanlar da hikâyede kişi (karakter) olabilir; Karayel bir kişidir."], ["Muhtar", "dikkat", "Muhtar, ordunun ata ihtiyacı olduğunu duyuruyor; o da hikâyede var."]],
          "Hikâyede adı geçen ve olaya katılan herkesi listele.",
          ["Hikâyede geçenler: Karayel, muhtar, Mehmet, babası, askerler.", "Öğretmenden hiç söz edilmiyor.", "Cevap: Öğretmen."],
          { kural: "Hikâyede kişi, olayı yaşayan ya da olaya katılan varlıktır; hayvanlar da kişi olabilir." }),
        Q("trat.unsur", "aciklama", 2, KARAYEL + "<br><br>Bu hikâyenin <b>ana olayı</b> hangisidir?", "Mehmet'in atını orduya vermesi",
          [["Mehmet'in okula başlaması", "dikkat", "Hikâyede okuldan söz edilmiyor."], ["Muhtarın köye gelmesi", "kavrama", "Bu, olayı başlatan küçük bir ayrıntıdır; ana olay değildir."], ["Mehmet'in yeni bir at alması", "dikkat", "Mehmet at almıyor, atını veriyor."]],
          "Hikâyenin baştan sona etrafında döndüğü durumu bul.",
          ["Ana olay, hikâyenin merkezindeki durumdur.", "Hikâye, Karayel'in orduya verilmesi ve sonrasında olanlar üzerine kurulu.", "Cevap: Mehmet'in atını orduya vermesi."],
          { kural: "Olay: hikâyede yaşanan ana durumdur; diğer ayrıntılar bu olayın çevresinde gelişir." }),
        Q("trat.unsur", "uygulama", 2, "<i>Bayram sabahı Hatice, ninesinin dizinin dibine oturdu. Ninesi, Kurtuluş Savaşı'nda köylerinden cepheye nasıl ekmek gönderdiklerini anlattı.</i><br><br>Bu metinde anlatılanların geçtiği <b>zaman</b> hangisidir?", "Bayram sabahı",
          [["Kurtuluş Savaşı yılları", "dikkat", "Bu, ninenin anlattığı anının zamanıdır; Hatice ile ninesinin konuşması bayram sabahı geçiyor."], ["Akşam yemeği", "dikkat", "Metinde akşamdan söz edilmiyor."], ["Ninenin evi", "kavrama", "Bu bir zaman değil, yer bildirir."]],
          "Hatice ile ninesinin konuştuğu anı düşün.",
          ["Soru metindeki olayın zamanını soruyor.", "Metin “Bayram sabahı” diye başlıyor.", "Cevap: Bayram sabahı."],
          { kural: "Zaman: olayın geçtiği vakit. Yer: olayın geçtiği mekân. İkisini karıştırma." }),
        Q("trat.unsur", "baglanti", 2, "1. temada okuduğun metinlerde de hikâye unsurlarını bulmuştun. Aşağıdaki eşleştirmelerden hangisi <b>yanlıştır</b>?", "Uyak – hikâyenin geçtiği yer",
          [["Kişi – olayı yaşayan varlık", "kavrama", "Bu eşleştirme doğrudur."], ["Zaman – olayın geçtiği vakit", "kavrama", "Bu eşleştirme doğrudur."], ["Olay – hikâyede yaşanan durum", "kavrama", "Bu eşleştirme doğrudur."]],
          "Hikâye unsurlarını say: olay, kişi, yer, zaman.",
          ["Hikâyenin dört unsuru: olay, kişi, yer, zaman.", "Uyak bir şiir bilgisidir; yer ile ilgisi yoktur.", "Yanlış eşleştirme: Uyak – hikâyenin geçtiği yer."],
          { kural: "Hikâye unsurları: olay, kişi, yer, zaman. Uyak, dize ve kıta ise şiir bilgileridir." }),
      ],
      "trat.ayrinti": [
        Q("trat.ayrinti", "aciklama", 1, KARAYEL + "<br><br>Hikâyenin sonunda Mehmet'in duyguları nelerdir?", "Hüzün ve gurur",
          [["Öfke ve kıskançlık", "kavrama", "Mehmet kimseye kızmıyor ya da kimseyi kıskanmıyor."], ["Korku ve şaşkınlık", "dikkat", "Son cümlede duygular açıkça yazıyor."], ["Pişmanlık ve utanç", "kavrama", "Mehmet atını verdiği için pişman değil, gururlu."]],
          "Son cümleyi dikkatle oku.",
          ["Soru Mehmet'in hikâyenin sonundaki duygularını soruyor.", "Son cümle: “hem hüzünlü hem gururluydu.”", "Cevap: Hüzün ve gurur."],
          { kural: "Duygular bazen açıkça yazılır, bazen davranışlardan (ağlamak, gülmek) anlaşılır." }),
        Q("trat.ayrinti", "uygulama", 2, KARAYEL + "<br><br>“Mehmet, Karayel'in boynuna sarılıp ağladı.” cümlesi bize ne anlatır?", "Mehmet'in atını çok sevdiğini",
          [["Mehmet'in attan korktuğunu", "kavrama", "Korkan biri hayvanın boynuna sarılmaz."], ["Atın hasta olduğunu", "dikkat", "Metinde atın hastalığından söz edilmiyor."], ["Mehmet'in askerlere kızdığını", "kavrama", "Mehmet atı kendi isteğiyle, babasıyla birlikte teslim ediyor."]],
          "Birinden ayrılırken neden ağlarız?",
          ["Ayrıntı bir davranışı anlatıyor: sarılmak ve ağlamak.", "Sevdiğimiz bir varlıktan ayrılırken böyle davranırız.", "Cevap: Mehmet'in atını çok sevdiğini."],
          { kural: "Kişilerin davranışları duygularını ve özelliklerini ortaya koyar." }),
        Q("trat.ayrinti", "uygulama", 2, "Aşağıdaki ayrıntılardan hangisi Kurtuluş Savaşı'nda halkın <b>fedakârlığını</b> göstermez?", "Köylülerin pazarda sebze satması",
          [["Kadınların cephaneyi sırtında taşıması", "kavrama", "Ağır yükü taşımak büyük bir fedakârlıktır."], ["Ailelerin atlarını orduya vermesi", "kavrama", "Sevdiği hayvanı vermek bir fedakârlıktır."], ["Köylülerin yiyeceklerini askerlerle paylaşması", "kavrama", "Kendi azığını paylaşmak fedakârlıktır."]],
          "Fedakârlık, başkası için kendi rahatından ya da malından vazgeçmektir.",
          ["Her seçenekte biri bir şeyden vazgeçiyor mu, ona bak.", "Pazarda sebze satmak günlük bir iştir; bir vazgeçme yoktur.", "Cevap: Köylülerin pazarda sebze satması."],
          { kural: "Fedakârlık: başkalarının iyiliği için kendi isteğinden, rahatından ya da malından vazgeçmek." }),
        Q("trat.ayrinti", "transfer", 3, "<i>Kağnı tekerleği gıcırdıyor, öküzler soluk soluğa yokuşu tırmanıyordu. Fatma, yorgun hayvanların başını okşayıp “Az kaldı, dayanın!” dedi.</i><br><br>Bu metindeki ayrıntılar en çok hangi düşünceyi destekler?", "Cepheye yardım için insanlar da hayvanlar da büyük emek verdi.",
          [["Kağnılar çok hızlı araçlardı.", "kavrama", "Yokuşu soluk soluğa tırmanmak hız değil, zorluk anlatır."], ["Fatma hayvanlara kötü davranıyordu.", "dikkat", "Fatma hayvanların başını okşuyor; şefkatli davranıyor."], ["Yolculuk çok kolay geçiyordu.", "kavrama", "Gıcırdayan tekerlek ve yorgun öküzler zorluğu gösterir."]],
          "Ayrıntıları tek tek düşün: gıcırdayan tekerlek, soluk soluğa öküzler, “Az kaldı, dayanın!”",
          ["Ayrıntılar yolculuğun zor olduğunu gösteriyor.", "Fatma da hayvanlar da bu zorluğa katlanıyor.", "Metin, cepheye yardım için herkesin emek verdiğini destekliyor."],
          { kural: "Ayrıntıları birleştirerek metnin asıl söylemek istediğine ulaşabilirsin." }),
      ],
    },
    oyun: [
      { tur: "eslestir", kaz: "trat.5n1k", soru: "“Ayşe Nine” metnindeki soruları cevaplarıyla eşleştir.", ciftler: [["Kim?", "Ayşe Nine"], ["Nereden?", "İnebolu'dan"], ["Ne zaman?", "1921 kışında"], ["Niçin örttü?", "Mermiler ıslanmasın diye"]], aciklama: "5N1K soruları metnin temel bilgilerini bulmanı sağlar: kişi, yer, zaman ve sebep." },
      { tur: "sirala", kaz: "trat.unsur", soru: "Karayel'in hikâyesindeki olayları oluş sırasına göre diz.", ogeler: ["Muhtar, ordunun ata ihtiyacı olduğunu duyurdu.", "Mehmet, Karayel'in boynuna sarılıp ağladı.", "Mehmet ve babası atı askerlere teslim etti.", "Cepheden bir mektup geldi.", "Mehmet hem hüzünlendi hem gururlandı."], aciklama: "Hikâyede olaylar bir sıra izler: önce duyuru, sonra ayrılık, ardından teslim, en sonda haber ve duygular." },
      { tur: "eslestir", kaz: "trat.unsur", soru: "Hikâye unsurlarını örnekleriyle eşleştir.", ciftler: [["Kişi", "Karayel adlı at"], ["Yer", "Köy meydanı"], ["Zaman", "Savaş yılları"], ["Olay", "Atın orduya verilmesi"]], aciklama: "Hikâyenin dört unsuru: kişi, yer, zaman ve olay." },
    ],
  });

  /* =============================== 2. Vatan =============================== */
  const SIIR1 = "<i>Toprağında büyüdüm, suyunu içtim,<br>Her taşında atamın izini seçtim.<br>Bir çiçek gibi açar gönlümde adın,<br>Sen benim canım, sen benim yurdum, vatanım!</i>";
  const SIIR2 = "<i>Dağlarında rüzgâr türkü söyler,<br>Ovalarında başak dalga dalga.<br>Bu toprak için ne canlar verildi,<br>Unutmayalım, sahip çıkalım ona!</i>";
  KONU_EKLE("tr", {
    id: "tr_vatan", tema: "tr2", ad: "Vatan", sayfa: "s. 78", gorev: "Ana fikir ve duygu belirleme",
    kazanimlar: [
      { id: "trvat.anafikir", ad: "Şiirin konusunu ve ana fikrini belirleme" },
      { id: "trvat.duygu", ad: "Şiirde dile getirilen duyguları belirleme" },
      { id: "trvat.siir", ad: "Şiir bilgisi: dize, kıta ve uyağı tanıma" },
    ],
    anlatim: [
      {
        baslik: "Konu ve ana fikir",
        metin: "Bir şiirin <b>konusu</b>, neyden söz ettiğidir: vatan, anne, doğa… <b>Ana fikir</b> ise şairin bu konu hakkında bize vermek istediği asıl mesajdır. Konu tek kelimeyle söylenebilir; ana fikir genellikle bir cümledir. Ana fikri bulmak için “Şair bize ne söylemek istiyor?” diye sor.",
        ornek: "Konu: vatan. Ana fikir: Vatan, uğrunda canlar verilmiş en değerli varlığımızdır; ona sahip çıkmalıyız.",
        durak: { soru: "Aşağıdakilerden hangisi bir <b>konu</b> değil, <b>ana fikir</b> cümlesidir?", secenekler: [["Vatanı sevmek, her vatandaşın görevidir.", true, "Bu bir cümledir ve şairin mesajını verir."], ["Vatan sevgisi", false, "Bu, konu olarak söylenebilir."], ["Bayrak", false, "Bu yalnızca bir konu adıdır."], ["Şehitler", false, "Bu da bir konu adıdır; mesaj bildirmez."]] },
      },
      {
        baslik: "Şiirdeki duygular",
        metin: "Şairler şiirlerinde <b>duygularını</b> dile getirir: sevgi, özlem, hüzün, gurur, coşku, minnet… Vatan şiirlerinde en çok <b>vatan sevgisi</b>, <b>gurur</b> ve şehitlere karşı <b>minnet</b> duygusu görülür. Duyguyu bulmak için şiirdeki seslenmelere (Vatanım!), ünlemlere ve duygu sözcüklerine dikkat et.",
        ornek: "“Sen benim canım, sen benim yurdum, vatanım!” dizesinde coşkulu bir vatan sevgisi vardır.",
        durak: { soru: "“Bu toprak için ne canlar verildi, / Unutmayalım, sahip çıkalım ona!” dizelerinde hangi duygu öne çıkar?", secenekler: [["Şehitlere minnet ve vatana bağlılık", true, "Canlarını verenleri anıp toprağa sahip çıkmayı istiyor."], ["Neşe ve eğlence", false, "Dizelerde eğlenceli bir durum yok."], ["Kıskançlık", false, "Kimse kıskanılmıyor."], ["Korku ve kaygı", false, "Dizelerde bir çağrı ve bağlılık var, korku yok."]] },
      },
      {
        baslik: "Dize, kıta, uyak",
        metin: "Şiirin her bir satırına <b>dize</b> (mısra) denir. Dizelerden oluşan gruplara <b>kıta</b> denir; dört dizelik bir bölüm bir kıtadır. Dize sonlarındaki ses benzerliğine <b>uyak</b> (kafiye) denir. Örneğin “içtim – seçtim” sözcüklerinde “-çtim” sesleri benzer.",
        ornek: "“Toprağında büyüdüm, suyunu içtim, / Her taşında atamın izini seçtim.” → 2 dize; “içtim – seçtim” uyaklıdır.",
        durak: { soru: "Şiirde dize sonlarında görülen ses benzerliğine ne ad verilir?", secenekler: [["Uyak", true, "Uyak (kafiye), dize sonlarındaki ses benzerliğidir."], ["Kıta", false, "Kıta, dizelerden oluşan bölümdür."], ["Dize", false, "Dize, şiirin her bir satırıdır."], ["Başlık", false, "Başlık şiirin adıdır."]] },
      },
    ],
    uret: {
      "trvat.anafikir": [
        Q("trvat.anafikir", "aciklama", 1, SIIR1 + "<br><br>Bu dörtlüğün <b>konusu</b> nedir?", "Vatan sevgisi",
          [["Doğa gezisi", "kavrama", "Çiçekten söz edilse de asıl konu doğa değil, vatandır."], ["Okul hayatı", "dikkat", "Dörtlükte okuldan söz edilmiyor."], ["Arkadaşlık", "dikkat", "Dörtlükte arkadaşlıkla ilgili bir söz yok."]],
          "Son dizede kime sesleniliyor?",
          ["Konu, şiirin neyden söz ettiğidir.", "Şair toprağa, taşa, “vatanım” diye vatana sesleniyor.", "Konu: Vatan sevgisi."],
          { kural: "Konu: metnin neyden söz ettiği. Kısa bir ifadeyle söylenir." }),
        Q("trvat.anafikir", "aciklama", 2, SIIR2 + "<br><br>Bu dörtlüğün <b>ana fikri</b> hangisidir?", "Uğrunda canlar verilen vatana sahip çıkmalıyız.",
          [["Dağlarda rüzgâr sesi çok güzeldir.", "kavrama", "Bu, şiirdeki bir ayrıntıdır; asıl mesaj değildir."], ["Ovalarda buğday yetişir.", "kavrama", "Bu da bir ayrıntıdır; şairin asıl söylediği değildir."], ["Türkü söylemeyi öğrenmeliyiz.", "dikkat", "Türkü sözcüğü geçiyor ama şair bunu öğütlemiyor."]],
          "Şairin bize çağrısı hangi dizede?",
          ["Ana fikir şairin vermek istediği mesajdır.", "Son iki dize: canlar verilen bu toprağı unutmayıp sahip çıkmamızı istiyor.", "Ana fikir: Uğrunda canlar verilen vatana sahip çıkmalıyız."],
          { kural: "Ana fikir genellikle şiirin sonunda ya da şairin seslenip öğüt verdiği dizelerde gizlidir." }),
        Q("trvat.anafikir", "uygulama", 2, "<i>Bayrağım, göklerde dalgalan dursun,<br>Seni bize emanet edenler nur içinde uyusun.<br>Ellerimiz hep senin yolunda,<br>Ay yıldızlı al rengin hep parlasın.</i><br><br>Bu dizelere en uygun <b>başlık</b> hangisidir?", "Al Bayrağım",
          [["Sonbahar", "dikkat", "Dizelerde mevsimle ilgili bir söz yok."], ["Gökyüzündeki Kuşlar", "kavrama", "“Gökler” geçiyor ama dalgalanan şey kuş değil, bayrak."], ["Annemin Elleri", "dikkat", "“Ellerimiz” geçiyor ama konu anne değil."]],
          "Başlık, konuyu en iyi yansıtan kısa ifadedir.",
          ["Önce konuyu bul: dizeler bayrağa sesleniyor.", "Başlık konuyu yansıtmalı.", "En uygun başlık: Al Bayrağım."],
          { kural: "Başlık metnin konusunu ya da ana fikrini kısaca yansıtır." }),
        Q("trvat.anafikir", "transfer", 2, "Sınıf panosuna “Vatan” konulu bir şiir asılacak. Şiirin altına ana fikri yazacaksın. Aşağıdakilerden hangisi ana fikir olarak yazılmaya <b>en uygun</b> olandır?", "Vatanımızı sevmek ve korumak hepimizin görevidir.",
          [["Vatan", "kavrama", "Bu tek kelime bir konu adıdır, ana fikir değildir."], ["Şiir dört dizeden oluşuyor.", "kavrama", "Bu, şiirin biçimiyle ilgili bir bilgidir."], ["Şair şiiri sabah yazmış.", "strateji", "Bu bilgi şiirin mesajını vermez."]],
          "Ana fikir bir mesaj taşıyan cümledir.",
          ["Ana fikir, şiirin okura verdiği mesajdır.", "Tek kelime ya da biçim bilgisi mesaj taşımaz.", "Uygun ana fikir: Vatanımızı sevmek ve korumak hepimizin görevidir."],
          { kural: "Ana fikir = Şair (yazar) bize ne öğretmek, ne söylemek istiyor?" }),
      ],
      "trvat.duygu": [
        Q("trvat.duygu", "aciklama", 1, SIIR1 + "<br><br>Bu dörtlükte en çok hangi duygu hissedilir?", "Vatan sevgisi",
          [["Özlem", "kavrama", "Şair vatanından uzakta değil; özlemden söz etmiyor."], ["Korku", "dikkat", "Dörtlükte korkuyu anlatan bir sözcük yok."], ["Öfke", "dikkat", "Şair kimseye kızmıyor."]],
          "“Sen benim canım… vatanım!” seslenişine dikkat et.",
          ["Duyguyu bulmak için duygu sözcüklerine ve seslenişlere bak.", "Şair vatanını “canım” diye çağırıyor; adı gönlünde çiçek gibi açıyor.", "Duygu: Vatan sevgisi."],
          { kural: "Seslenmeler (Ey vatan!, Vatanım!) ve ünlemler şiirdeki duyguyu ortaya çıkarır." }),
        Q("trvat.duygu", "uygulama", 2, "Aşağıdaki dizelerin hangisinde <b>özlem</b> duygusu vardır?", "Gurbette her gece seni düşünürüm, köyüm.",
          [["Bayrağım dalgalanınca göğsüm kabarır.", "kavrama", "Göğsün kabarması gurur duygusunu anlatır."], ["Zafer günü sevinçle koştu çocuklar.", "kavrama", "Bu dizede sevinç ve coşku vardır."], ["Şehitlerimize minnetle eğiliriz.", "kavrama", "Bu dizede minnet (teşekkür borcu) duygusu vardır."]],
          "Özlem, uzakta olan bir şeye kavuşmayı istemektir.",
          ["Özlem için uzaklık ve kavuşma isteği gerekir.", "“Gurbette” uzaklığı, “her gece seni düşünürüm” kavuşma isteğini gösterir.", "Cevap: Gurbette her gece seni düşünürüm, köyüm."],
          { kural: "Gurur: göğsün kabarması. Özlem: uzaktakini istemek. Minnet: iyiliğe karşı borçluluk duygusu." }),
        Q("trvat.duygu", "uygulama", 2, "“Bu topraklar için can veren kahramanlara sonsuz teşekkür borçluyuz.” cümlesindeki duygu hangisidir?", "Minnet",
          [["Kıskançlık", "kavrama", "Cümlede kimse kıskanılmıyor."], ["Hayal kırıklığı", "kavrama", "Cümlede beklentinin boşa çıkması anlatılmıyor."], ["Merak", "kavrama", "Cümlede bir şeyi öğrenme isteği yok."]],
          "“Teşekkür borçluyuz” ifadesi hangi duyguyu anlatır?",
          ["Duygu sözcüğünü bul: “teşekkür borçluyuz”.", "Birinin iyiliğine karşı duyulan borçluluk duygusu minnettir.", "Cevap: Minnet."],
          { kural: "Minnet: yapılan iyiliğe karşı duyulan teşekkür ve borçluluk duygusu." }),
        Q("trvat.duygu", "baglanti", 2, "“Cepheye Koşan At” metnindeki Mehmet de atını verirken hem hüzün hem gurur duymuştu. Aşağıdaki dizelerden hangisi <b>gurur</b> duygusunu anlatır?", "Ay yıldızlı bayrağım, seninle başım dik!",
          [["Ayrılık günü gözlerim doldu.", "kavrama", "Gözlerin dolması hüznü anlatır."], ["Geceleri yolunu gözlerim.", "kavrama", "Yol gözlemek özlemi anlatır."], ["Karanlıkta yalnız kaldım, titredim.", "kavrama", "Titremek korkuyu anlatır."]],
          "Başı dik olmak hangi duygunun işaretidir?",
          ["Her dizedeki davranışın hangi duyguyu gösterdiğini düşün.", "“Başım dik” ifadesi onur ve gurur anlatır.", "Cevap: Ay yıldızlı bayrağım, seninle başım dik!"],
          { kural: "Davranışlar duyguları anlatır: başı dik olmak gurur, gözlerin dolması hüzün, yol gözlemek özlem." }),
      ],
      "trvat.siir": [
        Q("trvat.siir", "hatirlama", 1, SIIR2 + "<br><br>Bu şiir parçası kaç <b>dizeden</b> oluşur?", "4",
          [["2", "dikkat", "Satırları yeniden say; her satır bir dizedir."], ["1", "kavrama", "Dörtlük bir kıtadır, dize değildir."], ["8", "dikkat", "Satırları tek tek say."]],
          "Her satır bir dizedir.",
          ["Dize, şiirin her bir satırıdır.", "Satırları say: 1, 2, 3, 4.", "Cevap: 4 dize."],
          { kural: "Dize (mısra): şiirin her bir satırı. Dört dizelik bölüm: dörtlük (kıta)." }),
        Q("trvat.siir", "hatirlama", 1, "Şiirde dizelerden oluşan her bir bölüme ne ad verilir?", "Kıta",
          [["Uyak", "kavrama", "Uyak, dize sonlarındaki ses benzerliğidir."], ["Paragraf", "kavrama", "Paragraf düz yazıdaki bölümdür; şiirde kıta denir."], ["Başlık", "bilgi", "Başlık şiirin adıdır."]],
          "Dörtlük de bunun bir çeşididir.",
          ["Soru şiirin bölümlerini soruyor.", "Dizeler bir araya gelince kıtayı oluşturur.", "Cevap: Kıta."],
          { kural: "Dize → satır. Kıta → dizelerden oluşan bölüm. Uyak → dize sonlarındaki ses benzerliği." }),
        Q("trvat.siir", "uygulama", 2, "“Toprağında büyüdüm, suyunu <b>içtim</b>, / Her taşında atamın izini <b>seçtim</b>.” dizelerinde uyağı oluşturan ortak ses grubu hangisidir?", "-çtim",
          [["-tim", "dikkat", "Ortak sesler daha uzun; “ç” sesi de iki sözcükte ortak."], ["toprak – taş", "kavrama", "Uyak dize sonlarında aranır, dize başlarında değil."], ["-ında", "dikkat", "“Toprağında – taşında” dize ortasındadır; uyak dize sonundadır."]],
          "Dize sonundaki iki sözcüğü alt alta yaz, ortak harfleri işaretle.",
          ["Dize sonları: içtim – seçtim.", "Sondan başlayarak ortak sesler: m, i, t, ç → “-çtim”.", "Cevap: -çtim."],
          { kural: "Uyak, dize sonlarında aranır. Sondan başa doğru ortak sesleri bul." }),
        Q("trvat.siir", "uygulama", 2, "Aşağıdaki sözcük çiftlerinden hangisi <b>uyaklı</b> değildir?", "vatan – bayrak",
          [["bayrak – toprak", "kavrama", "“-rak” sesleri ortaktır; bu çift uyaklıdır."], ["dağlar – ağlar", "kavrama", "“-ağlar” sesleri ortaktır; bu çift uyaklıdır."], ["zafer – sefer", "kavrama", "“-fer” sesleri ortaktır; bu çift uyaklıdır."]],
          "Her çiftin son seslerini karşılaştır.",
          ["Uyakta sözcüklerin son sesleri benzer olmalı.", "“vatan” -an ile, “bayrak” -ak ile bitiyor; ortak ses grubu yok.", "Cevap: vatan – bayrak."],
          { kural: "Uyak için sözcük sonlarında en az bir ses benzerliği gerekir: toprak – bayrak." }),
        Q("trvat.siir", "transfer", 3, "Kendi vatan şiirini yazıyorsun. İlk dizen “Ay yıldızlı bayrağım göklerde <b>dalgalanır</b>” oldu. İkinci dizenin sonuna hangi sözcüğü koyarsan uyak oluşur?", "sağlanır",
          [["parlar", "dikkat", "“parlar” -ar ile, “dalgalanır” -ır ile biter; son sesler benzemiyor."], ["bayrak", "kavrama", "“dalgalanır” ile “bayrak” arasında ses benzerliği yok."], ["vatan", "kavrama", "“vatan” sözcüğünün sonu “dalgalanır” ile benzeşmiyor."]],
          "“dalgalanır” sözcüğünün sonundaki sesleri bul.",
          ["Uyak için son sesler benzer olmalı.", "“dalgalanır – sağlanır”: “-lanır” sesleri ortak.", "En uygun sözcük: sağlanır."],
          { kural: "Ortak ses sayısı arttıkça uyak daha güçlü olur." }),
      ],
    },
    oyun: [
      { tur: "eslestir", kaz: "trvat.siir", soru: "Şiir bilgilerini tanımlarıyla eşleştir.", ciftler: [["Dize", "Şiirin her bir satırı"], ["Kıta", "Dizelerden oluşan bölüm"], ["Uyak", "Dize sonlarındaki ses benzerliği"], ["Başlık", "Şiirin adı"]], aciklama: "Dize satırdır, kıta dizelerden oluşan bölümdür, uyak dize sonundaki ses benzerliğidir." },
      { tur: "eslestir", kaz: "trvat.duygu", soru: "Dizeleri içerdikleri duygularla eşleştir.", ciftler: [["Bayrağım dalgalanınca göğsüm kabarır.", "Gurur"], ["Gurbette her gece seni düşünürüm.", "Özlem"], ["Şehitlere sonsuz teşekkür borçluyuz.", "Minnet"], ["Zafer günü sevinçle koştu çocuklar.", "Sevinç"]], aciklama: "Göğsün kabarması gurur, gurbette düşünmek özlem, teşekkür borcu minnet, sevinçle koşmak sevinç anlatır." },
      { tur: "eslestir", kaz: "trvat.siir", soru: "Uyaklı sözcükleri eşleştir.", ciftler: [["bayrak", "toprak"], ["zafer", "sefer"], ["içtim", "seçtim"], ["dağlar", "ağlar"]], aciklama: "Uyaklı sözcüklerin sonları benzer seslerle biter: bayrak – toprak (-rak), zafer – sefer (-fer)." },
      { tur: "uret", kaz: "trvat.anafikir", soru: "VATANIM harfleriyle en az 3 anlamlı kelime üret.", harfler: "VATANIM", kelimeler: ["vatanım", "vatan", "tavan", "manav", "tanım", "anıt", "tanı", "tava", "anma", "ana", "ata", "ama", "tam", "mat", "nam", "tan", "atı", "anı", "an", "at"], hedef: 3, aciklama: "Vatan, tavan, manav, anıt, tava, ana, ata… Harfleri farklı sıralarla dene!" },
    ],
  });

  /* =============================== 3. İstiklâl Marşı (Dinleme/İzleme) =============================== */
  const IM_BILGI = G.tablo(["Bilgi", "Cevap"], [["Şairi", "Mehmet Âkif Ersoy"], ["TBMM'de kabul tarihi", "12 Mart 1921"], ["Kıta sayısı", "10 kıta"], ["İthaf edildiği yer", "Kahraman Ordumuza"], ["Bugünkü bestesi", "Osman Zeki Üngör"]]);
  KONU_EKLE("tr", {
    id: "tr_istiklal", tema: "tr2", ad: "Rafadan Tayfa – İstiklâl Marşı (Dinleme/İzleme)", sayfa: "s. 90", gorev: "Dinleme/izleme soruları",
    kazanimlar: [
      { id: "trist.bilgi", ad: "İstiklâl Marşı'nın şairini, kabul tarihini ve önemini bilme" },
      { id: "trist.anlam", ad: "İstiklâl Marşı'ndaki dize ve sözcüklerin anlamını kavrama" },
      { id: "trist.dinleme", ad: "Dinleme/izleme stratejilerini (not alma, tahmin, ana fikri bulma) ve saygı kurallarını uygulama" },
    ],
    anlatim: [
      {
        baslik: "Millî marşımız",
        metin: "İstiklâl Marşı'nın şairi <b>Mehmet Âkif Ersoy</b>'dur. Marş, Kurtuluş Savaşı'nın en zor günlerinde, <b>12 Mart 1921</b>'de Türkiye Büyük Millet Meclisinde kabul edildi. Âkif, marşı <b>“Kahraman Ordumuza”</b> ithaf etti, yani orduya armağan etti. Marş <b>10 kıtadır</b>; törenlerde ilk iki kıtası okunur. İstiklâl “bağımsızlık” demektir.",
        ornek: "12 Mart, her yıl İstiklâl Marşı'nın Kabulü ve Mehmet Âkif Ersoy'u Anma Günü olarak anılır.",
        durak: { soru: "İstiklâl Marşı hangi tarihte TBMM'de kabul edilmiştir?", secenekler: [["12 Mart 1921", true, "Marş, Kurtuluş Savaşı sürerken 12 Mart 1921'de kabul edildi."], ["19 Mayıs 1919", false, "Bu, Mustafa Kemal Paşa'nın Samsun'a çıktığı tarihtir."], ["23 Nisan 1920", false, "Bu, TBMM'nin açıldığı tarihtir."], ["29 Ekim 1923", false, "Bu, Cumhuriyet'in ilan edildiği tarihtir."]] },
      },
      {
        baslik: "Dizelerin anlamı",
        metin: "Marşın ilk dizesi “<b>Korkma, sönmez bu şafaklarda yüzen al sancak;</b>” şeklindedir. <b>Al sancak</b> kırmızı bayrak, <b>şafak</b> sabahın ilk aydınlığı demektir. Şair, millete “Korkma, bayrağımız hiç inmeyecek.” diye umut verir. “<b>Ben ezelden beridir hür yaşadım, hür yaşarım.</b>” dizesinde <b>ezel</b> başlangıcı olmayan geçmiş, <b>hür</b> özgür anlamındadır.",
        ornek: "“Hakkıdır, Hakk'a tapan milletimin istiklâl.” → Bağımsızlık, Allah'a inanan milletimin hakkıdır.",
        durak: { soru: "“Korkma, sönmez bu şafaklarda yüzen <b>al sancak</b>” dizesindeki “al sancak” ne anlama gelir?", secenekler: [["Kırmızı bayrak", true, "Al kırmızı, sancak bayrak demektir."], ["Sabah güneşi", false, "Sabahın ilk aydınlığı “şafak” sözcüğüyle anlatılır."], ["Kahraman asker", false, "Sancak bir kişi değil, bayraktır."], ["Yanan ocak", false, "Ocak sonraki dizede geçer; sancak bayraktır."]] },
      },
      {
        baslik: "Nasıl dinleriz, nasıl izleriz?",
        metin: "Bir video izlerken ya da bir metin dinlerken: <b>1)</b> Başlıktan konuyu <b>tahmin et</b>. <b>2)</b> Dikkatini dağıtan şeyleri uzaklaştır. <b>3)</b> Önemli bilgileri (ad, tarih, yer) kısa kısa <b>not al</b>. <b>4)</b> Sonunda “Asıl ne anlatıldı?” diye <b>ana fikri</b> bul. İstiklâl Marşı okunurken ise <b>hazır ol</b>da durur, konuşmaz, saygıyla dinleriz.",
        ornek: "Not örneği: “Marş – M. Âkif Ersoy – 12 Mart 1921 – 10 kıta.”",
        durak: { soru: "İstiklâl Marşı okunurken aşağıdaki davranışlardan hangisi doğrudur?", secenekler: [["Hazır olda durup saygıyla dinlemek", true, "Millî marşımıza saygı böyle gösterilir."], ["Arkadaşla sohbet etmek", false, "Marş okunurken konuşmak saygısızlıktır."], ["Oturmaya devam etmek", false, "Marş okunurken ayağa kalkılır."], ["Telefonla oynamak", false, "Dikkatimizi tamamen marşa vermeliyiz."]] },
      },
    ],
    uret: {
      "trist.bilgi": [
        Q("trist.bilgi", "hatirlama", 1, "İstiklâl Marşı'nın şairi kimdir?", "Mehmet Âkif Ersoy",
          [["Ziya Gökalp", "bilgi", "Ziya Gökalp de önemli bir yazardır ama marşın şairi değildir."], ["Yunus Emre", "bilgi", "Yunus Emre yüzyıllar önce yaşamış bir halk şairidir."], ["Osman Zeki Üngör", "kavrama", "Osman Zeki Üngör marşın bestecisidir, şairi değildir."]],
          "Şair, sözleri yazan kişidir.",
          ["Soru marşın sözlerini yazan kişiyi soruyor.", "İstiklâl Marşı'nı Mehmet Âkif Ersoy yazmıştır.", "Cevap: Mehmet Âkif Ersoy."],
          { gorsel: IM_BILGI, kural: "Şair sözleri yazar; besteci müziğini yapar. Şair: Mehmet Âkif Ersoy. Besteci: Osman Zeki Üngör." }),
        Q("trist.bilgi", "hatirlama", 1, "İstiklâl Marşı kaç kıtadan oluşur?", "10",
          [["2", "kavrama", "Törenlerde ilk 2 kıta okunur ama marşın tamamı daha uzundur."], ["4", "bilgi", "Marşın kıta sayısı daha fazladır."], ["12", "dikkat", "12, marşın kabul edildiği günün sayısıdır (12 Mart)."]],
          "Törenlerde okunan kısım, marşın yalnızca başıdır.",
          ["Soru marşın tamamındaki kıta sayısını soruyor.", "İstiklâl Marşı 10 kıtadır; törenlerde ilk 2 kıtası okunur.", "Cevap: 10."],
          { gorsel: IM_BILGI, kural: "İstiklâl Marşı 10 kıtadır; törenlerde ilk iki kıtası okunur." }),
        Q("trist.bilgi", "aciklama", 2, "Mehmet Âkif Ersoy, İstiklâl Marşı'nı “Kahraman Ordumuza” ithaf etmiştir. “İthaf etmek” ne demektir?", "Bir eseri birine armağan etmek",
          [["Bir eseri ezberlemek", "kavrama", "Ezberlemek, bir metni akılda tutmaktır."], ["Bir eseri yarışmaya göndermek", "kavrama", "Yarışmaya göndermek ithaf etmek anlamına gelmez."], ["Bir eseri bestelemek", "bilgi", "Bestelemek, sözlere müzik yapmaktır."]],
          "“Kahraman Ordumuza” sözü kime adandığını gösterir.",
          ["Soru “ithaf etmek” sözünün anlamını soruyor.", "Şair, marşını orduya adamış, ona armağan etmiştir.", "Cevap: Bir eseri birine armağan etmek."],
          { kural: "İthaf: bir eseri birine adamak, armağan etmek." }),
        Q("trist.bilgi", "baglanti", 2, "Aşağıdaki olaylardan hangisi İstiklâl Marşı'nın kabulünden <b>önce</b> gerçekleşmiştir?", "TBMM'nin açılması (23 Nisan 1920)",
          [["Cumhuriyet'in ilanı (29 Ekim 1923)", "bilgi", "Cumhuriyet 1923'te ilan edildi; marş 1921'de kabul edilmişti."], ["Büyük Taarruz (26 Ağustos 1922)", "bilgi", "Büyük Taarruz 1922'dedir; marştan sonradır."], ["İzmir'in kurtuluşu (9 Eylül 1922)", "bilgi", "İzmir 1922'de kurtuldu; marştan sonradır."]],
          "Marş 12 Mart 1921'de kabul edildi. Daha eski tarihi bul.",
          ["Önce marşın tarihini hatırla: 12 Mart 1921.", "Seçeneklerdeki yılları karşılaştır: 1920, 1922, 1922, 1923.", "1921'den önceki tek olay: TBMM'nin açılması (1920)."],
          { kural: "Olayları sıralarken önce yıllara, yıllar aynıysa aylara bak." }),
      ],
      "trist.anlam": [
        Q("trist.anlam", "hatirlama", 1, "“İstiklâl” sözcüğünün anlamı nedir?", "Bağımsızlık",
          [["Kahramanlık", "bilgi", "Kahramanlık cesaretle yapılan büyük işlerdir; istiklâl başka bir şeydir."], ["Bayrak", "bilgi", "Bayrak için marşta “sancak” sözcüğü kullanılır."], ["Zafer", "bilgi", "Zafer savaşta kazanılan başarıdır."]],
          "Marşın adı, milletin en büyük amacını anlatır.",
          ["Soru “istiklâl” sözcüğünün anlamını soruyor.", "İstiklâl, bir milletin kimseye bağlı olmadan yaşamasıdır.", "Cevap: Bağımsızlık."],
          { kural: "İstiklâl = bağımsızlık. Hür = özgür. Sancak = bayrak." }),
        Q("trist.anlam", "aciklama", 2, "“Ben ezelden beridir <b>hür</b> yaşadım, <b>hür</b> yaşarım.” dizesinde “hür” sözcüğünün anlamı nedir?", "Özgür",
          [["Mutlu", "kavrama", "Mutlu olmak ile hür olmak farklıdır; hür, kimseye bağlı olmamaktır."], ["Yalnız", "kavrama", "Hür olmak yalnız olmak demek değildir."], ["Zengin", "kavrama", "Hürlük maddi durumla ilgili değildir."]],
          "Bağımsız bir milletin bireyleri nasıl yaşar?",
          ["Soru “hür” sözcüğünün anlamını soruyor.", "Dize, milletin her zaman bağımsız ve özgür yaşadığını anlatıyor.", "Cevap: Özgür."],
          { kural: "Hür: özgür, kimsenin esiri olmayan. Ezel: başlangıcı olmayan geçmiş." }),
        Q("trist.anlam", "uygulama", 2, "“Çatma, kurban olayım, <b>çehreni</b> ey nazlı <b>hilâl</b>!” dizesinde koyu yazılan sözcüklerin anlamları sırasıyla hangisidir?", "yüz – ay",
          [["kaş – yıldız", "kavrama", "Kaş “çatma” sözüyle ilgilidir; hilâl yıldız değil, aydır."], ["yüz – güneş", "bilgi", "Hilâl güneş değil, bayrağımızdaki aydır."], ["ses – bulut", "bilgi", "Çehre yüz demektir; hilâl de aydır."]],
          "Bayrağımızda ay ve yıldız vardır.",
          ["Çehre sözcüğü “yüz” anlamına gelir.", "Hilâl, bayrağımızdaki ay biçimidir.", "Cevap: yüz – ay."],
          { kural: "Çehre: yüz. Hilâl: ince ay biçimi; burada bayrağımızdaki ay. Çatmak: kaşlarını çatmak, kızgın bakmak." }),
        Q("trist.anlam", "aciklama", 2, "“Korkma, sönmez bu şafaklarda yüzen al sancak;” dizesinde şair millete hangi duyguyu vermek istemektedir?", "Umut ve güven",
          [["Korku ve endişe", "kavrama", "Şair “Korkma” diyerek korkuyu gidermek istiyor."], ["Öfke ve kin", "kavrama", "Dizede öfke anlatan bir söz yok."], ["Hüzün ve özlem", "kavrama", "Dize hüzünlü değil, cesaret verici bir seslenmedir."]],
          "Şair “Korkma” diyerek ne yapıyor?",
          ["“Korkma” sözü bir cesaret verme seslenmesidir.", "“Sönmez … al sancak” sözü bayrağın hep dalgalanacağını söyler.", "Şair millete umut ve güven veriyor."],
          { kural: "Şiirdeki seslenmeler (Korkma!, Çatma!) şairin okura vermek istediği duyguyu gösterir." }),
        Q("trist.anlam", "transfer", 3, "Arkadaşın, “Sönmeden yurdumun üstünde tüten en son ocak.” dizesini anlamadığını söyledi. Ona en doğru açıklama hangisidir?", "Yurdumda tek bir ev bile kalsa bayrak sönmeyecek.",
          [["Evlerde ocak yakılmasın.", "kavrama", "Dize gerçek bir ocaktan değil, yurttaki son yuvadan söz ediyor."], ["Yurdumuzda çok soğuk olur.", "kavrama", "Dizede hava durumuyla ilgili bir anlatım yok."], ["Bayrak ocakta yakılmalı.", "kavrama", "Bu, dizenin anlamına tamamen terstir."]],
          "“Tüten ocak” bir evin, bir ailenin yaşadığını gösterir.",
          ["Önceki dize: “Korkma, sönmez … al sancak”.", "“Tüten en son ocak” yurttaki son yuva, son aile demektir.", "Anlamı: Yurdumuzda son bir ev kalana kadar bayrak inmeyecek."],
          { kural: "Şiirde sözcükler çoğu zaman mecaz anlamda kullanılır; “ocak” burada yuva, aile anlamındadır." }),
      ],
      "trist.dinleme": [
        Q("trist.dinleme", "uygulama", 1, "İstiklâl Marşı'nı anlatan bir video izleyeceksin. İzlemeye başlamadan önce yapman gereken en doğru davranış hangisidir?", "Başlığa bakıp konuyu tahmin etmek",
          [["Videoyu hızlı hızlı ileri sarmak", "strateji", "İleri sararsan önemli bilgileri kaçırırsın."], ["Bir yandan oyun oynamak", "strateji", "Başka işle uğraşmak dikkatini dağıtır."], ["Videonun sonunu tahmin etmeden kapatmak", "strateji", "İzlemeden bilgi edinemezsin."]],
          "İzlemeden önce zihnini konuya hazırla.",
          ["İzleme öncesi strateji: başlıktan ve görsellerden tahmin yürütmek.", "Tahmin, dikkatini konuya yöneltir.", "Cevap: Başlığa bakıp konuyu tahmin etmek."],
          { kural: "İzleme öncesi: tahmin et. İzleme sırasında: not al. İzleme sonrası: ana fikri bul." }),
        Q("trist.dinleme", "uygulama", 2, "Bir dinleme metninde not alırken aşağıdakilerden hangisi <b>en doğru</b> not örneğidir?", "M. Âkif Ersoy – 12 Mart 1921 – 10 kıta",
          [["Her duyduğumu kelimesi kelimesine yazmak", "strateji", "Her şeyi yazmaya çalışırsan dinlemeyi kaçırırsın; anahtar bilgileri yaz."], ["Hiç not almamak", "strateji", "Not almazsan önemli bilgileri unutabilirsin."], ["Yalnızca videodaki renkleri yazmak", "strateji", "Renkler ana bilgiyi vermez; ad, tarih, olay gibi bilgileri yaz."]],
          "İyi not kısa ve anahtar bilgilerden oluşur.",
          ["Not almanın amacı önemli bilgileri unutmamaktır.", "Kişi adı, tarih ve sayı gibi anahtar bilgiler kısaca yazılır.", "En doğru not: M. Âkif Ersoy – 12 Mart 1921 – 10 kıta."],
          { kural: "Not alırken kısa yaz: kişi, tarih, yer, sayı ve önemli olaylar." }),
        Q("trist.dinleme", "transfer", 1, "Okul töreninde İstiklâl Marşı okunmaya başladı. Yanındaki arkadaşın sana bir şey sormak istiyor. Ne yapmalısın?", "Marş bitene kadar hazır olda bekleyip sonra konuşmak",
          [["Hemen cevap vermek", "strateji", "Marş okunurken konuşmak saygısızlıktır."], ["Sırayı bozup arkadaşın yanına gitmek", "strateji", "Marş sırasında yerinden ayrılmamalısın."], ["Kulağına fısıldamak", "strateji", "Fısıldamak da konuşmaktır; marş bitene kadar bekle."]],
          "Millî marşa saygı nasıl gösterilir?",
          ["Marş okunurken hazır olda durulur, konuşulmaz.", "Arkadaşının sorusu marş bittikten sonra cevaplanabilir.", "Cevap: Marş bitene kadar hazır olda bekleyip sonra konuşmak."],
          { kural: "İstiklâl Marşı okunurken: ayağa kalk, hazır olda dur, konuşma, bayrağa bak." }),
        Q("trist.dinleme", "aciklama", 2, "İzlediğin bir videonun <b>ana fikrini</b> bulmak için kendine hangi soruyu sormalısın?", "Bu videoda asıl anlatılmak istenen ne?",
          [["Videodaki kişilerin kıyafetleri ne renkti?", "strateji", "Bu bir ayrıntıdır; ana fikri vermez."], ["Video kaç dakika sürdü?", "strateji", "Süre bilgisi videonun mesajını vermez."], ["Videoyu kim yükledi?", "strateji", "Bu bilgi videonun ana fikriyle ilgili değildir."]],
          "Ana fikir, ayrıntı değil, asıl mesajdır.",
          ["Ana fikir, dinlediğimiz ya da izlediğimiz metnin asıl mesajıdır.", "Renk, süre gibi ayrıntılar mesajı vermez.", "Doğru soru: “Bu videoda asıl anlatılmak istenen ne?”"],
          { kural: "Ana fikir = Asıl söylenmek istenen. Ayrıntılar ana fikri destekler." }),
      ],
    },
    oyun: [
      { tur: "eslestir", kaz: "trist.anlam", soru: "İstiklâl Marşı'ndaki sözcükleri anlamlarıyla eşleştir.", ciftler: [["istiklâl", "bağımsızlık"], ["hür", "özgür"], ["sancak", "bayrak"], ["çehre", "yüz"]], aciklama: "İstiklâl bağımsızlık, hür özgür, sancak bayrak, çehre yüz demektir." },
      { tur: "eslestir", kaz: "trist.bilgi", soru: "İstiklâl Marşı bilgilerini eşleştir.", ciftler: [["Şairi", "Mehmet Âkif Ersoy"], ["Kabul tarihi", "12 Mart 1921"], ["Kıta sayısı", "10"], ["İthaf edildiği yer", "Kahraman Ordumuz"]], aciklama: "Mehmet Âkif Ersoy'un yazdığı 10 kıtalık marş, 12 Mart 1921'de kabul edildi ve Kahraman Ordumuza ithaf edildi." },
      { tur: "sirala", kaz: "trist.dinleme", soru: "Bir videoyu izlerken uygulayacağın adımları doğru sıraya koy.", ogeler: ["Başlığa bakıp konuyu tahmin et.", "Dikkatini dağıtan şeyleri uzaklaştır.", "İzlerken önemli bilgileri not al.", "Notlarına bakarak ana fikri bul."], aciklama: "Önce tahmin, sonra hazırlık, izlerken not alma ve en sonda ana fikri bulma." },
      { tur: "uret", kaz: "trist.anlam", soru: "İSTİKLAL harfleriyle en az 3 anlamlı kelime üret.", harfler: "İSTİKLAL", kelimeler: ["istiklal", "lastikli", "lastik", "tilki", "silik", "ilik", "asil", "atik", "salt", "ilk", "kil", "sil", "kal", "kas", "kat", "tak", "tas", "sat", "sal", "lal", "il", "it", "is", "al", "at", "as", "ak"], hedef: 3, aciklama: "Lastik, tilki, silik, ilk, kil, kas, tas… Birçok kelime saklı!" },
    ],
  });

  /* =============================== 4. 1071'den 1922'ye Tek Millet İki Zafer =============================== */
  const IKI_ZAFER = G.tablo(["", "Malazgirt Meydan Muharebesi", "Büyük Taarruz"], [["Başlangıç", "26 Ağustos 1071", "26 Ağustos 1922"], ["Komutan", "Sultan Alparslan", "Başkomutan Mustafa Kemal Paşa"], ["Karşı taraf", "Bizans (İmparator Romen Diyojen)", "Yunan ordusu"], ["Sonuç", "Anadolu'nun kapıları Türklere açıldı.", "Anadolu düşmandan kurtarıldı."]]);
  const TAARRUZ = "<i>Büyük Taarruz, 26 Ağustos 1922 sabahı Kocatepe'den başladı. Türk ordusu önce düşman hatlarını yardı. Ardından 30 Ağustos'ta Başkomutanlık Meydan Muharebesi kazanıldı. Bu zaferden sonra Mustafa Kemal Paşa, 1 Eylül'de “Ordular! İlk hedefiniz Akdeniz'dir. İleri!” emrini verdi. Sonunda 9 Eylül 1922'de İzmir düşmandan kurtarıldı.</i>";
  KONU_EKLE("tr", {
    id: "tr_zafer", tema: "tr2", ad: "1071'den 1922'ye Tek Millet İki Zafer", sayfa: "s. 100", gorev: "Olayları doğru sıraya koyma",
    kazanimlar: [
      { id: "trzaf.sira", ad: "Olayları oluş sırasına koyma ve zaman ifadelerini belirleme" },
      { id: "trzaf.bilgi", ad: "Bilgilendirici metnin özelliklerini tanıma ve metinden bilgi bulma" },
      { id: "trzaf.sebep", ad: "Olaylar arasındaki sebep–sonuç ilişkisini belirleme" },
    ],
    anlatim: [
      {
        baslik: "İki zafer, bir tarih: 26 Ağustos",
        metin: "<b>26 Ağustos 1071</b>'de Sultan Alparslan komutasındaki Selçuklu ordusu, Malazgirt'te Bizans ordusunu yendi. Bu zaferle <b>Anadolu'nun kapıları Türklere açıldı</b>. Tam 851 yıl sonra, <b>26 Ağustos 1922</b>'de Mustafa Kemal Paşa'nın yönettiği <b>Büyük Taarruz</b> başladı ve <b>30 Ağustos</b>'ta Başkomutanlık Meydan Muharebesi kazanıldı. Her iki zafer de aynı gün başladığı için “Tek Millet İki Zafer” denir.",
        ornek: "30 Ağustos her yıl Zafer Bayramı olarak kutlanır.",
        durak: { soru: "Malazgirt Meydan Muharebesi ile Büyük Taarruz'un ortak özelliği hangisidir?", secenekler: [["İkisi de 26 Ağustos'ta başlamıştır.", true, "Biri 1071'de, diğeri 1922'de aynı gün başlamıştır."], ["İkisi de aynı yıl olmuştur.", false, "Aralarında 851 yıl vardır."], ["İkisini de Alparslan yönetmiştir.", false, "Büyük Taarruz'u Mustafa Kemal Paşa yönetmiştir."], ["İkisi de İzmir'de olmuştur.", false, "Malazgirt Doğu Anadolu'da, Büyük Taarruz ise Afyonkarahisar çevresinde başlamıştır."]] },
      },
      {
        baslik: "Olay sırası ve zaman ifadeleri",
        metin: "Olayları anlatırken onları <b>oluş sırasına</b> göre dizeriz. Bunun için <b>zaman ifadeleri</b> kullanırız: <b>önce, ilk olarak, ardından, sonra, daha sonra, en sonunda, ertesi gün</b>… Tarih verilmişse önce yıla, yıl aynıysa aya, ay da aynıysa güne bakarız.",
        ornek: "Önce 26 Ağustos'ta taarruz başladı, ardından 30 Ağustos'ta zafer kazanıldı, en sonunda 9 Eylül'de İzmir kurtarıldı.",
        durak: { soru: "Aşağıdakilerden hangisi bir <b>zaman ifadesi</b> değildir?", secenekler: [["Kocatepe'de", true, "Bu bir yer bildirir."], ["Ardından", false, "Ardından, olayların sırasını gösteren bir zaman ifadesidir."], ["En sonunda", false, "En sonunda, son olayı gösteren bir zaman ifadesidir."], ["Ertesi gün", false, "Ertesi gün, bir zaman ifadesidir."]] },
      },
      {
        baslik: "Bilgilendirici metin ve sebep–sonuç",
        metin: "<b>Bilgilendirici metin</b>, bir konu hakkında bilgi vermek için yazılır. Tarih, sayı, ad gibi <b>kanıtlanabilir bilgiler</b> içerir; dili açık ve <b>nesneldir</b>. Bu metinlerde olayların <b>sebebi</b> (neden oldu?) ve <b>sonucu</b> (ne oldu?) sık sık anlatılır. “Bu yüzden, bu nedenle, -dığı için, sonucunda” sözleri sebep–sonuç ilişkisini gösterir.",
        ornek: "Malazgirt zaferi kazanıldığı için (sebep) Türkler Anadolu'ya yerleşmeye başladı (sonuç).",
        durak: { soru: "“Ordu iyi hazırlandığı için taarruz başarıyla sonuçlandı.” cümlesinde <b>sebep</b> hangisidir?", secenekler: [["Ordunun iyi hazırlanması", true, "“-dığı için” sebebi gösterir."], ["Taarruzun başarıyla sonuçlanması", false, "Bu, sonuçtur."], ["Taarruzun başlaması", false, "Cümlede başlamaktan söz edilmiyor."], ["Ordunun dinlenmesi", false, "Cümlede böyle bir bilgi yok."]] },
      },
    ],
    uret: {
      "trzaf.sira": [
        Q("trzaf.sira", "hatirlama", 1, TAARRUZ + "<br><br>Metne göre aşağıdaki olaylardan hangisi <b>en son</b> gerçekleşmiştir?", "İzmir'in kurtarılması",
          [["Taarruzun Kocatepe'den başlaması", "dikkat", "Bu, metindeki ilk olaydır."], ["Başkomutanlık Meydan Muharebesi'nin kazanılması", "dikkat", "Bu, 30 Ağustos'ta oldu; daha sonra başka olaylar var."], ["“Ordular! İlk hedefiniz Akdeniz'dir.” emrinin verilmesi", "dikkat", "Bu emir 1 Eylül'de verildi; İzmir 9 Eylül'de kurtarıldı."]],
          "“Sonunda” sözcüğüyle başlayan cümleye bak.",
          ["Olayların tarihlerini sırala: 26 Ağustos, 30 Ağustos, 1 Eylül, 9 Eylül.", "En geç tarih 9 Eylül 1922'dir.", "En son olay: İzmir'in kurtarılması."],
          { kural: "“Sonunda, en sonunda, son olarak” ifadeleri son olayı gösterir." }),
        Q("trzaf.sira", "uygulama", 2, "Aşağıdaki olaylar oluş sırasına göre dizilirse <b>ikinci</b> sırada hangisi yer alır?<br>• Büyük Taarruz (1922)<br>• Malazgirt Meydan Muharebesi (1071)<br>• Cumhuriyet'in ilanı (1923)<br>• TBMM'nin açılması (1920)", "TBMM'nin açılması",
          [["Malazgirt Meydan Muharebesi", "dikkat", "Bu, en eski olaydır; birinci sıradadır."], ["Büyük Taarruz", "islem", "1922, 1920'den sonra gelir; Büyük Taarruz üçüncü sıradadır."], ["Cumhuriyet'in ilanı", "islem", "1923 en yeni tarihtir; son sıradadır."]],
          "Yılları küçükten büyüğe sırala.",
          ["Yıllar: 1071, 1920, 1922, 1923.", "Sıralama: Malazgirt → TBMM → Büyük Taarruz → Cumhuriyet.", "İkinci sırada: TBMM'nin açılması."],
          { kural: "Tarihî olayları sıralarken yılları küçükten büyüğe diz." }),
        Q("trzaf.sira", "uygulama", 2, "“Askerler <b>önce</b> mevzilerine yerleşti, <b>ardından</b> sabahı beklediler.” cümlesinde koyu yazılan sözcüklerin görevi nedir?", "Olayların sırasını göstermek",
          [["Olayın yerini göstermek", "kavrama", "Yer bildiren sözcükler “nerede?” sorusuna cevap verir."], ["Olayın sebebini göstermek", "kavrama", "Sebep “neden?” sorusuna cevap verir; bu sözcükler sıra bildirir."], ["Kişilerin duygusunu göstermek", "kavrama", "Bu sözcükler duygu bildirmez."]],
          "“Önce” ve “ardından” hangi olayın ilk, hangisinin sonra olduğunu söyler.",
          ["Sözcüklerin anlamına bak: önce, ardından.", "Bu sözcükler olayları zaman sırasına koyar.", "Görevleri: Olayların sırasını göstermek."],
          { kural: "Zaman ifadeleri: önce, ilk olarak, ardından, sonra, daha sonra, en sonunda." }),
        Q("trzaf.sira", "transfer", 2, "Zafer Bayramı töreni için bir program hazırlıyorsun. Aşağıdaki sıralamalardan hangisi tören düzenine <b>en uygundur</b>?", "Saygı duruşu ve İstiklâl Marşı → Konuşma → Şiirler → Kapanış",
          [["Kapanış → Şiirler → Konuşma → İstiklâl Marşı", "dikkat", "Kapanış en sonda olmalı; tören saygı duruşu ve marşla açılır."], ["Şiirler → Kapanış → İstiklâl Marşı → Konuşma", "dikkat", "Kapanıştan sonra başka bölüm gelmez."], ["Konuşma → Kapanış → Şiirler → Saygı duruşu", "dikkat", "Saygı duruşu ve marş törenin başında yapılır."]],
          "Bir tören nasıl açılır, nasıl kapanır?",
          ["Törenler saygı duruşu ve İstiklâl Marşı ile başlar.", "Ardından günün anlam ve önemiyle ilgili konuşma ve şiirler gelir.", "En sonda kapanış yapılır."],
          { kural: "Bir işi planlarken adımları mantıklı sıraya koy: başlangıç → gelişme → sonuç." }),
        Q("trzaf.sira", "baglanti", 3, "1. temada öğrendiğin <b>zaman</b> unsuru gibi, olayları sıralamak için tarihlere bakarız. Aşağıdaki tarihlerden hangisi <b>en eskidir</b>?", "26 Ağustos 1071",
          [["19 Mayıs 1919", "islem", "1919, 1071'den çok sonradır."], ["12 Mart 1921", "islem", "1921, 1071'den çok sonradır."], ["30 Ağustos 1922", "dikkat", "Ay ve gün benzer ama yıl 1922'dir; 1071 çok daha eskidir."]],
          "Önce yılları karşılaştır.",
          ["Yıllar: 1071, 1919, 1921, 1922.", "En küçük yıl en eski olaydır.", "Cevap: 26 Ağustos 1071."],
          { kural: "Yıl küçüldükçe olay daha eskidir." }),
      ],
      "trzaf.bilgi": [
        Q("trzaf.bilgi", "hatirlama", 1, "Malazgirt Meydan Muharebesi'nde Türk ordusunun komutanı kimdir?", "Sultan Alparslan",
          [["Mustafa Kemal Paşa", "bilgi", "Mustafa Kemal Paşa, 1922'deki Büyük Taarruz'u yönetmiştir."], ["Romen Diyojen", "kavrama", "Romen Diyojen, karşı taraftaki Bizans imparatorudur."], ["Fatih Sultan Mehmet", "bilgi", "Fatih, 1453'te İstanbul'u fethetmiştir."]],
          "Tablodaki “Komutan” satırına bak.",
          ["Soru 1071'deki Türk komutanını soruyor.", "Malazgirt'te Selçuklu ordusunu Sultan Alparslan yönetti.", "Cevap: Sultan Alparslan."],
          { gorsel: IKI_ZAFER, kural: "1071 Malazgirt: Sultan Alparslan. 1922 Büyük Taarruz: Mustafa Kemal Paşa." }),
        Q("trzaf.bilgi", "aciklama", 2, "Aşağıdakilerden hangisi <b>bilgilendirici metnin</b> özelliklerinden biri değildir?", "Hayal ürünü olaylar ve kişiler anlatır.",
          [["Tarih, sayı gibi kanıtlanabilir bilgiler içerir.", "kavrama", "Bu, bilgilendirici metnin özelliğidir."], ["Dili açık ve anlaşılırdır.", "kavrama", "Bilgilendirici metinler açık bir dille yazılır."], ["Okuru bir konuda bilgilendirmeyi amaçlar.", "kavrama", "Bu, bilgilendirici metnin temel amacıdır."]],
          "Hayal ürünü olaylar hangi metin türlerinde olur?",
          ["Bilgilendirici metin gerçek bilgileri aktarır.", "Hayal ürünü olay ve kişiler hikâye, masal gibi türlerde bulunur.", "Cevap: Hayal ürünü olaylar ve kişiler anlatır."],
          { kural: "Bilgilendirici metin: gerçek, kanıtlanabilir bilgi; açık dil; amaç bilgi vermek." }),
        Q("trzaf.bilgi", "uygulama", 2, "Aşağıdaki cümlelerden hangisi <b>nesnel</b> (kanıtlanabilir) bir bilgidir?", "Malazgirt Meydan Muharebesi 1071 yılında yapılmıştır.",
          [["Büyük Taarruz, tarihin en heyecanlı olayıdır.", "kavrama", "“En heyecanlı” kişisel bir yorumdur; kanıtlanamaz."], ["Zafer Bayramı en güzel bayramdır.", "kavrama", "“En güzel” kişiden kişiye değişen bir görüştür."], ["Alparslan çok sevimli bir komutandı.", "kavrama", "“Sevimli” bir yorumdur; nesnel değildir."]],
          "Herkesin kabul edeceği, kanıtlanabilen cümleyi bul.",
          ["Nesnel yargı kanıtlanabilir, kişiye göre değişmez.", "Tarih bilgisi belgelerle kanıtlanabilir.", "Cevap: Malazgirt Meydan Muharebesi 1071 yılında yapılmıştır."],
          { kural: "Nesnel yargı: kanıtlanabilir. Öznel yargı: kişisel görüş (güzel, en iyi, heyecanlı…)." }),
        Q("trzaf.bilgi", "uygulama", 2, TAARRUZ + "<br><br>Metne göre Büyük Taarruz nereden başlamıştır?", "Kocatepe'den",
          [["İzmir'den", "dikkat", "İzmir, taarruzun sonunda kurtarılan yerdir."], ["Malazgirt'ten", "dikkat", "Malazgirt, 1071'deki zaferin yeridir."], ["Akdeniz'den", "dikkat", "Akdeniz, orduya gösterilen hedeftir; başlangıç yeri değildir."]],
          "İlk cümleyi oku.",
          ["Soru başlangıç yerini soruyor.", "İlk cümle: “26 Ağustos 1922 sabahı Kocatepe'den başladı.”", "Cevap: Kocatepe'den."],
          { kural: "Bilgi sorularında cevabı metinde ara; tahminle cevap verme." }),
      ],
      "trzaf.sebep": [
        Q("trzaf.sebep", "aciklama", 2, "Malazgirt zaferinin en önemli <b>sonucu</b> hangisidir?", "Anadolu'nun kapıları Türklere açıldı.",
          [["İzmir düşmandan kurtarıldı.", "bilgi", "Bu, 1922'deki Büyük Taarruz'un sonucudur."], ["TBMM açıldı.", "bilgi", "TBMM 1920'de açılmıştır; Malazgirt'in sonucu değildir."], ["İstiklâl Marşı kabul edildi.", "bilgi", "Marş 1921'de kabul edildi; Malazgirt'le ilgisi yoktur."]],
          "1071'de ne değişti? Tabloya bak.",
          ["Soru Malazgirt'in sonucunu soruyor.", "Zaferden sonra Türkler Anadolu'ya yerleşmeye başladı.", "Cevap: Anadolu'nun kapıları Türklere açıldı."],
          { gorsel: IKI_ZAFER, kural: "Sonuç: bir olayın ardından ortaya çıkan durumdur. “Ne oldu?” sorusuna cevap verir." }),
        Q("trzaf.sebep", "uygulama", 2, "“Yollar çamurlu olduğu için cephane kağnılarla taşındı.” cümlesinde <b>sonuç</b> hangisidir?", "Cephanenin kağnılarla taşınması",
          [["Yolların çamurlu olması", "kavrama", "“-duğu için” bu kısmı sebep yapar."], ["Kağnıların bozulması", "dikkat", "Cümlede kağnıların bozulduğu söylenmiyor."], ["Cephanenin bitmesi", "dikkat", "Cümlede böyle bir bilgi yok."]],
          "“-duğu için” sözünden önceki kısım sebeptir.",
          ["Sebep: Yollar çamurlu olduğu için.", "Bu sebebin doğurduğu durum: cephane kağnılarla taşındı.", "Sonuç: Cephanenin kağnılarla taşınması."],
          { kural: "“için, -dığı için, bu yüzden, bu nedenle” sözleri sebep–sonuç ilişkisi kurar." }),
        Q("trzaf.sebep", "uygulama", 2, "Aşağıdaki cümlelerin hangisinde <b>sebep–sonuç</b> ilişkisi vardır?", "Zafer kazanıldığı için halk sokaklara döküldü.",
          [["Askerler sabah erkenden yola çıktı.", "kavrama", "Bu cümlede yalnızca zaman bilgisi var, sebep yok."], ["Kocatepe, Afyonkarahisar yakınlarındadır.", "kavrama", "Bu cümle bir yer bilgisi verir."], ["Bayrak rüzgârda dalgalanıyordu.", "kavrama", "Bu cümle bir durumu anlatır; sebep bildirilmiyor."]],
          "“için, bu yüzden, -dığı için” gibi sözleri ara.",
          ["Sebep–sonuç cümlesinde bir olay diğerinin nedenidir.", "“Zafer kazanıldığı için” sebep, “halk sokaklara döküldü” sonuçtur.", "Cevap: Zafer kazanıldığı için halk sokaklara döküldü."],
          { kural: "Sebep–sonuç cümlesinde “Neden?” sorusunun cevabı cümlenin içinde bulunur." }),
        Q("trzaf.sebep", "transfer", 3, "Bir arkadaşın, “30 Ağustos neden bayram olarak kutlanıyor?” diye sordu. En doğru cevap hangisidir?", "Çünkü 30 Ağustos 1922'de Başkomutanlık Meydan Muharebesi kazanıldı.",
          [["Çünkü o gün Cumhuriyet ilan edildi.", "bilgi", "Cumhuriyet 29 Ekim 1923'te ilan edildi."], ["Çünkü o gün TBMM açıldı.", "bilgi", "TBMM 23 Nisan 1920'de açıldı."], ["Çünkü o gün Malazgirt Muharebesi bitti.", "bilgi", "Malazgirt Muharebesi 26 Ağustos 1071'de yapıldı; bayramın sebebi 1922'deki zaferdir."]],
          "Zafer Bayramı hangi zaferi kutlar?",
          ["Soru bayramın sebebini soruyor.", "30 Ağustos 1922'de Başkomutanlık Meydan Muharebesi kazanıldı.", "Bu yüzden 30 Ağustos Zafer Bayramı olarak kutlanır."],
          { kural: "Sebep sorusuna “Çünkü …” diye başlayan bir cümleyle cevap verebilirsin." }),
      ],
    },
    oyun: [
      { tur: "sirala", kaz: "trzaf.sira", soru: "Büyük Taarruz'un olaylarını oluş sırasına göre diz.", ogeler: ["Taarruz Kocatepe'den başladı (26 Ağustos 1922).", "Başkomutanlık Meydan Muharebesi kazanıldı (30 Ağustos 1922).", "“Ordular! İlk hedefiniz Akdeniz'dir. İleri!” emri verildi (1 Eylül 1922).", "İzmir düşmandan kurtarıldı (9 Eylül 1922)."], aciklama: "Taarruz 26 Ağustos'ta başladı, 30 Ağustos'ta zafer kazanıldı, 1 Eylül'de Akdeniz emri verildi, 9 Eylül'de İzmir kurtarıldı." },
      { tur: "sirala", kaz: "trzaf.sira", soru: "Tarihî olayları eskiden yeniye doğru sırala.", ogeler: ["Malazgirt Meydan Muharebesi (1071)", "Mustafa Kemal Paşa'nın Samsun'a çıkışı (1919)", "TBMM'nin açılması (1920)", "Büyük Taarruz (1922)", "Cumhuriyet'in ilanı (1923)"], aciklama: "Yılları küçükten büyüğe dizersen doğru sıraya ulaşırsın: 1071, 1919, 1920, 1922, 1923." },
      { tur: "sirala", kaz: "trzaf.sira", soru: "Zaman ifadelerini olay anlatımındaki doğru sıraya koy.", ogeler: ["İlk olarak", "Ardından", "Daha sonra", "En sonunda"], aciklama: "Anlatım “İlk olarak” ile başlar, “Ardından” ve “Daha sonra” ile sürer, “En sonunda” ile biter." },
      { tur: "eslestir", kaz: "trzaf.sebep", soru: "Sebepleri sonuçlarıyla eşleştir.", ciftler: [["Malazgirt zaferi kazanıldı.", "Anadolu'nun kapıları Türklere açıldı."], ["Başkomutanlık Meydan Muharebesi kazanıldı.", "30 Ağustos Zafer Bayramı oldu."], ["Yollar çamurluydu.", "Cephane kağnılarla taşındı."]], aciklama: "Her sebep bir sonucu doğurur. Sebep “Neden?”, sonuç “Ne oldu?” sorusuna cevap verir." },
    ],
  });

  /* =============================== 5. Mustafa Kemal Paşa'nın Samsun'a Çıkışı =============================== */
  const MM_TABLO = G.tablo(["Tarih", "Olay"], [["16 Mayıs 1919", "Bandırma Vapuru ile İstanbul'dan ayrılış"], ["19 Mayıs 1919", "Samsun'a çıkış"], ["22 Haziran 1919", "Amasya Genelgesi"], ["23 Temmuz 1919", "Erzurum Kongresi'nin başlaması"], ["4 Eylül 1919", "Sivas Kongresi'nin başlaması"], ["23 Nisan 1920", "TBMM'nin açılması"]]);
  const ANI = "<i>O sabah babamla birlikte iskeleye koştuk. Liman insanlarla doluydu. Uzaktan bir vapurun yaklaştığını gördüm. Babam elimi sıkıca tutup “Bugünü hiç unutma oğlum.” dedi. Aradan yıllar geçti ama o sabahın heyecanını hâlâ hatırlıyorum.</i>";
  const BIYOGRAFI = "<i>Mustafa Kemal, 1881 yılında Selanik'te doğdu. Askerî okullarda okudu. Çanakkale Savaşı'nda gösterdiği başarıyla tanındı. 19 Mayıs 1919'da Samsun'a çıkarak Millî Mücadele'yi başlattı. Kurtuluş Savaşı'nı yönetti ve Türkiye Cumhuriyeti'ni kurdu.</i>";
  KONU_EKLE("tr", {
    id: "tr_samsun", tema: "tr2", ad: "Mustafa Kemal Paşa'nın Samsun'a Çıkışı (Okumak Gibisi Yok!)", sayfa: "s. 109", gorev: "Olay ve metin eşleştirme",
    kazanimlar: [
      { id: "trsam.tarih", ad: "Millî Mücadele'nin başlangıç olaylarını tarihleriyle eşleştirme" },
      { id: "trsam.tur", ad: "Anı ve biyografi (yaşam öyküsü) türlerini tanıma ve ayırt etme" },
      { id: "trsam.okuma", ad: "Okuduğu metinden bilgi çıkarma ve metni uygun başlıkla eşleştirme" },
    ],
    anlatim: [
      {
        baslik: "19 Mayıs 1919: Bir yolculuk başlıyor",
        metin: "Mustafa Kemal Paşa, <b>16 Mayıs 1919</b>'da <b>Bandırma Vapuru</b> ile İstanbul'dan yola çıktı ve <b>19 Mayıs 1919</b>'da <b>Samsun</b>'a ulaştı. Bu tarih, <b>Millî Mücadele</b>'nin, yani Kurtuluş Savaşı'nın başlangıcı kabul edilir. Ardından Amasya Genelgesi yayımlandı; Erzurum ve Sivas kongreleri toplandı. <b>23 Nisan 1920</b>'de de TBMM açıldı.",
        ornek: "19 Mayıs her yıl “Atatürk'ü Anma, Gençlik ve Spor Bayramı” olarak kutlanır.",
        durak: { soru: "Mustafa Kemal Paşa Samsun'a hangi vapurla gitmiştir?", secenekler: [["Bandırma Vapuru", true, "16 Mayıs 1919'da İstanbul'dan Bandırma Vapuru ile ayrıldı."], ["Samsun Vapuru", false, "Samsun, vapurun gittiği şehrin adıdır."], ["Kocatepe Vapuru", false, "Kocatepe, Büyük Taarruz'un başladığı yerdir."], ["Erzurum Vapuru", false, "Erzurum, kongrenin toplandığı şehirdir."]] },
      },
      {
        baslik: "Anı mı, biyografi mi?",
        metin: "<b>Anı</b>, yazarın kendi yaşadığı ya da tanık olduğu olayları anlattığı yazıdır; genellikle “ben, biz” diye yazılır (birinci kişi). <b>Biyografi</b> (yaşam öyküsü) ise tanınmış bir kişinin hayatının <b>başka biri tarafından</b> anlatılmasıdır; “o” diye yazılır (üçüncü kişi). Kişi kendi hayatını kendisi yazarsa buna <b>otobiyografi</b> denir. Hepsinde gerçek olaylar anlatılır.",
        ornek: "“O gün limana koştuk…” → anı. “Mustafa Kemal 1881'de Selanik'te doğdu…” → biyografi.",
        durak: { soru: "Tanınmış bir kişinin hayatını başka birinin anlattığı yazı türü hangisidir?", secenekler: [["Biyografi", true, "Biyografi, bir kişinin hayatının başkası tarafından anlatılmasıdır."], ["Anı", false, "Anıda yazar kendi yaşadıklarını anlatır."], ["Şiir", false, "Şiir dizelerle yazılır; hayat öyküsü türü değildir."], ["Masal", false, "Masal hayal ürünüdür; gerçek bir hayatı anlatmaz."]] },
      },
      {
        baslik: "Metinle başlığı, olayla tarihi eşleştir",
        metin: "Bir metni okuduktan sonra ona <b>uygun başlığı</b> bulmak, metni anladığını gösterir. Başlık metnin <b>konusunu</b> ya da <b>ana fikrini</b> yansıtır. Tarihî metinlerde ise olayları <b>tarihleriyle</b> eşleştirmek için bir <b>tablo</b> ya da <b>zaman şeridi</b> hazırlamak çok işe yarar.",
        ornek: "Zaman şeridi: 19 Mayıs 1919 Samsun → 22 Haziran 1919 Amasya → 23 Nisan 1920 TBMM.",
        durak: { soru: "Mustafa Kemal'in doğumundan Cumhuriyet'in kuruluşuna kadar hayatını anlatan bir metne en uygun başlık hangisidir?", secenekler: [["Bir Önderin Hayatı", true, "Metin bir kişinin hayat öyküsünü anlatıyor."], ["Yaz Tatilim", false, "Bu başlık metnin konusuyla ilgisizdir."], ["Karadeniz'in Balıkları", false, "Metin balıklarla ilgili değildir."], ["Okul Bahçesinde Bir Gün", false, "Metin okulda geçen bir günü anlatmıyor."]] },
      },
    ],
    uret: {
      "trsam.tarih": [
        Q("trsam.tarih", "hatirlama", 1, "Mustafa Kemal Paşa Samsun'a hangi tarihte çıkmıştır?", "19 Mayıs 1919",
          [["16 Mayıs 1919", "dikkat", "16 Mayıs, İstanbul'dan ayrıldığı tarihtir."], ["23 Nisan 1920", "bilgi", "Bu, TBMM'nin açıldığı tarihtir."], ["30 Ağustos 1922", "bilgi", "Bu, Başkomutanlık Meydan Muharebesi'nin kazanıldığı tarihtir."]],
          "Gençlik ve Spor Bayramı hangi gün kutlanır?",
          ["Soru Samsun'a çıkış tarihini soruyor.", "Bu tarih her yıl Gençlik ve Spor Bayramı olarak kutlanır.", "Cevap: 19 Mayıs 1919."],
          { gorsel: MM_TABLO, kural: "19 Mayıs 1919: Samsun'a çıkış, Millî Mücadele'nin başlangıcı." }),
        Q("trsam.tarih", "aciklama", 2, "19 Mayıs 1919 neden önemli bir tarihtir?", "Millî Mücadele'nin başlangıcı kabul edildiği için",
          [["Cumhuriyet o gün ilan edildiği için", "bilgi", "Cumhuriyet 29 Ekim 1923'te ilan edildi."], ["İstiklâl Marşı o gün kabul edildiği için", "bilgi", "İstiklâl Marşı 12 Mart 1921'de kabul edildi."], ["Kurtuluş Savaşı o gün bittiği için", "kavrama", "19 Mayıs bir başlangıçtır, bitiş değildir."]],
          "Samsun'a çıkış bir sonun mu, başlangıcın mı adıdır?",
          ["Mustafa Kemal Paşa Samsun'dan Anadolu'ya geçerek halkı örgütlemeye başladı.", "Bu yüzden 19 Mayıs 1919, Millî Mücadele'nin başlangıcı sayılır.", "Cevap: Millî Mücadele'nin başlangıcı kabul edildiği için."],
          { kural: "19 Mayıs 1919 başlangıç, 30 Ağustos 1922 büyük zafer, 29 Ekim 1923 Cumhuriyet." }),
        Q("trsam.tarih", "uygulama", 2, "Tabloya göre aşağıdaki eşleştirmelerden hangisi <b>yanlıştır</b>?", "Sivas Kongresi – 19 Mayıs 1919",
          [["Amasya Genelgesi – 22 Haziran 1919", "dikkat", "Bu eşleştirme tabloyla uyumludur."], ["TBMM'nin açılması – 23 Nisan 1920", "dikkat", "Bu eşleştirme doğrudur."], ["İstanbul'dan ayrılış – 16 Mayıs 1919", "dikkat", "Bu eşleştirme doğrudur."]],
          "Her olayı tablodaki tarihiyle karşılaştır.",
          ["Tabloda Sivas Kongresi'nin tarihi 4 Eylül 1919'dur.", "19 Mayıs 1919 ise Samsun'a çıkış tarihidir.", "Yanlış eşleştirme: Sivas Kongresi – 19 Mayıs 1919."],
          { gorsel: MM_TABLO, kural: "Tablo okurken satırı soldan sağa izle: tarih → olay." }),
        Q("trsam.tarih", "baglanti", 2, "Samsun'a çıkıştan sonra gerçekleşen olaylardan hangisi aynı temadaki “İstiklâl Marşı” konusuyla ilgilidir?", "12 Mart 1921'de marşın TBMM'de kabul edilmesi",
          [["1071'de Malazgirt zaferinin kazanılması", "bilgi", "Malazgirt, Samsun'a çıkıştan çok önce olmuştur ve marşla ilgili değildir."], ["16 Mayıs 1919'da İstanbul'dan ayrılış", "dikkat", "Bu olay Samsun'a çıkıştan öncedir."], ["4 Eylül 1919'da Sivas Kongresi", "bilgi", "Sivas Kongresi marşın kabulüyle ilgili değildir."]],
          "İstiklâl Marşı hangi tarihte kabul edilmişti?",
          ["Soru, Samsun'dan sonra olan ve marşla ilgili olayı soruyor.", "İstiklâl Marşı 12 Mart 1921'de TBMM'de kabul edildi; bu, 1919'dan sonradır.", "Cevap: 12 Mart 1921'de marşın TBMM'de kabul edilmesi."],
          { kural: "Millî Mücadele sırası: Samsun (1919) → TBMM (1920) → İstiklâl Marşı (1921) → Büyük Taarruz (1922) → Cumhuriyet (1923)." }),
      ],
      "trsam.tur": [
        Q("trsam.tur", "aciklama", 1, ANI + "<br><br>Bu metin hangi türe örnektir?", "Anı",
          [["Biyografi", "kavrama", "Biyografide başka birinin hayatı “o” diye anlatılır; burada yazar kendi yaşadığını anlatıyor."], ["Masal", "kavrama", "Masal hayal ürünüdür; bu metinde yaşanmış bir an anlatılıyor."], ["Şiir", "kavrama", "Metin dizelerle değil, düz yazıyla yazılmıştır."]],
          "Metni anlatan kişi kim? “Ben” mi, “o” mu?",
          ["Metin “koştuk, gördüm, hatırlıyorum” gibi birinci kişi anlatımıyla yazılmış.", "Yazar kendi yaşadığı bir olayı yıllar sonra anlatıyor.", "Tür: Anı."],
          { kural: "Anı: yazarın kendi yaşadığı ya da tanık olduğu gerçek olaylar; birinci kişi (ben, biz)." }),
        Q("trsam.tur", "aciklama", 2, BIYOGRAFI + "<br><br>Bu metin hangi türe örnektir?", "Biyografi",
          [["Anı", "kavrama", "Anıda yazar kendi yaşadığını anlatır; burada başka birinin hayatı anlatılıyor."], ["Otobiyografi", "kavrama", "Otobiyografide kişi kendi hayatını “ben” diye anlatır."], ["Hikâye", "kavrama", "Hikâyede olaylar hayal ürünü olabilir; burada gerçek bir hayat öyküsü anlatılıyor."]],
          "Metin bir kişinin hayatını kimin ağzından anlatıyor?",
          ["Metinde “doğdu, okudu, tanındı” gibi üçüncü kişi anlatımı var.", "Tanınmış bir kişinin hayatı başka biri tarafından anlatılıyor.", "Tür: Biyografi."],
          { kural: "Biyografi: tanınmış bir kişinin hayatının başkası tarafından anlatılması; üçüncü kişi (o)." }),
        Q("trsam.tur", "uygulama", 2, "Aşağıdaki cümlelerden hangisi bir <b>anıdan</b> alınmış olabilir?", "Çocukken dedemle 19 Mayıs törenine gittiğimizi hiç unutmam.",
          [["Mustafa Kemal 1881'de Selanik'te doğdu.", "kavrama", "Bu cümle başka birinin hayatını anlatır; biyografiye uygundur."], ["Samsun, Karadeniz kıyısında bir şehirdir.", "kavrama", "Bu cümle bilgi verir; kişisel bir yaşantı anlatmaz."], ["Bir varmış bir yokmuş, uzak bir ülkede bir kral yaşarmış.", "kavrama", "Bu, masal tekerlemesidir."]],
          "Yazarın kendi yaşadığını anlatan cümleyi bul.",
          ["Anıda yazar “ben” diye kendi yaşantısını anlatır.", "“Dedemle törene gittiğimizi hiç unutmam” cümlesi kişisel bir yaşantıdır.", "Cevap: Çocukken dedemle 19 Mayıs törenine gittiğimizi hiç unutmam."],
          { kural: "Anıyı tanımak için “ben, biz” anlatımına ve geçmişte yaşanmış gerçek olaylara bak." }),
        Q("trsam.tur", "transfer", 2, "Geçen yıl katıldığın 19 Mayıs gösterilerinde yaşadıklarını yazmak istiyorsun. Hangi türde yazmalısın?", "Anı",
          [["Biyografi", "kavrama", "Biyografi başka birinin hayatını anlatır; sen kendi yaşadığını anlatacaksın."], ["Masal", "kavrama", "Masal hayal ürünüdür; senin yaşadıkların gerçektir."], ["Haber başlığı", "strateji", "Başlık tek satırdır; yaşadıklarını ayrıntılı anlatamazsın."]],
          "Kendi yaşadığın gerçek bir olayı anlatacaksın.",
          ["Yaşanmış, gerçek ve sana ait bir olay anlatılacak.", "Kişinin kendi yaşadıklarını anlattığı tür anıdır.", "Cevap: Anı."],
          { kural: "Kendi yaşadığını anlatırsan anı, başkasının hayatını anlatırsan biyografi yazarsın." }),
      ],
      "trsam.okuma": [
        Q("trsam.okuma", "hatirlama", 1, BIYOGRAFI + "<br><br>Metne göre Mustafa Kemal nerede doğmuştur?", "Selanik'te",
          [["Samsun'da", "dikkat", "Samsun, 1919'da çıktığı şehirdir; doğum yeri değildir."], ["Çanakkale'de", "dikkat", "Çanakkale'de savaşmış, orada doğmamıştır."], ["Ankara'da", "dikkat", "Metinde Ankara geçmiyor."]],
          "İlk cümleye bak.",
          ["Soru doğum yerini soruyor.", "İlk cümle: “1881 yılında Selanik'te doğdu.”", "Cevap: Selanik'te."],
          { kural: "Bilgi sorularında cevabı metnin içinde bul ve kanıtını göster." }),
        Q("trsam.okuma", "aciklama", 2, ANI + "<br><br>Bu metne en uygun başlık hangisidir?", "Unutulmaz Bir Sabah",
          [["Babamın Bahçesi", "dikkat", "Metinde bahçeden söz edilmiyor."], ["Karadeniz'de Balıkçılık", "kavrama", "Liman ve vapur geçiyor ama konu balıkçılık değil."], ["Okulun İlk Günü", "dikkat", "Metinde okuldan söz edilmiyor."]],
          "Yazar o sabahı neden hâlâ hatırlıyor?",
          ["Metin, yazarın hiç unutmadığı heyecanlı bir sabahı anlatıyor.", "Başlık metnin konusunu yansıtmalı.", "En uygun başlık: Unutulmaz Bir Sabah."],
          { kural: "Başlık, metnin konusunu ya da ana fikrini yansıtmalıdır." }),
        Q("trsam.okuma", "uygulama", 2, ANI + "<br><br>Babanın “Bugünü hiç unutma oğlum.” demesinden ne anlaşılır?", "O günün çok önemli bir gün olduğu",
          [["Babanın çocuğa kızdığı", "kavrama", "Baba çocuğun elini sıkıca tutuyor; kızgınlık yok."], ["O günün sıradan bir gün olduğu", "kavrama", "Sıradan bir gün için “hiç unutma” denmez."], ["Vapurun geç kaldığı", "dikkat", "Metinde vapurun geç kaldığı söylenmiyor."]],
          "Bir şeyi “hiç unutma” diye öğütleriz, çünkü…",
          ["Baba, oğlunun bu anı hatırlamasını istiyor.", "Unutulmaması istenen günler önemli günlerdir.", "Cevap: O günün çok önemli bir gün olduğu."],
          { kural: "Kişilerin sözlerinden olayların önemini ve kişilerin duygularını çıkarabiliriz." }),
        Q("trsam.okuma", "transfer", 3, "Kütüphanede Millî Mücadele hakkında kitap arıyorsun. Mustafa Kemal'in Samsun'dan Ankara'ya kadar yaptığı yolculuğu öğrenmek için hangi kitap <b>en uygundur</b>?", "Samsun'dan Ankara'ya: Millî Mücadele'nin İlk Yılı",
          [["Karadeniz Mutfağından Lezzetler", "strateji", "Bu kitap yemekle ilgilidir; Millî Mücadele'yi anlatmaz."], ["Uzay Yolculuğuna Çıkalım", "strateji", "“Yolculuk” sözcüğü ortak ama konu uzaydır."], ["Masallar Ülkesi", "strateji", "Masallar hayal ürünüdür; tarihî bilgi vermez."]],
          "Kitap adının, aradığın konuyla ilgili olup olmadığına bak.",
          ["Aradığın konu: Samsun'dan Ankara'ya Millî Mücadele yolculuğu.", "Kitap başlığı bu konuyu doğrudan yansıtmalı.", "En uygun kitap: Samsun'dan Ankara'ya: Millî Mücadele'nin İlk Yılı."],
          { kural: "Kaynak seçerken başlığın aradığın konuyla uyumlu olmasına dikkat et." }),
      ],
    },
    oyun: [
      { tur: "eslestir", kaz: "trsam.tarih", soru: "Olayları tarihleriyle eşleştir.", ciftler: [["Samsun'a çıkış", "19 Mayıs 1919"], ["Amasya Genelgesi", "22 Haziran 1919"], ["Sivas Kongresi", "4 Eylül 1919"], ["TBMM'nin açılması", "23 Nisan 1920"]], aciklama: "Millî Mücadele 19 Mayıs 1919'da Samsun'da başladı; TBMM 23 Nisan 1920'de açıldı." },
      { tur: "eslestir", kaz: "trsam.tur", soru: "Metin türlerini tanımlarıyla eşleştir.", ciftler: [["Anı", "Yazarın kendi yaşadıkları"], ["Biyografi", "Bir kişinin hayatını başkasının anlatması"], ["Otobiyografi", "Kişinin kendi hayatını kendisinin anlatması"], ["Masal", "Hayal ürünü olağanüstü olaylar"]], aciklama: "Anıda yazar kendi yaşadıklarını, biyografide başkası bir kişinin hayatını, otobiyografide kişi kendi hayatını anlatır." },
      { tur: "sirala", kaz: "trsam.tarih", soru: "Millî Mücadele'nin ilk olaylarını oluş sırasına göre diz.", ogeler: ["Bandırma Vapuru ile İstanbul'dan ayrılış", "Samsun'a çıkış", "Amasya Genelgesi", "Erzurum Kongresi", "Sivas Kongresi"], aciklama: "16 Mayıs İstanbul, 19 Mayıs Samsun, 22 Haziran Amasya, 23 Temmuz Erzurum, 4 Eylül Sivas (hepsi 1919)." },
      { tur: "eslestir", kaz: "trsam.okuma", soru: "Metin parçalarını uygun başlıklarla eşleştir.", ciftler: [["Mustafa Kemal 1881'de Selanik'te doğdu…", "Bir Önderin Hayatı"], ["O sabah babamla iskeleye koştuk…", "Unutulmaz Bir Sabah"], ["Vapur, 19 Mayıs'ta Samsun'a ulaştı…", "Samsun'a Varış"]], aciklama: "Başlık, metnin konusunu yansıtır: hayat öyküsü, bir anı ve bir yolculuk." },
    ],
  });

  /* =============================== 6. Üretmek Gibisi Yok! =============================== */
  KONU_EKLE("tr", {
    id: "tr_uret2", tema: "tr2", ad: "Üretmek Gibisi Yok!", sayfa: "s. 110", gorev: "Verilen harflerden anlamlı kelimeler üretme",
    kazanimlar: [
      { id: "truret2.kelime", ad: "Verilen harflerle anlamlı kelimeler üretme" },
      { id: "truret2.turetme", ad: "Kök ve yapım ekleriyle yeni sözcükler türetme" },
    ],
    anlatim: [
      {
        baslik: "Harflerden kelimelere",
        metin: "Verilen harflerle kelime üretirken her harfi <b>en fazla bir kez</b> kullanırız. Önce <b>kısa kelimeleri</b> (at, ana, taş) bul, sonra harf ekleyerek <b>uzun kelimelere</b> geç. Sesli harfleri (a, e, ı, i, o, ö, u, ü) sessizlerin arasına yerleştirmek işini kolaylaştırır.",
        ornek: "BAYRAK → bay, kar, yara, kaya, arka, bayrak",
        durak: { soru: "VATAN harfleriyle (V, A, T, A, N) aşağıdaki kelimelerden hangisi yazılamaz?", secenekler: [["kitap", true, "Bu harflerde K, İ ve P yok."], ["tavan", false, "T, A, V, A, N harfleriyle yazılabilir."], ["ana", false, "A, N, A harfleri var."], ["ata", false, "A, T, A harfleri var."]] },
      },
      {
        baslik: "Kök ve ek",
        metin: "Bir sözcüğün <b>anlamlı en küçük parçasına kök</b> denir. Köke eklenen parçalara <b>ek</b> denir. <b>Yapım ekleri</b> yeni bir sözcük türetir: vatan → vatan<b>daş</b>, bayrak → bayrak<b>tar</b>, kahraman → kahraman<b>lık</b>. <b>Çekim ekleri</b> ise yeni sözcük türetmez, sözcüğü cümleye uydurur: asker<b>ler</b>, bayrağ<b>ı</b>.",
        ornek: "yol → yol<b>cu</b> (yeni sözcük, yapım eki) · yol<b>lar</b> (çoğul, çekim eki)",
        durak: { soru: "Aşağıdaki sözcüklerin hangisinde <b>yapım eki</b> vardır?", secenekler: [["vatandaş", true, "-daş eki “vatan” sözcüğünden yeni bir sözcük türetmiştir."], ["askerler", false, "-ler çoğul eki bir çekim ekidir."], ["bayrağı", false, "-ı eki bir çekim ekidir; yeni sözcük türetmez."], ["evde", false, "-de bulunma eki bir çekim ekidir."]] },
      },
      {
        baslik: "Türettiğin kelimelerle cümle kur",
        metin: "Ürettiğin ve türettiğin kelimeleri <b>cümle içinde</b> kullanmak onları kalıcı olarak öğrenmeni sağlar. Örneğin <b>-lık / -lik</b> ekiyle soyut kavramlar türetebilirsin: kahraman<b>lık</b>, özgür<b>lük</b>, birlik. <b>-lı / -li</b> ekiyle “sahip olan”, <b>-sız / -siz</b> ekiyle “olmayan” anlamı katarsın.",
        ornek: "“Atalarımızın kahramanlığı sayesinde özgürlüğümüze kavuştuk.”",
        durak: { soru: "“bağım” sözcüğüne hangi ek getirilirse “bağımsız” sözcüğü oluşur?", secenekler: [["-sız", true, "bağım + sız = bağımsız (bağı olmayan)."], ["-lı", false, "bağım + lı = bağımlı; anlamı tam tersidir."], ["-lık", false, "bağım + lık sözcüğü “bağımsız” anlamı vermez."], ["-cı", false, "bağım + cı Türkçede kullanılan bir sözcük değildir."]] },
      },
    ],
    uret: {
      "truret2.kelime": [
        Q("truret2.kelime", "uygulama", 1, "BAYRAK harfleriyle (B, A, Y, R, A, K) aşağıdaki kelimelerden hangisi yazılabilir?", "kaya",
          [["kayık", "dikkat", "Bu harflerde I yok ve yalnızca bir K var."], ["barış", "dikkat", "Bu harflerde I ve Ş yok."], ["yarın", "dikkat", "Bu harflerde I ve N yok."]],
          "Kelimenin her harfini verilen harflerle karşılaştır.",
          ["Verilen harfler: B, A, Y, R, A, K.", "“kaya” için K, A, Y, A gerekir; hepsi var.", "Cevap: kaya."],
          { kural: "Kelime üretirken her harfi en fazla bir kez kullanabilirsin." }),
        Q("truret2.kelime", "uygulama", 2, "MİLLET harfleriyle (M, İ, L, L, E, T) aşağıdaki kelimelerden hangisi <b>yazılamaz</b>?", "metin",
          [["telli", "islem", "T, E, L, L, İ harfleri var; bu kelime yazılabilir."], ["etli", "islem", "E, T, L, İ harfleri var; bu kelime yazılabilir."], ["mil", "islem", "M, İ, L harfleri var; bu kelime yazılabilir."]],
          "Hangi kelimede verilmeyen bir harf var?",
          ["Her kelimenin harflerini tek tek kontrol et.", "“metin” kelimesinde N harfi var; MİLLET'te N yok.", "Cevap: metin."],
          { kural: "Bir kelimeyi yazabilmek için tüm harfleri verilen harfler arasında olmalıdır." }),
        Q("truret2.kelime", "uygulama", 2, "ZAFER harflerinin (Z, A, F, E, R) bazılarıyla yazılabilen ve <b>küçük bir kemirgen hayvanın</b> adı olan kelime hangisidir?", "fare",
          [["zar", "kavrama", "Zar bu harflerle yazılır ama anlamı tavla zarıdır."], ["far", "kavrama", "Far bu harflerle yazılır ama arabanın lambasıdır."], ["kedi", "dikkat", "Kedi bu harflerle yazılamaz ve kemirgen değildir."]],
          "Kemirgen bir hayvan düşün; peynir sever!",
          ["İstenen kelime küçük bir kemirgendir.", "F, A, R, E harfleriyle “fare” yazılır.", "Cevap: fare."],
          { kural: "Kelime üretirken anlamı da düşün: üretilen kelime sözlükte bulunmalıdır." }),
        Q("truret2.kelime", "transfer", 2, "Sınıfta “harften kelime” yarışması yapılıyor. VATANDAŞ harfleriyle en <b>uzun</b> kelimeyi yazan kazanacak. Hangi kelimeyi yazarsan kazanırsın?", "vatandaş",
          [["vatan", "strateji", "Vatan 5 harflidir; tüm harfleri kullanan daha uzun bir kelime var."], ["tavan", "strateji", "Tavan 5 harflidir; daha uzun bir kelime yazılabilir."], ["taş", "strateji", "Taş 3 harflidir; çok kısadır."]],
          "Bazen verilen harflerin tamamı da bir kelimedir!",
          ["Seçeneklerdeki kelimelerin harf sayılarını karşılaştır.", "vatandaş 8 harflidir ve tüm harfleri kullanır.", "Cevap: vatandaş."],
          { kural: "Önce tüm harflerin bir kelime olup olmadığına bak, sonra kısa kelimelere geç." }),
        Q("truret2.kelime", "uygulama", 3, "MALAZGİRT harfleriyle yazılabilen ve bir <b>müzik aleti</b> adı olan kelime hangisidir?", "gitar",
          [["mazgal", "kavrama", "Mazgal yazılabilir ama müzik aleti değil, kale duvarındaki deliktir."], ["tarla", "kavrama", "Tarla yazılabilir ama ekin ekilen yerdir."], ["keman", "dikkat", "Keman bir müzik aletidir ama bu harflerde K, E ve N yok."]],
          "Telli bir müzik aleti düşün.",
          ["İstenen kelime bir müzik aletidir.", "G, İ, T, A, R harfleriyle “gitar” yazılır.", "Cevap: gitar."],
          { kural: "Harflerin tümü bir kelime olmasa da içinden birçok kelime çıkar: malazgirt → gitar, tarla, tamir…" }),
      ],
      "truret2.turetme": [
        Q("truret2.turetme", "hatirlama", 1, "“vatandaşlık” sözcüğünün kökü hangisidir?", "vatan",
          [["vatandaş", "kavrama", "“-daş” bir yapım ekidir; kök daha kısadır."], ["vat", "kavrama", "“vat” tek başına anlamlı değildir."], ["lık", "kavrama", "“-lık” bir ektir, kök değildir."]],
          "Sözcüğün sonundan ekleri tek tek at.",
          ["vatandaşlık → vatandaş + lık", "vatandaş → vatan + daş", "Kök: vatan."],
          { kural: "Kök: sözcüğün anlamlı ve daha küçük parçalara ayrılamayan bölümü." }),
        Q("truret2.turetme", "aciklama", 2, "Aşağıdaki sözcüklerin hangisinde büyük harfle gösterilen ek bir <b>çekim eki</b>dir?", "askerLER",
          [["askerLİK", "kavrama", "-lik yeni bir sözcük türetir; yapım ekidir."], ["yolCU", "kavrama", "-cu yeni bir sözcük türetir; yapım ekidir."], ["vatanDAŞ", "kavrama", "-daş yeni bir sözcük türetir; yapım ekidir."]],
          "Hangi ek yeni bir anlam değil, yalnızca çoğulluk katar?",
          ["Yapım eki yeni sözcük türetir; çekim eki türetmez.", "-ler eki “asker” sözcüğünü çoğul yapar, yeni sözcük türetmez.", "Cevap: askerLER."],
          { kural: "Çekim ekleri: -ler/-lar, -i, -e, -de, -den… Yeni sözcük türetmez." }),
        Q("truret2.turetme", "uygulama", 2, "“kahraman” sözcüğüne hangi ek getirilirse “kahraman olma durumu” anlamına gelen sözcük türer?", "-lık",
          [["-lar", "kavrama", "-lar çoğul ekidir; “kahramanlar” birden çok kahraman demektir."], ["-ca", "kavrama", "“kahramanca” kahraman gibi anlamına gelir; durum bildirmez."], ["-ı", "kavrama", "-ı bir çekim ekidir; yeni sözcük türetmez."]],
          "“-lık / -lik” eki “olma durumu” anlamı katar.",
          ["İstenen anlam: kahraman olma durumu.", "kahraman + lık = kahramanlık.", "Cevap: -lık."],
          { kural: "-lık/-lik/-luk/-lük: durum ya da kavram bildiren sözcükler türetir (özgürlük, birlik)." }),
        Q("truret2.turetme", "uygulama", 2, "Aşağıdaki sözcüklerden hangisi “bayrak” kökünden <b>türetilmiş</b> bir sözcüktür?", "bayraktar",
          [["bayrakları", "kavrama", "-lar ve -ı çekim ekleridir; yeni sözcük türemez."], ["bayrağa", "kavrama", "-a yönelme ekidir; çekim ekidir."], ["bayrakta", "kavrama", "-ta bulunma ekidir; çekim ekidir."]],
          "Yeni bir anlam kazanan sözcüğü bul.",
          ["Türemiş sözcük, yapım ekiyle yeni anlam kazanır.", "bayrak + tar = bayraktar (bayrağı taşıyan kişi).", "Cevap: bayraktar."],
          { kural: "Türemiş sözcük = kök + yapım eki (bayraktar, vatandaş, yolcu)." }),
        Q("truret2.turetme", "transfer", 2, "“Atalarımız ……… için büyük bedeller ödedi.” cümlesindeki boşluğa “özgür” sözcüğünden türetilen hangi sözcük gelmelidir?", "özgürlük",
          [["özgürce", "kavrama", "“özgürce” nasıl yapıldığını anlatır; cümleye uymuyor."], ["özgürler", "kavrama", "-ler çekim ekidir; cümlede anlam bozulur."], ["özgürsüz", "kavrama", "Böyle bir sözcük Türkçede kullanılmaz."]],
          "Boşluğa bir kavram adı gelmeli.",
          ["Cümlede “… için bedel ödemek” kalıbı var; bir kavram gerekiyor.", "özgür + lük = özgürlük (özgür olma durumu).", "Cevap: özgürlük."],
          { kural: "Türettiğin sözcüğü cümlede dene; anlam bozulmuyorsa doğru seçmişsindir." }),
        Q("truret2.turetme", "baglanti", 3, "1. temada sözcüğün gerçek ve mecaz anlamını öğrenmiştin. “Ordunun <b>bayraktarı</b> oldu.” cümlesinde mecaz anlamda “bir işe önderlik eden” anlamı kazanan sözcüğün kökü ve aldığı yapım eki hangisidir?", "bayrak + -tar",
          [["bay + -raktar", "kavrama", "“-raktar” diye bir ek yoktur; kök “bayrak”tır."], ["bayraktar + -ı", "kavrama", "-ı çekim ekidir; soru yapım ekini soruyor."], ["bayra + -ktar", "kavrama", "“bayra” anlamlı bir kök değildir."]],
          "Önce çekim ekini at, sonra yapım ekini ayır.",
          ["bayraktarı → bayraktar + ı (çekim eki).", "bayraktar → bayrak + tar (yapım eki).", "Cevap: bayrak + -tar."],
          { kural: "Ekleri sondan başlayarak ayır: önce çekim ekleri, sonra yapım ekleri; geriye kök kalır." }),
      ],
    },
    oyun: [
      { tur: "uret", kaz: "truret2.kelime", soru: "VATANDAŞ harfleriyle en az 3 anlamlı kelime üret.", harfler: "VATANDAŞ", kelimeler: ["vatandaş", "vatan", "tavan", "tava", "dava", "dana", "adaş", "ada", "ana", "ata", "şan", "taş", "ad", "at", "an"], hedef: 3, aciklama: "Vatan, tavan, dava, dana, ada, taş, şan… Vatandaş kelimesinin içinde koca bir vatan saklı!" },
      { tur: "uret", kaz: "truret2.kelime", soru: "BAYRAK harfleriyle en az 3 anlamlı kelime üret.", harfler: "BAYRAK", kelimeler: ["bayrak", "kabar", "arka", "ayar", "kara", "kaya", "yaka", "yara", "bay", "bar", "kar", "yar", "ray", "ark", "bak", "yak", "ak", "ay"], hedef: 3, aciklama: "Kaya, yaka, yara, arka, kara, bay, kar… Harflerin yerini değiştirerek yeni kelimeler bulabilirsin." },
      { tur: "uret", kaz: "truret2.kelime", soru: "ZAFERLİ harfleriyle en az 3 anlamlı kelime üret.", harfler: "ZAFERLİ", kelimeler: ["zafer", "zarif", "lazer", "rezil", "lira", "fare", "file", "azil", "zira", "arif", "ela", "far", "fal", "fil", "lif", "laf", "fer", "zil", "zar", "il", "el", "er", "ez", "az", "al"], hedef: 3, aciklama: "Zafer, fare, lira, zil, fil, far, zarif… Kısa kelimelerden başla!" },
      { tur: "uret", kaz: "truret2.kelime", soru: "MİLLET harfleriyle en az 3 anlamlı kelime üret.", harfler: "MİLLET", kelimeler: ["millet", "illet", "telli", "etli", "elti", "ilet", "mil", "mit", "tim", "tel", "il", "el", "et"], hedef: 3, aciklama: "Millet, telli, etli, mil, tel, el, et… İki L harfini unutma!" },
      { tur: "uret", kaz: "truret2.kelime", soru: "MALAZGİRT harfleriyle en az 3 anlamlı kelime üret.", harfler: "MALAZGİRT", kelimeler: ["malazgirt", "mazgal", "ziraat", "tamga", "gitar", "tamir", "talim", "tarla", "imla", "arma", "lama", "gala", "gram", "tarz", "mart", "amir", "mazi", "lira", "mal", "zar", "tam", "mat", "ama", "ala", "alt", "gaz", "zam", "zil", "mil", "mit", "tim", "iz", "al", "at", "az"], hedef: 3, aciklama: "Gitar, tarla, tamir, mazgal, gram, mart… Uzun bir sözcükte bir sürü kelime gizlidir!" },
      { tur: "eslestir", kaz: "truret2.turetme", soru: "Kökleri yapım ekiyle türeyen sözcüklerle eşleştir.", ciftler: [["vatan", "vatandaş"], ["bayrak", "bayraktar"], ["kahraman", "kahramanlık"], ["yol", "yolcu"]], aciklama: "Yapım ekleri köke yeni anlam katar: vatan-daş, bayrak-tar, kahraman-lık, yol-cu." },
    ],
  });
})();
